### ISSUE TITLE
Check the new DBSWriter 

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#1012]
We use one writer endpoint in Unified to update dataset statuses (`updateDatasetType`) [1] I've tested it w/ the new server via the following script:

```
from dbs.apis.dbsClient import DbsApi
from optparse import OptionParser

def getDatasetStatus(dataset, readerUrl):
  dbsapi = DbsApi(url = readerUrl)
  reply = dbsapi.listDatasets(dataset=dataset,dataset_access_type='*',detail=True)
  if len(reply):
    return reply[0]['dataset_access_type']
  else:
    return None


def testDBSWriter(dataset, status, readerUrl, writerUrl):

  dbsWriterTest = DbsApi(url = writerUrl)

  print "Dataset status before update: " + str(getDatasetStatus(dataset, readerUrl))
  print "Setting the status to " + str(status)
  
  result = dbsWriterTest.updateDatasetType(dataset = dataset, dataset_access_type= status)

  print "Setter function returned: " + str(result)
  print "Dataset status after update: " + str(getDatasetStatus(dataset, readerUrl))


def main():

  parser = OptionParser()
  parser.add_option("-d", "--dataset", dest="dataset",
                      help="Dataset name")
  parser.add_option("-s", "--status", dest="status", 
                      help="Status to set the dataset")

  parser.add_option("-r", "--readerUrl", dest="readerUrl",
                      help="dbs reader url")

  parser.add_option("-w", "--writerUrl", dest="writerUrl",
                      help="dbs writer url")



  (options, args) = parser.parse_args()
  
  testDBSWriter(str(options.dataset), str(options.status), str(options.readerUrl), str(options.writerUrl))
  

if __name__ == "__main__":
    main()
```

and I got an unexpected result:
```
$ python checkDBSWriter.py -r "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader" -w "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter" -d "/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/AODSIM" -s "INVALID"
Dataset status before update: VALID
Setting the status to INVALID
Setter function returned: []
Dataset status after update: None
```

I checked the production endpoints as well to make sure that the script works fine and it works fine:
```
$ python checkDBSWriter.py -r "https://cmsweb.cern.ch/dbs/prod/global/DBSReader" -w "https://cmsweb.cern.ch/dbs/prod/global/DBSWriter" -d "/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIWinter19PFCalib18wmLHEGS-ideal_105X_upgrade2018_design_v3-v1/GEN-SIM" -s "VALID"
Dataset status before update: INVALID
Setting the status to VALID
Setter function returned: None
Dataset status after update: VALID
$ python checkDBSWriter.py -r "https://cmsweb.cern.ch/dbs/prod/global/DBSReader" -w "https://cmsweb.cern.ch/dbs/prod/global/DBSWriter" -d "/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIWinter19PFCalib18wmLHEGS-ideal_105X_upgrade2018_design_v3-v1/GEN-SIM" -s "INVALID"
Dataset status before update: VALID
Setting the status to INVALID
Setter function returned: None
Dataset status after update: INVALID
```

Not sure what's wrong for now. Investigating.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L2808

**Comment by vkuznet** [comment]
@haozturk , adjusting your script to py3 (print function) and running it I get correct result:

```
./hasan.py -r "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader" -w "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter" -d "/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/AODSIM" -s "INVALID"
Dataset status before update: None
Setting the status to INVALID
Setter function returned: []
Dataset status after update: None
```
The dataset you choose does not exist in DBS testbed and therefore it status before update is None and setting status does not change anything.

I also confirm this with simpler curl calls for it (here `scurl` is my alias to `curl -L -k --key ~/.globus/userkey.pem --cert ~/.globus/usercert.pem):`
```
scurl "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/datasets?dataset=/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/AODSIM&detail=true"
[]
```
So, there is no such dataset in DBS testbed instance. But if I do:
```
scurl "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/datasets?dataset=/ZMM_13TeV_TeCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/*&detail=true&dataset_access_type=*"
[
{"acquisition_era_name":"RunIIAutumn18DR","create_by":"wmagent@vocms0280.cern.ch","creation_date":1571147227,"data_tier_name":"GEN-SIM-RAW","dataset":"/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW","dataset_access_type":"VALID","dataset_id":13957793,"last_modification_date":1571859873,"last_modified_by":"cmsunified@vocms0268.cern.ch","physics_group_name":"NoGroup","prep_id":"MUO-RunIIAutumn18DR-00015","primary_ds_name":"ZMM_13TeV_TuneCP5-pythia8","primary_ds_type":"mc","processed_ds_name":"RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2","processing_version":2,"xtcrosssection":null}
]
```
Therefore, the dataset `/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DRSNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW` is not present in testbed.

If you run your script as is, then dump the `reply` to see what is your reply from DBS client. Make sure you use recent DBSClient version 4.0.7 and python3. In addition ,check with curl call your dataset(s). The DBS APIs are listed here https://github.com/dmwm/dbs2go/blob/master/docs/apis.md and you can use them directly with curl w/o DBS client.

**Comment by haozturk** [comment]
Hi @vkuznet thanks for checking. The dataset that I used in the issue body existed, however the API call that I did deleted the dataset from the db if I'm not wrong. To make sure, I used the example dataset that you've given and it got deleted as well:

```
$ scurl "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/datasets?dataset=/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW&detail=true"
Enter PEM pass phrase:
[
{"acquisition_era_name":"RunIIAutumn18DR","create_by":"wmagent@vocms0280.cern.ch","creation_date":1571147227,"data_tier_name":"GEN-SIM-RAW","dataset":"/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW","dataset_access_type":"VALID","dataset_id":13957793,"last_modification_date":1571859873,"last_modified_by":"cmsunified@vocms0268.cern.ch","physics_group_name":"NoGroup","prep_id":"MUO-RunIIAutumn18DR-00015","primary_ds_name":"ZMM_13TeV_TuneCP5-pythia8","primary_ds_type":"mc","processed_ds_name":"RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2","processing_version":2,"xtcrosssection":null}
]


$ python checkDBSWriter.py -r "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader" -w "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter" -d "/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW" -s "INVALID"
Dataset to be checked: /ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW
Dataset status before update: VALID
Setting the status to INVALID
Setter function returned: []
Dataset status after update: None

$ scurl "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/datasets?dataset=/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW&detail=true"
Enter PEM pass phrase:
[]
```
Do you know why this happens? This seems very dangerous to me.

We use an old dbs client. Is this because of that? I haven't tried to do it in python3 w/ a newer client. I'll do it today. But, if the problem is the old client, then we need some time to update the relevant code to python3. The project is migrated to python3 partially, however this part of the code is still python2 unfortunately.

Thanks!

**Comment by vkuznet** [comment]
Hasan, the dataset is there, if I do the following query:
```
scurl "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter/datasets?dataset=/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW&is_dataset_valid=0&dataset_access_type=INVALID"
[
{"dataset":"/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW"}
]
```
and if you'll adjust your script to use this code:
```
    dbsapi = DbsApi(url = str(options.readerUrl))
    reply = dbsapi.listDatasets(dataset=str(options.dataset),dataset_access_type='*',is_dataset_valid=0,detail=True)
    print(reply)
```
then it prints out the correct result:
```
[{'acquisition_era_name': 'RunIIAutumn18DR', 'create_by': 'wmagent@vocms0280.cern.ch', 'creation_date': 1571824350, 'data_tier_name': 'AODSIM', 'dataset': '/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/AODSIM', 'dataset_access_type': 'INVALID', 'dataset_id': 13961613, 'last_modification_date': 1651060173, 'last_modified_by': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=valya/CN=443502/CN=Valentin Y Kuznetsov', 'physics_group_name': 'NoGroup', 'prep_id': 'MUO-RunIIAutumn18DR-00015', 'primary_ds_name': 'ZMM_13TeV_TuneCP5-pythia8', 'primary_ds_type': 'mc', 'processed_ds_name': 'RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2', 'processing_version': 2, 'xtcrosssection': None}]
```

Therefore, the issue is parameters you pass to `listDatasets` API. I think we'll need to slightly adjust DBSReader to properly assign both options (`is_valid_dataset` and `dataset_access_type`) when only one is provided by the client. In other words new DBSReader uses explicit set of parameters. I'll think about how to correctly assign parameters in this case.

**Comment by haozturk** [comment]
Ah, now I understand. I've tested it again and I'm convinced that it works. This means that we're ready for the migration as well. Sorry for the noise and thanks for the prompt check Valentin!

**Comment by belforte** [comment]
@vkuznet and CompOps can you clarify `dataset_access_type` vs. `is_dataset_valid` ?
AFAIK this is the first time that I see `is_dataset_valid=0` being needed to list a dataset.
Was a default value changed in move to new DBS server ?
(it would also be good if https://github.com/dmwm/DBSClient/blob/main/src/python/dbs/apis/dbsClient.py listed what is the default value of arguments).
I noticed that in `is_dataset_valid` is never used in neither WMCore nor CRAB (I do not find such string in GitHub).
We always look for what's commonly referred to as "dataset status" as stored in `dataset_access_type`.

I thought that usually operations (and users on phys03 dbs instance) only modfy `dataset_access_type`, see e.g. 
https://github.com/dmwm/DBS/blob/master/Client/utils/DataOpsScripts/DBS3SetDatasetStatus.py
Which what we have been recommending to users since start of DBS3 times, and which I expect to still work.

Indeed I have two questions here:
1. what are arguments default values for DBSClient calls
2. what is the operational practice in using all those flags, did Ops stick to a consistent policy over time, or was something changed at some point ? I am afraid I never found a documentation of "dataset life cycle".

**Comment by vkuznet** [comment]
@belforte , this is what we try to figure from Yuyi. Here is her latest response:
```
   DATASET_ACCESS_TYPE and IS_DTATSET_VALID/IS_FILE_VALID  are two
   different way to describe a file and defined by different CMS groups  .
   Yes, they have some common.

   The DATASET_ACCESS_TYPE is used by the WM to label the data is in still
   in  PRODUCTION or it can be used by others (in VALID).

   IS_FILE_VALID is used by another team they verify the data any time.
   The data could be VALID so they can be released by production group,
   but they could be damaged after that, for example, during the
   transferring.  If a file becomes bad, then one will mark
   the IS_FILE_VALID to 0 instead of going back to change
   the DATASET_ACCESS_TYPE. If all the files are invalid in the entire
   dataset, then the IS_DTATSET_VALID will be set to 0.


   The principle of DBS is to keep as much as useful data history as we
   can. This is the only place CMS keeps file history. So we never delete
   a dataset/block/file from DBS. We use these label to describe them.
```
Once we got reply from her about defaults we'll adjust new DBS server code accordingly. So far new DBSReader use the following logic https://github.com/dmwm/dbs2go/blob/master/dbs/datasets.go#L73-L93 As you can see we setup by default `is_dataset_valid` to be 1 (if not provided) and this is the reason why initially his call to `listDatasets` does not show the dataset (this field is used in query). My understanding that in python DBSReader code it is different and we're trying to figure this out.

**Comment by belforte** [comment]
thanks for having clarified default value.
I am afraid that Yuyi describes some initial setup from 1-+ years ago, she will not be able to tell us how many different teams of CMS Operation people may be using those fields recently, and which policies they use.
In a way the question is really "who and why set the is_dataset_valid flag to 0 on this dataset", i.e. whether I should e.g. change CRAB code to reports those datasets as "DELETED" rather than "NON-EXISTING" .

**Comment by vkuznet** [comment]
after discussion with Yuyi we adjusted new DBSReader code to properly return dataset w/o specifying `is_dataset_valid`, so now I can do as usual:
```
scurl "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter/datasets?dataset=/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW&dataset_access_type=*"
[
{"dataset":"/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW"}
]
```
and if you want full details you can do:
```
scurl "https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter/datasets?dataset=/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW&dataset_access_type=*&detail=true"
[
{"acquisition_era_name":"RunIIAutumn18DR","create_by":"wmagent@vocms0280.cern.ch","creation_date":1571147227,"data_tier_name":"GEN-SIM-RAW","dataset":"/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM-RAW","dataset_access_type":"INVALID","dataset_id":13957793,"last_modification_date":1651074604,"last_modified_by":"/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=haozturk/CN=839926/CN=Hasan Ozturk","physics_group_name":"NoGroup","prep_id":"MUO-RunIIAutumn18DR-00015","primary_ds_name":"ZMM_13TeV_TuneCP5-pythia8","primary_ds_type":"mc","processed_ds_name":"RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2","processing_version":2,"xtcrosssection":null}
]
```
so, it only requires `dataset_access_type=*` to list all (VALID and INVALID, etc.) datasets.

The DBSClient will do the same, i.e. using this code:
```
    reply = dbsapi.listDatasets(dataset=str(options.dataset),dataset_access_type='*',detail=True)
    print(reply)
```
I get proper results:
```
[{'acquisition_era_name': 'RunIIAutumn18DR', 'create_by': 'wmagent@vocms0280.cern.ch', 'creation_date': 1571824350, 'data_tier_name': 'AODSIM', 'dataset': '/ZMM_13TeV_TuneCP5-pythia8/RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2/AODSIM', 'dataset_access_type': 'INVALID', 'dataset_id': 13961613, 'last_modification_date': 1651060173, 'last_modified_by': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=valya/CN=443502/CN=Valentin Y Kuznetsov', 'physics_group_name': 'NoGroup', 'prep_id': 'MUO-RunIIAutumn18DR-00015', 'primary_ds_name': 'ZMM_13TeV_TuneCP5-pythia8', 'primary_ds_type': 'mc', 'processed_ds_name': 'RunIIAutumn18DR-SNBHP_SNB_HP_102X_upgrade2018_realistic_v17-v2', 'processing_version': 2, 'xtcrosssection': None}]
```

Feel free to verify yourself, but to me the issue is really closed now.

**Comment by vkuznet** [comment]
@belforte regarding your comment:
```
In a way the question is really "who and why set the is_dataset_valid
   flag to 0 on this dataset", i.e. whether I should e.g. change CRAB code
   to reports those datasets as "DELETED" rather than "NON-EXISTING"
```
To find DELETED dataset you'll use `dataset_access_type=DELETED` or if you want to know all datasets you'll use `dataset_access_type=*`, i.e. this is exact behavior as you get used to. Therefore, I don't think you need to change anything in CRAB code.

**Comment by belforte** [comment]
thanks @vkuznet and Yuyi. For my undertanding, are you saying that listDatasets will make an SQL query which ignores `is_dataset_valid` field in case it is not specified ?

**Comment by vkuznet** [comment]
yes, but by default only valid dataset are listed, please have a look at https://github.com/dmwm/dbs2go/blob/master/dbs/datasets.go#L73-L93, it says:
- if no `dataset_access_types` parameter use VALID as default
- if `dataset_access_types=*` use `like %` which us any in ORACLE
- if `is_dataset_valid` is provided use it in query

Therefore, if you want INVALID, DELETED dataset, you may use `dataset_access_type` specific value, and if you want to query dataset with specific value of `is_valid_dataset` you must specify this parameter in your API.
