### ISSUE TITLE
Introduce a limitation to the workflow assignment to keep the total number of acquired workflows under a limit.

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#1051]
**Impact of the new feature**
Unified/assignor

**Is your feature request related to a problem? Please describe.**
Yes, the system is under heavy load and we need to lower down the total number of active workflows in the system.

**Describe the solution you'd like**

    1. We’ll remove the current priority based assignment limitation (stop anything <= 85k)
    2. We’ll introduce a new logic to stop the assignment of workflows based on the nWorkflows in acquired (pending workflows to run) and priority together. It'll work as follows:

       a. Every priority block will have its own threshold.
       b. If (nWorkflows in acquired) > (the threshold of the workflow's priority block) , we’ll stop the assignment. Else, we’ll assign.
       c. Higher priority workflows will have high threshold and vice versa. So, what we'll use the following params once we implement this:

          i. Block1: 20k
          ii. Block2: 16.7k (Total number of workflows in acquired right now. We picked this limit to be able to run new block2 injections. We'll reduce it in time.)
          iii. Block3: 1k
          iiii. Block4 and lower priority: 0

**Describe alternatives you've considered**
Nonce

**Additional context**
We'll keep tuning these numbers as we digest the load.

**Comment by haozturk** [comment]
Hi @amaltaro what's the most efficient way to get the number of workflows in acquired? I can get all the workflows in acquired and count, but maybe there is a better way?

**Comment by amaltaro** [comment]
The best will be for us to create a reduce function in WMCore such that you get only the `count` of workflows in the desired status. For now, I would suggest to use this ReqMgr2 API (remove testbed):
https://cmsweb-testbed.cern.ch/reqmgr2/data/request?status=acquired&detail=false

then get the length of that list.

**Comment by haozturk** [comment]
Thanks @amaltaro will do that. I agree that an api returning just the count would have been more efficient
