### ISSUE TITLE
reqmgr 2 change seems to be gone.

### ISSUE THREAD

**Issue by ticoann** [CMSCompOps/WmAgentScripts#127]
@vlimant, @julianbadillo Hi Jean-Roch, Julian

I made this change back in October.

https://github.com/CMSCompOps/WmAgentScripts/commit/a40dbb4b7210d8c5bfdc7a5cf75fb8d4f7ee1d78#diff-3fc98fbeeaadf6df0cfbc50d59551ffe

But it seem it is not exist in current file. But I don't see anyone was removing that change either.
Do you know what happen? was that causing the problem?

**Comment by vlimant** [comment]
Hi,
https://github.com/CMSCompOps/WmAgentScripts/commit/f5ff1190c07c7d972dcb2d61d6bed11407f4456c labelled "Get back to previous version before ReqMgr2"

the current schema of trying reqmgr2, fail and fall back to reqmgr1 was probably too heavy ; Julian made that move, and indeed the changes in the commit have to be merged back in again.

**Comment by ticoann** [comment]
Thanks Jean-Roch,  I talked Julian he said that there was problem with assign script when it gets cloned.
So it removed it. I will make the pull request again after fixing the problem he reported.

**Comment by vlimant** [comment]
All recovered.
