### ISSUE TITLE
Setting acqera and procstring correctly when assigning

### ISSUE THREAD

**Issue by areinsvo** [CMSCompOps/WmAgentScripts#150]
@mcremone @prozober @amaltaro @vlimant 

I want to make sure that the value for acquisition era and processing string are being fixed correctly in assign.py. I've had several conversations today about it and want to make sure we are all on the same page. There is still some confusion on what to set the values to for merge ACDCs. Now that we are using request manager 2, do we have to provide values for era and processing string, or do we still leave those blank?

Here is my best understanding of how it needs to be done:

        #Dealing with era and proc string
        if taskchain:
            # Setting the Era and ProcStr values per Task
            for key, value in schema.items():
                if type(value) is dict and key.startswith("Task"):
                    try:
                        procstring[value['TaskName']] = value['ProcessingString']
                        era[value['TaskName']] = value['AcquisitionEra']
                    except KeyError:
                        print("This taskchain request has no AcquisitionEra or ProcessingString defined into the Tasks, aborting...")
                        sys.exit(1)
        # Adding the special string - in case it was provided in the command line
        if options.special:
            specialStr = '_' + str(options.special)
            for key, value in procstring.items():
                procstring[key] = value + specialStr
        # Override if a value is given using the procstring command
        if options.procstring:
            procstring = options.procstring
        elif not taskchain:
            procstring = wf.info['ProcessingString']
        if options.era:
            era = options.era
        elif not taskchain:
            era = wf.info['AcquisitionEra']
        #Set era and procstring to none for merge ACDCs inside a task chain
        if schema["RequestType"] == "Resubmission") and wfInfo.info["PrepID"].startswith("task") and "Merge" in schema["InitialTaskPath"].split("/")[-1]:
            era = None
            procstring = None

The full script is here: https://github.com/areinsvo/WmAgentScripts-1/tree/EditAssignment/
Alan, does this look correct for merge ACDs?

**Comment by amaltaro** [comment]
Allie, I would change the upper part to more or less the following:
```
if type(value) is dict and key.startswith("Task"):
                try:
                    if 'ProcessingString' in value:
                        procstring[value['TaskName']] = value['ProcessingString']
                    else:
                        procstring[value['TaskName']] = schema['ProcessingString']
                    if 'AcquisitionEra' in value:
                        era[value['TaskName']] = value['AcquisitionEra']
                    else:
                        procstring[value['TaskName']] = schema['AcquisitionEra']
                except KeyError:
```

and for the last lines, I didn't check what happen downstream, but AcquisitionEra and ProcessingString cannot be sent AT ALL within the parameters during assignment (meaning, don't send empty strings, don't send None).

**Comment by areinsvo** [comment]
Hi Alan,
Thanks, I can make those changes.

Downstream, in reqMgrClient.py, there are these lines in assignWorkflow that make it so that the parameters aren't sent at all for merge ACDCs:
    pop_useless = ['AcquisitionEra','ProcessingString']
    for what in pop_useless:
        if defaults[what] == None:
            defaults.pop(what)

**Comment by areinsvo** [comment]
The changes were made and submitted in this pull request. We can continue the discussion there, if need be. 
https://github.com/CMSCompOps/WmAgentScripts/pull/151
