### ISSUE TITLE
Backfill option is not setting all value properly

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#161]
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/prozober_task_SUS-RunIISpring16DR80-Backfill-00140__v1_T_160720_143230_6939

 is an example

**Comment by prozober** [comment]
Hi,

The processing string and acquisition era for tasks belonging to TaskChain workflows, are not  correctly set when we want to create backfills. The problem was fixed here #162.

**Comment by vlimant** [comment]
thanks
