### ISSUE TITLE
Merge ACDC priority should be very high

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#165]
if these stay forever in acquired, then the files will go away and we will have to start everything over.
set 5M+priority to merge ACDC.
this is clearly not optimal since that means that any subsequent task will be high priority too and invert everything. 

@amaltaro best would be to have the agents acquire ACDC in highest priority.

**Comment by amaltaro** [comment]
I'm sure you would eventually regret what you are asking for. I've seen cases where ACDC is almost as big as the original workflow, so we better keep it simple and use only priority numbers IMO.

**Comment by vlimant** [comment]
it's ok. if the inial wf got running/completed with low priority, then having the acdc acquired first thing is fine and htcondor will deal with priority if needed.
