### ISSUE TITLE
Don't create ACDC workflows for Cleanup and LogCollect tasks

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#167]
It's not supported by the system. This type of data is not uploaded to the ACDCServer.
Please, fix the scripts creating ACDCs.

**Comment by amaltaro** [comment]
Has this issue been fixed? I think so, since we had no more incidents like this. If so, can someone please close this issue?

**Comment by prozober** [comment]
The issue has been fixed. I haven't seen any new case.
