### ISSUE TITLE
setCascadeStatus.py script is crashing

### ISSUE THREAD

**Issue by jenimal** [CMSCompOps/WmAgentScripts#173]
I was going to cleanup orphaned ACDC's and recovery's out of the system. 
We have the setCascadeStatus.py script, but it is currently crashing out:
jen_a@vocms049:~/WmAgentScripts $ python setCascadeStatus.py -h
usage: python ../RelVal/setrequeststatus.py <inputFile_containing_a_list_of_workflows> <new_status>
jen_a@vocms049:~/WmAgentScripts $ more announced
jen_a_ACDC_HIG-RunIISpring16DR80-01778_00601_v0__160818_110245_2528
jen_a_ACDC_Run2016B-v2-MuonEG-29Jul2016_8016_160809_204626_3775
jen_a_ACDC_Run2016B-v2-MuonEG-29Jul2016_8016_160809_204643_1061
jen_a_ACDC_Run2016B-v2-MuonEG-29Jul2016_8016_160809_204651_5106
jen_a_ACDC_TOP-RunIISpring16DR80-00076_00609_v1__160829_210652_541
prozober_ACDC_Run2016B-2-JetHT-01Jul2016_8013p1_160726_141143_6462
prozober_ACDC_Run2016B-2-JetHT-01Jul2016_8013p1_160726_141150_9198
prozober_ACDC_Run2016B-2-JetHT-01Jul2016_8013p1_160726_141158_1010
prozober_ACDC_Run2016B-2-JetHT-01Jul2016_8013p1_160726_141205_357
prozober_ACDC_Run2016B-2-JetHT-01Jul2016_8013p1_160726_141222_1231
jen_a@vocms049:~/WmAgentScripts $ python setCascadeStatus.py announced announced
Setting jen_a_ACDC_HIG-RunIISpring16DR80-01778_00601_v0__160818_110245_2528 to announced
404 Not Found
Traceback (most recent call last):
File "setCascadeStatus.py", line 55, in <module>
main()
File "setCascadeStatus.py", line 51, in main
print "Final status is: %s" % getStatus(url, workflow)
File "setCascadeStatus.py", line 34, in getStatus
t = s['RequestStatus']
KeyError: 'RequestStatus'
jen_a@vocms049:~/WmAgentScripts $

**Comment by vlimant** [comment]
The script was pointing by default to testbed, hence the crash.

 I took the occasion to rewrite it

https://github.com/CMSCompOps/WmAgentScripts/commit/6c851ff0174412deb3eb9dd5572a1037fe67d4ca#diff-984dc8de5d06d4a5adc06cf75f2dac77

**Comment by jenimal** [comment]
Tested it, and it works, but you changed the options, feeding it a file with a list of workflows is actually more convenient when you are cleaning up a lot of workflows, I can easily write a shell wrapper around it but was wondering why you changed that behavior?  

I will also update the documentation on it.
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompOpsWorkflowOperationsWMAgentScripts#set_CascadeStatus_py

**Comment by vlimant** [comment]
the help is misleading. it actually supports both. ac quick look in the code tells it within 10s

**Comment by jenimal** [comment]
Running this script to change workflows from closed-out to announced isn't working:
jen_a@vocms049:~/WmAgentScripts $ python setCascadeStatus.py --w dmason_BoogaBoogaDCache_160309_055331_9265 --s announced
Setting dmason_BoogaBoogaDCache_160309_055331_9265 to announced
jen_a@vocms049:~/WmAgentScripts $ python setCascadeStatus.py -w dmason_BoogaBoogaDCache_160309_055331_9265 -s 'announced'
Setting dmason_BoogaBoogaDCache_160309_055331_9265 to announced
jen_a@vocms049:~/WmAgentScripts $ 


and when I look:
https://cmsweb.cern.ch/reqmgr/view/details/dmason_BoogaBoogaDCache_160309_055331_9265

it's still in closed-out

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/33edd1c9f68ba36227b4a6381fab26394d5670de will fix that issue with cascading announced
