### ISSUE TITLE
recoveryMissingLumis.py doesn't work with reqmgr2

### ISSUE THREAD

**Issue by ticoann** [CMSCompOps/WmAgentScripts#179]

**Comment by vlimant** [comment]
@prozober FYI
@ticoann can you please be more precise in what was not functioning ?

**Comment by ticoann** [comment]
Hi Jean-Roch, Sorry for getting back to the issue late.

I didn't  actually run the script. But by looking at the code it seems it is using.

from WMCore.Services.RequestManager.RequestManager import RequestManager

Which is only ReqMgr1 client. 

This need to be changed with ReqMgr2 client.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/ReqMgr/ReqMgr.py

That is why I assume it is not working with ReqMgr2

**Comment by vlimant** [comment]
I think I got it to work.
