### ISSUE TITLE
Incorporate stuck transfer information

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#183]
https://test-cmstransfererrors.web.cern.ch/test-CMSTransferErrors/stuck_X.json

where X=1,2,m1,m3,m4,m5,m6.

The numbers refer to transfer error code, not time periods. mN refers to -N. The values are documented as basis values here: https://cmsweb.cern.ch/phedex/datasvc/doc/blockarrive

**Comment by vlimant** [comment]
@sidnarayanan is there a non-test url for this now ?
@areinsvo @mcremone FYI

**Comment by sidnarayanan** [comment]
@sebastianpulido can this be deployed in a non-test url?

**Comment by vlimant** [comment]
what is the url we can use in production ?

**Comment by vlimant** [comment]
@sidnarayanan @sebastianpulido what is the production url ?

**Comment by sebastianpulido** [comment]
Hi, I'm working on enabling the production url. Let you know.

**Comment by sebastianpulido** [comment]
SSO is disable, let me know if should be enable.

**Comment by vlimant** [comment]
now pointing to those.
