### ISSUE TITLE
Assigning ACDC to sites not containing input data

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#185]
https://cmst2.web.cern.ch/cmst2/unified/report/pdmvserv_TOP-RunIISummer15wmLHEGS-00109_00183_v0__161005_164950_5013

E.g. for the production task we have several blue sites, not containing any input data and not available.
I would like to assign the ACDC (prozober_ACDC_TOP-RunIISummer15wmLHEGS-00109_00183_v0__161026_133634_9704 in this case), and not getting a message like this:
[u'T1_DE_KIT', u'T2_FI_HIP', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_IN_TIFR', u'T2_MY_UPM_BIRUNI', u'T2_PK_NCP', u'T2_PL_Warsaw', u'T2_RU_INR', u'T2_RU_ITEP', u'T2_RU_PNPI', u'T2_RU_SINP', u'T2_TH_CUNSTDA', u'T2_TR_METU', u'T2_TW_NCHC', u'T2_UK_London_Brunel', u'T2_US_UCSD'] is/are not ready

Can we cross-check this info @vlimant ?
Thanks.

**Comment by vlimant** [comment]
the site checking mechanism is much too restrictive in the version I had put yesterday. pull in the master.
More work is needed to get the site checking to be optimum
