### ISSUE TITLE
Use the Quota instead of Free for tape setting

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#188]
@mcreomone as discussed with @sidnarayanan over chat, we should have TT have an way to ban MM endpoint, or throttle.
http://cmsmonitoring.web.cern.ch/cmsmonitoring/StorageOverview/latest/StorageOverview.json
we use the "Free" entry, once there is a "Usable" (or whatever else) we should switch to it.

**Comment by vlimant** [comment]
Sebastian gave us a new json with "Usable" and we switched to that to let TT drive the tape distribution.

**Comment by sidnarayanan** [comment]
To be totally clear - the TT does not closely monitor tape distribution. We will only use this functionality to blacklist sites temporarily if there is an issue. Besides that, the distribution will be as before, unless some decision is made to disfavor certain sites despite free space.

Also, it was Jorge who added the Usable field :)

**Comment by vlimant** [comment]
thx for the clarification.
