### ISSUE TITLE
Problem with ACDC for RqMgr2 requets

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#190]
We have a problem with the makeACDC.py script, it is not able to create ACDCs for RqMgr2 requests. Some samples in assistance-manual [1].
This is the message we are getting [2].
[1]
pdmvserv_task_EXO-RunIIFall15DR76-04754__v1_T_161026_171602_8745
pdmvserv_task_EXO-RunIIFall15DR76-04734__v1_T_161025_051736_8033
pdmvserv_task_EXO-RunIIFall15DR76-04744__v1_T_161025_184330_1458
pdmvserv_task_EXO-RunIIFall15DR76-04747__v1_T_161026_121640_2035

[2]
</head>
    <body>
        <h2>400 Bad Request</h2>
        <p>Create request failed, (404, 'Given request name not found: pdmvserv_task_EXO-RunIIFall15DR76-04754__v1_T_161026_171602_8745')</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy unknown</a>
      </span>
    </div>
    </body>
</html>

**Comment by vlimant** [comment]
if you setup export UNIFIED_SUBMIT=reqmgr2 then it functions. It looks like reqmgr2 request ACDC can only be made in reqmgr2. @ticoann can you please confirm ?

**Comment by vlimant** [comment]
for the record 
vlimant_ACDC0_task_EXO-RunIIFall15DR76-04754__v1_T_161101_053335_2620 for /pdmvserv_task_EXO-RunIIFall15DR76-04754__v1_T_161026_171602_8745/EXO-RunIIFall15DR76-04754_0/EXO-RunIIFall15DR76-04754_1/EXO-RunIIFall15DR76-04754_1MergeAODSIMoutput/EXO-RunIIFall15MiniAODv2-04622_0
vlimant_ACDC0_task_EXO-RunIIFall15DR76-04754__v1_T_161101_053331_1524 for /pdmvserv_task_EXO-RunIIFall15DR76-04754__v1_T_161026_171602_8745/EXO-RunIIFall15DR76-04754_0/EXO-RunIIFall15DR76-04754_1

**Comment by vlimant** [comment]
default to submitting to reqmgr2 was added in the master.
