### ISSUE TITLE
recoverMissingLumis does not longer work with /reqmgr/reqMgr API

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#193]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/recoverMissingLumis.py#L387
The API https://cmsweb.cern.ch/reqmgr/reqMgr, does not longer work to get the request's info.
Alan suggests to use something like https://github.com/amaltaro/ProductionTools/blob/master/drainAgent.py#L85

**Comment by vlimant** [comment]
thanks for the fix
