### ISSUE TITLE
swtich recoveror to the actual ACDC documents

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#196]
It is using the workflow summary which is incomplete and will probably disappear. 
Maybe this is bound to disappear with the new interface, or maybe not.
FYI @areinsvo

**Comment by areinsvo** [comment]
Summarizing what I've discovered so far (apologies that this has taken so long).

What we need from the workflow summary is a list with the following information:
Error code, Number of jobs failing with that code, Error name, Error type, Details

I can get most of this from the getWMErrors() function in workflowInfo, except the "Number of jobs failing with that code" parameter doesn't really exist in getWMErrors() or anywhere else that I found. 

Also, the error codes aren't consistent between the old workflow summary and the getWMErrors output. For instance, for /pdmvserv_B2G-RunIISummer16MiniAODv2-00972_00211_v0__161222_122645_3950/, exit code 99303 is mentioned in getWMErrors(), but not 71305.  The other workflow I checked, /pdmvserv_SUS-RunIISummer16MiniAODv2-00158_00152_v0__161211_044046_8155/, included a 137 error code in getWMErrors() that wasn't mentioned in the workflow summary. Tips on where I should go from here to get this working?

**Comment by vlimant** [comment]
There is a big lag between the two source of information, so I don't expect them to be in sync.
Maybe combine with getWMStats() and in showError.py

**Comment by areinsvo** [comment]
For /pdmvserv_B2G-RunIISummer16MiniAODv2-00972_00211_v0__161222_122645_3950 the output of showError.py is the same as what I can get from WMError. That is, exit code 71305 still isn't mentioned.

For pdmvserv_task_EXO-RunIISummer16DR80Premix-02113__v1_T_161125_202214_5115, the first task has 6 error codes, but showError only shows 2 of them. The two it shows doesn't even correspond to the two with the highest error rates (if you define highest as what the workflow summary has as the most frequent error).

I can use getWMStats() and getWMError() in place of the workflow summary, but I worry that it isn't giving us the same results. Should I go ahead anyway?

**Comment by vlimant** [comment]
Yes

**Comment by areinsvo** [comment]
The code is done (but not fully tested) and can be found at /afs/cern.ch/user/c/cmst2/Unified/WmAgentScripts/Unified/recoveror_WMError.py. What is the best way to test this? Is it safe to run it with the --test option? Although I was careful, I would be very surprised if there weren't any typos. The code is by no means elegant, but it took much longer than it should have for me to figure out the right python commands, and it at least does what I want it to now.

Here is how I'm doing it, using the structure of WMError below: I use errorCount for the number of jobs with that error. If a given exitCode/type/errorname combo appears again in a different sitename or under a different errorcode, then the errorCount for that one is added to the first entry. Does that make sense? I'm not sure why there are two parameters that give an exit code, but I've chosen to use the second one to decide what recovery action should be taken. 

The "details" entry can either be a single string or a list, depending on if the detail message differs for the different instances of the same exitCode/type/errorname combination.

WM Error has the format 
{taskname:
 {'jobfailed' : 
  {errorcode : 
   {sitename : 
    {'errorCount': # 
     'samples' : [
      {'errors' : 
       {errorname: [
        'type' : errortype,
        'details' : detailmessage,
        'exitCode' : exitcode#}....

For example, 
 u'/pdmvserv_SUS-RunIISummer16MiniAODv2-00158_00152_v0__161211_044046_8155/StepOneProc/StepOneProcMergeMINIAODSIMoutput': {
    u'jobfailed': {
      u'137': {
        u'T2_US_Nebraska': {
          u'errorCount': 42,
          u'samples': [
            {
              u'errors': {
                u'stageOut1': [
                  {
                    u'type': u'ReportManipulatingError',
                    u'details': u'Could not find report file for step stageOut1!',
                    u'exitCode': 99999
                  }
                ],
                u'cmsRun1': [
                  {
                    u'type': u'CMSSWStepFailure',
                    u'details': u"\n Adding last 25 lines of CMSSW stdout:"
                    u'exitCode': 137
                  },
                  {
                    u'type': u'BadFWJRXML',
                    u'details': u'Error reading XML job report file, possibly corrupt XML File:\nDetails: no element found: line 1491, column 0',
                    u'exitCode': 50115
                  },
                ],
...

**Comment by areinsvo** [comment]
Tried to run it with --test, but there aren't any workflows in need of recovery, so my new code isn't touched. Since the normal recoveror module that runs twice an hour moves workflows out of "recovery" to "assistance", it might be hard to find a time when there is a workflow sitting in recovery for me to test the new code on.

**Comment by vlimant** [comment]
maybe you can hack it to look at workflows in -manual

**Comment by areinsvo** [comment]
Sorry for the delay. I've finished testing it on workflows in assistance-manual and I've gotten rid of all of the bugs and typos. It seems to be working. 

Possibly dumb question: What do we want to happen if there are unreported errors? I replicated the logic in showError.py to check if there are unreported errors, but I don't know what to do about it if that's the case.

**Comment by vlimant** [comment]
unreported errors (robust merges most of the time) are indeed tricky and indeed only using the accdc doc (as in showError) would work.

**Comment by areinsvo** [comment]
But the ACDC doc doesn't have error codes or error messages. I can use the ACDC doc to check if there are unreported errors, but I don't think I can use it to add in the missing error codes or messages.

**Comment by vlimant** [comment]
recoveror was decommissioned.
