### ISSUE TITLE
Is deprecated/resubmit_ACDC_Montecarlo.py  still used

### ISSUE THREAD

**Issue by ticoann** [CMSCompOps/WmAgentScripts#199]
It seems there is reqmgr1 dependency.
from WMCore.Services.RequestManager.RequestManager import RequestManager

Let me know if this is still used, I can provide replacement api.

**Comment by vlimant** [comment]
resubmit_ACDC_Montecarlo.py and the deprecated dir should be just removed all together, so don't worry about breaking that dependency, as long as it is nowhere else.

**Comment by ticoann** [comment]
Thanks Jean-Roch, I didn't see anywhere else in WmAgentScript

**Comment by vlimant** [comment]
gone 8d8ac5fe2a81994f5f8bbbd0ed9d5ce41f49b5a4
