### ISSUE TITLE
Create the error report for running problematic worklows

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#200]
We need a couple of technical details to actually move forward than just complaining.
@jenimal : what is the exact condition a workflows needs to pass to be problematic and needing a report ? (in terms of "I click there, I go there, I sort here, ... )
@ticoann : once we know that, we'll need to know how to get that from wmstats api. Maybe you actually want to implement this kind of report https://cmst2.web.cern.ch/cmst2/unified/report/fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch0-09Nov2016_8023_161109_182037_4148 directly in wmstats (it uses the acdc doc and wmstats api info) 

FYI @areinsvo, maybe a bit related to #196

**Comment by jenimal** [comment]
OK Where I look for problematic workflows:
Go to WMStats:
https://cmsweb.cern.ch/wmstats/index.html
Click on All Requests
Click on Progress
Sort by Failure Rate
Generally I will look at the workflows with the highest failure rate, anything over 50% definitely has problems and should be looked at.  By clicking on the "L" to see what steps are failing and what the error messages are.  


It is useful to look at things that have been running for a while over 20% will not make statistics and should be looked at but likely will not have anything we can fix on the fly.  Unless it is just one site that is sucking down work with a black hole.

Debugging with WMStats is fairly easy this way but it doesn't allow us to get to the logs easily.  If we can get to the logs easily with Unified having the error logs for anything over 10% would be good to give us room.  Perhaps we could start with 25% and which unless we have very badly behaving workflows or sites should be "good enough" if it is expensive to make the pages.  this should limit the number you need to make.  but it should be a tunable parameter so if at some point we decide we want to either increase or decrease that level we can do so easily. 

Although if it's merge issues this threshold will likely be too high, but generally we have been able to get the info to the sites on merge issues that they need.

**Comment by ticoann** [comment]
Hi Jean-Roch, Jen. I created the issue related to this. (https://github.com/dmwm/WMCore/issues/7517)
About the log access here is the discussion and Alan's (@amaltaro) suggestion
https://github.com/dmwm/WMCore/issues/7224

**Comment by vlimant** [comment]
https://vocms049.cern.ch/unified/toperror.html to be refined
