### ISSUE TITLE
makeACDC.py --memory does not set things properly for TaskChain

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#201]
@areinsvo @prozober worth taking a look at

vlimant_ACDC1_task_PPD-PhaseIIFall16GS82-00006__v1_T_170109_124909_9238 was created with --memory 7900 and it does not get set in the various tasks, so I am not sure that'll work

@amaltaro FYI, if you want to chip in

**Comment by amaltaro** [comment]
I see only two processing tasks and both have memoryRequirements set to 7900. Unless I overlooked something, it looks good.

**Comment by vlimant** [comment]
using actors anyways
