### ISSUE TITLE
Modifying memory for TaskChain clones

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#203]
Related to https://its.cern.ch/jira/browse/CMSCOMPPR-429, we need to modify resubmit.py in order to able of changing the memory parameter for TaskChain clones. 
We need to decide if we are going to:
- Delete the "Memory" value in the dictionary of every Task, and keep the modified Memory value in the main dictionary.
- Or we can modify the "Memory" value in the dictionary of every Task.

**Comment by vlimant** [comment]
I think this is OK now through actor.py
