### ISSUE TITLE
Get rid of CouchURL

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#216]
for https://github.com/dmwm/WMCore/pull/7734

CouchURL appears in several places. Does not look too complicated to remove any usage

**Comment by vlimant** [comment]
@amaltaro this was not done on ops end, but nothing break. Should it ?

**Comment by amaltaro** [comment]
Nope, we call it an internal ReqMgr parameter (because it's automatically set) but it won't hurt if the user *correctly* provides it. https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1051

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/2641f3150385b60a108c057e85baa3cc8cd54e50
