### ISSUE TITLE
analyzeDuplicates does not work

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#218]
The duplicateEvents' output does not longer fit with the analyzeDuplicates requirements.
analyzeDuplicates' documentation says:
```
FILE: A text file with the output of lumis from the duplicateEvents.py
    script
    Should be in this format:
      dataset : /DATASET_NAME
      runs
      lumi x is in these files
      file 1
      file 2
      lumi y is in these files
      file 3
      file 4
```

Either we change the output format of duplicateEvents, or we modify the way analyzeDuplicates is reading the data.

**Comment by vlimant** [comment]
I think I fixed the output of duplicateEvents.py with https://github.com/CMSCompOps/WmAgentScripts/commit/1b793018f951272340edcaab9571bb725f6d0759
and now analyzeDuplicates.py should work again.
we can think of refacoring the code now that it's in unified (https://github.com/CMSCompOps/WmAgentScripts/commit/4b15cd3dc0585c5f2b02c49ead3a7f52d9877be9). 
@areinsvo ?

**Comment by areinsvo** [comment]
@vlimant I don't know if you tagged me as an FYI or not, but let me know if there is something specific that I need to change or work on from the Unified side of things.
