### ISSUE TITLE
Handle better statuses within a relval batches

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#220]
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_8_0_27__ALCARELVAL-2017_04_13_17_13

unified is made that things are maybe too static.
with a search by campaign (does that exists already @ticoann @amaltaro ?) one should be able to go through and decide better on when a batch/campaign can be considered done.

**Comment by amaltaro** [comment]
https://cmsweb.cern.ch/reqmgr2/data/request?campaign=HIRun2015&status=announced&detail=false

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/16bf2d3ae3a576ae4a380fc56547a99f122dc815 should do it
FYI @areinsvo @mcremone @thongonary
