### ISSUE TITLE
makeACDC missing/unsupported parameters

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#222]
After the reqmgr2 upgrade, we are facing this exception when we try to create ACDC using "makeACDC.py", e.g.:

`>> python makeACDC.py --all -w pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727 `

```
 <h2>400 Bad Request</h2>
        <p>Invalid spec parameter value: WMSpecFactoryException
Message: There are unknown/unsupported arguments in your request spec: [u'BlockWhitelist', u'BlockBlacklist']
	ModuleName : WMCore.WMSpec.WMWorkloadTools
	MethodName : validateUnknownArgs
	ClassInstance : None
	FileName : /data/srv/beHG1705g/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.3.pre5-comp/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkloadTools.py
	ClassName : None
	LineNumber : 306
	ErrorNr : 0

Traceback
```

@vlimant, could you please take a look?

**Comment by vlimant** [comment]
hey, indeed

vlimant@vocms049.cern.ch >./makeACDC.py --all -w pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727 
Workflow: pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727
Tasks: [u'/pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727/HIG-PhaseISpring17wmLHEGS-00007_0/HIG-PhaseISpring17wmLHEGS-00007_0MergeLHEoutput', u'/pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727/HIG-PhaseISpring17wmLHEGS-00007_0/HIG-PhaseISpring17wmLHEGS-00007_0MergeRAWSIMoutput', u'/pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727/HIG-PhaseISpring17wmLHEGS-00007_0/HIG-PhaseISpring17wmLHEGS-00007_0MergeRAWSIMoutput/HIG-PhaseISpring17DR-00002_0', u'/pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727/HIG-PhaseISpring17wmLHEGS-00007_0/HIG-PhaseISpring17wmLHEGS-00007_0MergeRAWSIMoutput/HIG-PhaseISpring17DR-00002_0/HIG-PhaseISpring17DR-00002_0MergeRAWSIMoutput/HIG-PhaseISpring17DR-00002_1', u'/pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727/HIG-PhaseISpring17wmLHEGS-00007_0/HIG-PhaseISpring17wmLHEGS-00007_0MergeRAWSIMoutput/HIG-PhaseISpring17DR-00002_0/HIG-PhaseISpring17DR-00002_0MergeRAWSIMoutput/HIG-PhaseISpring17DR-00002_1/HIG-PhaseISpring17DR-00002_1MergeAODSIMoutput']
ACDC payload
{
  "InitialTaskPath": "/pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727/HIG-PhaseISpring17wmLHEGS-00007_0/HIG-PhaseISpring17wmLHEGS-00007_0MergeLHEoutput", 
  "OriginalRequestName": "pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727", 
  "ACDCServer": "https://cmsweb.cern.ch/couchdb", 
  "Campaign": "PhaseISpring17wmLHEGS", 
  "TimePerEvent": 51, 
  "RequestType": "Resubmission", 
  "OpenRunningTimeout": 0, 
  "ACDCDatabase": "acdcserver", 
  "RequestString": "ACDC0_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T", 
  "Requestor": "vlimant", 
  "SizePerEvent": 3000, 
  "Memory": 5900, 
  "Group": "ppd", 
  "RequestPriority": 900000, 
  "PrepID": "task_HIG-PhaseISpring17wmLHEGS-00007", 
  "CMSSWVersion": "CMSSW_9_0_2"
}
[]
Error in making the request
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>400 Bad Request</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>400 Bad Request</h2>
        <p>Invalid spec parameter value: WMSpecFactoryException
Message: There are unknown/unsupported arguments in your request spec: [u'BlockWhitelist', u'BlockBlacklist']
	ModuleName : WMCore.WMSpec.WMWorkloadTools
	MethodName : validateUnknownArgs
	ClassInstance : None
	FileName : /data/srv/beHG1705g/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.3.pre5-comp/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkloadTools.py
	ClassName : None
	LineNumber : 306
	ErrorNr : 0

Traceback: 

</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy unknown</a>
      </span>
    </div>
    </body>
</html>

Error in making ACDC for pdmvserv_task_HIG-PhaseISpring17wmLHEGS-00007__v1_T_170428_162726_9727

**Comment by vlimant** [comment]
neither BlockWhitelist nor  BlockBlacklist are passed in the schema, @amaltaro is the one who can do something for this I think

**Comment by amaltaro** [comment]
jeez

**Comment by amaltaro** [comment]
Sorry, I should have foreseen this case. Issue created here:
https://github.com/dmwm/WMCore/issues/7835

I don't think we can create ACDCs before we update the code... no way around it

**Comment by prozober** [comment]
I did a couple of tests and everything is working now. Thank you, Alan.

**Comment by amaltaro** [comment]
awesome! Thanks!
