### ISSUE TITLE
Does CompOps use reqmgr2.py client?

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#224]
Not an issue, but a question. Is CompOps relying on this reqmgr2 client
https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/reqmgr2.py
?

I'd like to make some changes to it, eventually. And I just want to make sure it's not going to break anything on your side.

**Comment by amaltaro** [comment]
ping

**Comment by vlimant** [comment]
not aware of any interaction with this that I remember. Is a grep on the repo giving anything ?

**Comment by amaltaro** [comment]
Nope, I can't find reqmgr2.py being used in this repo. Thanks!
