### ISSUE TITLE
Check unmerged file presence using xrd

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#227]
In the Unified report it would be useful to have an automatic check whether the unmerged file exists so that we can ACDC.

**Comment by vlimant** [comment]
@yiiyama I think you send me a command to check the existence of a file "anywhere". 
could you please copy it here.

**Comment by yiiyama** [comment]
Would `xrdfs root://cms-xrd-global.cern.ch ls /store/unmerged/...` work?

**Comment by vlimant** [comment]
does this hang forever when the file is actually not available anywhere anymore ?

**Comment by yiiyama** [comment]
Indeed `ls` seems to hang.. On the other hand `xrdfs root://cms-xrd-global.cern.ch stat /store/unmerged/...` came back in finite time with a message `[ERROR] Server responded with an error: [3011] No servers are available to read the file.`

**Comment by prozober** [comment]
Hi, I am using something like

`result=os.system(''gfal-ls "'+PFN)  `

on lxplus to check if files are in place.
if result ==0 the file is gone, a try-except must be included.

**Comment by vlimant** [comment]
gfal-ls is not available on the nodes, once its installed I'll add it and check on performance.

**Comment by vlimant** [comment]
@prozober that works only for eos, or anysite, anywhere ?

**Comment by vlimant** [comment]
xrdfs added
