### ISSUE TITLE
Get rid of the 4H assignment-approved grace period

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#228]
as per https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/19032.html assignment-approved means "go for it", therefore we should get rid of the legacy 4h grace period.

**Comment by vlimant** [comment]
FYI @drkovalskyi @mcremone @thongonary

**Comment by drkovalskyi** [comment]
It that's what they want I see no issue with that.

**Comment by vlimant** [comment]
ebab9f1893fab11e2073aa4ac87b91b8ebdd416b will do
