### ISSUE TITLE
Migrate to dynamo registry

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#229]
from @yiiyama
We have a new dataset-locking mechanism for Dynamo. This is something we have been advertising for a long time and is finally online.

In the new scheme, you will write to our database the list of items you want to lock, instead of Dynamo reading files you produce.

In short, we'd like to ask you to create a JSON file in the format

[{"item": "dataset_or_block_name", "sites": "site_name", "groups": "group_name", "expires": expiry_date, "comment": "comment_string"}, {"item": ...}, ...]

and upload it to dynamo.mit.edu using your x509 proxies:

curl -k --cert <proxy> --key <proxy> --data @json_file.json 'https://dynamo.mit.edu/registry/detoxlock/set?service=<service>' (or equivalent in whatever https client you use)

The server should return a JSON with "OK" if the command is successful.

In the JSON above, "sites", "groups", and "comment" are optional fields. If you don't specify sites or groups, the lock will protect all matching items universally. Expiry date is an arbitrary time (in either unix time or a string like '2017-05-17') in the future. It's just for our guide; nothing is programmatically enforced, but we'll be checking locks regularly and notify people who have locks that are older than their declared expiration time.

In the cURL command above, "service" is a tag that identifies the program you are registering the locks for, and corresponds to the different JSON files you are producing now. I've made up service names for the existing JSON files already:

https://vocms049.cern.ch/unified/public/globallocks.json   --> service=unified
https://cmst2.web.cern.ch/cmst2/unified-testbed/globallocks.json   --> service=unified-testbed
https://cmst1.web.cern.ch/CMST1/lockedData/lockTestSamples.json   --> service=wmcore
https://cmsweb.cern.ch/t0wmadatasvc/prod/dataset_locked   -> service=t0-prod
https://cmsweb.cern.ch/t0wmadatasvc/replayone/dataset_locked   --> service=t0-replayone
https://cmsweb.cern.ch/t0wmadatasvc/replaytwo/dataset_locked   --> service=t0-replaytwo

Let me know if the names are not appropriate. Also, I'm actually not sure if the "wmcore" JSON is produced by either one of you - if not, do you happen to know who?

Locks are identified by [item, sites, groups, user, service]. User is determined from the DN in the certificate (which must be the one in SiteDB). If multiple [user, service]s lock the same item, the item is protected until the last lock is removed.

The above cURL command is an example of the "set" command, where you create the locks in one go. All existing locks in our system that are not mentioned in the uploaded JSON file will be removed. There are also "lock" and "unlock" commands where you can deal with individual locks (see the documentation below for that).

With Jean-Roch, we currently also have a mechanism of "locking the locks" to avoid race conditions between Unified and Dynamo. This is also going to be replaced with a similar interface. The new method is

curl -k --cert <proxy> --key <proxy> 'https://dynamo.mit.edu/registry/activitylock/lock?service=<service>&app=detox'     --> to lock
and
curl -k --cert <proxy> --key <proxy> 'https://dynamo.mit.edu/registry/activitylock/unlock?service=<service>&app=detox'      --> to unlock

The server returns an "OK" JSON if the lock/unlock succeeds. If e.g. Dynamo is already running when you issue the lock command, the message is "Failed: application already locked".

Full documentation of the interfaces are here:
https://dynamo.mit.edu/registry/detoxlock/help
https://dynamo.mit.edu/registry/activitylock/help

There is a test instance of the registry interface running on t3desk007.mit.edu. You can test all commands using this machine instead of dynamo.mit.edu. In fact, we need to be careful when writing to dynamo.mit.edu since the locks from the files above are already being converted and registered to the DB, and Dynamo is currently reading the locks from this DB.

**Comment by vlimant** [comment]
vlimant@vocms049.cern.ch >curl -k --cert $X509_USER_PROXY --key $X509_USER_PROXY 'https://t3desk007.mit.edu//registry/activitylock/lock?service=unified&app=detox'
curl: (35) error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca

 if you could adapt


def lock_DDM(lock=True):
    conn  =  httplib.HTTPSConnection('t3desk007.mit.edu', cert_file = os.getenv('X509_USER_PROXY'), key_file = os.getenv('X509_USER_PROXY'))
    if lock:
        conn.request("POST","/registry/activitylock/lock?service=unified&app=detox")
    else:
        conn.request("POST","/registry/activitylock/unlock?service=unified&app=detox")
    response = conn.getresponse()
    data = response.read()
    res = json.loads( data )
    print res

to make it work, that'd be very helpful.

**Comment by yiiyama** [comment]
Actually, I forgot to ask for a crucial information - @vlimant which certificate are you using?

**Comment by vlimant** [comment]
we are using personal certificate, mine and @mcremone for now

**Comment by yiiyama** [comment]
I think I understand what is going on now - we have OSG-signed host certificates on our servers, and OSG CA is not in the list of default CAs in the system (/etc/pki/tls/cert.pem).

For an httplib connection object, if we add the OSG CA in /etc/grid-security directory like this:
```
context = ssl.create_default_context()
context.load_cert_chain('/tmp/x509up_u49321')
context.load_verify_locations('/etc/grid-security/certificates/cilogon-osg.pem')
conn = httplib.HTTPSConnection('t3desk007.mit.edu', context = context)
```
I could get the connection to work using the python build in the wmagent software suite from vocms049 (thanks to Dan).

This still doesn't explain why connecting from `curl -k` didn't work last time @vlimant tried though...

**Comment by vlimant** [comment]
hey @yiiyama , I think you need to have a certificate that complies with the default CAs, or have it added to the defaults.  @amaltaro how do we do that ?

**Comment by yiiyama** [comment]
Ideally yes, but there isn't really an issue with adding that load_verify_locations() line in the script, no?

**Comment by yiiyama** [comment]
Hi @vlimant, I found a way to enable the osg cert as default trusted:
https://www.happyassassin.net/2015/01/14/trusting-additional-cas-in-fedora-rhel-centos-dont-append-to-etcpkitlscertsca-bundle-crt-or-etcpkitlscert-pem/

As root:
```
ln -s /etc/grid-security/certificates/cilogon-osg.pem /etc/pki/ca-trust/source/anchors/cilogon-osg.pem
update-ca-trust
update-ca-trust enable
```

**Comment by vlimant** [comment]
I let @amaltaro decide on the kosher-ness of that change. I am not in favor.

**Comment by vlimant** [comment]
@yiiyama not sure where do we stand there. I have the feeling we change the way to do this.
