### ISSUE TITLE
Check on the output size and adapt the splitting

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#230]
From this issue [Special Error for SYSTEM_PERIODIC_REMOVE](https://github.com/dmwm/WMCore/issues/7906) 

Currently, when the job's output size exceeds the limit, it aborts prematurely, leaving logs with very limited information and exit code 99303. 

We need to have an automatic check on the job's output size and adapt the splitting accordingly. 

@vlimant

**Comment by vlimant** [comment]
a first step towards this https://github.com/CMSCompOps/WmAgentScripts/commit/fd3aaf437aadeaec09b857dd9ca359aadad9bdd3
with which some other splitting check were lost, but maybe not too relevant

**Comment by vlimant** [comment]
further minor modifications were necessary for the connection and when things can get applied.
it's all working now.
