### ISSUE TITLE
Are workflows asssigned with UnmergedLFNBase and MergedLFNBase

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#235]
The title says it all. Is unified **always** passing a key/value for these 2 arguments during assignment?

They currently have some default values that could be harmful (same default value as creation):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1092

and I'd like to remove those default values from assignment, such that we **only** update that during assignment if explicitly provided.
Thanks

**Comment by vlimant** [comment]
it's always set in assignment, for ops scripts via

https://github.com/CMSCompOps/WmAgentScripts/blob/master/reqMgrClient.py#L922
https://github.com/CMSCompOps/WmAgentScripts/blob/master/reqMgrClient.py#L952

you could make the default None and fail assignment if those are not passed.

**Comment by amaltaro** [comment]
Perfect, thanks!
