### ISSUE TITLE
Changing Memory and Multicore at assignment

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#238]
@amaltaro @ticoann can you please shed some technical light on how to practically change the Memory-Multicore parameters in a taskchain at assignment time. Is passing a single dict (like era) sufficient ?

note for self https://github.com/CMSCompOps/WmAgentScripts/blob/afd3eb8ee566ddc4d1d7c28035ddb27c45d0ad8d/reqMgrClient.py#L778 will nee to update to properly adapt MaxRSS

**Comment by amaltaro** [comment]
That's correct. Use it the same way it's used for AcquisitionEra, so a dict key'ed by the tasknames. Or just a single value if you want that setting for the whole workflow.

FYI., the MaxRSS ticket is in our radar for this month. I might change TimePerEvent as well and support override during assignment (such that it triggers the 8h jobs).

**Comment by areinsvo** [comment]
Hi @vlimant has this issue been fixed yet? Right now if we try to change the memory parameter for an ACDC created by actor, the updated value doesn't get passed all the way to the task dict, and the MaxRSS and Memory for the task remain unchanged.

FYI @mcremone and @thongonary

**Comment by vlimant** [comment]
@areinsvo this issue is unrelated to the issue of changing the memory parameter in making acdc.
What we want here is the ability of changing these parameters when assigning a new request, with changing the Multicore and Memory (i.e. changing a 4core into an 8core task).

**Comment by vlimant** [comment]
@amaltaro upon changing Multicore, is the splitting changed accordingly, or should TimePerEvent be also changed concurrently so as to have the proper splitting of 8h ?

**Comment by amaltaro** [comment]
Job splitting is only touched when the workflow is created, thus Multicore changes has no effect neither on TimePerEvent nor with the final job splitting settings.

**Comment by vlimant** [comment]
https://github.com/dmwm/WMCore/issues/7767

**Comment by areinsvo** [comment]
Hi @vlimant. Maybe I need to create another issue then. What I was referring to was the ability to change Memory and MaxRSS for an ACDC during assignment. Specifically, the way things were changed here, if I pass 'Memory' as a parameter during ACDC assignment, it changes things for the main dict but not in each task like we want.   https://github.com/CMSCompOps/WmAgentScripts/commit/afd3eb8ee566ddc4d1d7c28035ddb27c45d0ad8d#diff-3fc98fbeeaadf6df0cfbc50d59551ffe

**Comment by areinsvo** [comment]
Never mind; I see now that you pointed me to a fix for handling this properly on the actor side of things. Thanks.
