### ISSUE TITLE
Duplicate files reported in Unified

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#239]
We want to incorporate in Unified the logic we were using to report duplicated events.
https://github.com/CMSCompOps/WmAgentScripts/blob/master/dbs3Client.py#L24
The output of https://github.com/CMSCompOps/WmAgentScripts/blob/master/duplicateEvents.py was something like

_dataset: DATASET_NAME
Lumi HERE_NUM_DUPLICATED_LUMI is in these files
------FILE 1 ------
------FILE 2------
------FILE N------

**Comment by vlimant** [comment]
using existing code from analyzeDuplicates.py #218 unified will now provide the proper list of files to be invalidated in case of duplicates.
@yiiyama is there any hook for invalidating files alltogether ?
could unified flip the file status to invalid in dbs and one of the TT script get that file removed from TMDB ?

**Comment by yiiyama** [comment]
We have an interface to a Dynamo DB now, as reported in https://its.cern.ch/jira/browse/CMSCOMPPR-1488 .
http://dynamo.mit.edu/registry/invalidation/invalidate?item=<file name>
adds a file to the list of files to be globally invalidated from TMDB and the TT can take care of it from there on.

**Comment by vlimant** [comment]
are we going to have the same issue with the service certificate trying to reach that restapi ? How fast can we expect the files to be removed ?

**Comment by yiiyama** [comment]
Because we had the issue with certificate, this interface is made without SSL.
Initially we would want to drive it manually (e.g. system checks the DB every minute then sends an email to a TT member) just to avoid accidents, so the reaction won't be instantaneous.

**Comment by vlimant** [comment]
all in https://github.com/CMSCompOps/WmAgentScripts/commit/7e130d2b30d2a49463e6b20a0f1d07fc7e9f0a1c
we'll need to change to https when the api gets secured
