### ISSUE TITLE
Unified bypass policy for DQMIO-only missing lumisections

### ISSUE THREAD

**Issue by areinsvo** [CMSCompOps/WmAgentScripts#241]
Following the discussion from https://its.cern.ch/jira/browse/CMSCOMPPR-1456, we want to implement a new policy in Unified for ReReco workflows that are only missing DQMIO:

For SingleMuon SinglePhoton, ZeroBias, JetHT dataset it is OK to bypass if the lost lumisections per run are not less than what is allowed in Prompt Reco processing (I am not sure about the percentage, is it 2% ?)
For the other datasets always bypass without any threshold

This will be the policy for all future ReReco campaigns as well.
@vlimant can you help me implement this?

**Comment by vlimant** [comment]
Doing  "by primary dataset" will require some changes in checkor. Everything is doable.
The "per run" available statistics is already implemented (by expensive) and can be applied selectively.
What needs to be adjusted is the "fraction_pass" dictionary in checkor and how we pass/get the information from the campaignInfo.

I'll make another comment on JIRA for Francesco.

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/e96ebc61cb09f6ef4ea893ab08f2cbdee3230e7c
it's done. easier than I thought it would be
