### ISSUE TITLE
Update MaxRSS/MaxVSize units from KB to MB

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#248]
Since CMSWEB HG1710, we have these changes in production:
https://github.com/dmwm/WMCore/pull/8204

Thus, can we update the value set during assignment from KB to MB (e.g., if you were setting MaxRSS=2097152 for a 2GB RSS, you should now set MaxRSS=2048).

Another option is to completely remove MaxRSS/MaxVSize from assignment, but for that we need to make sure that there are no workflows older than 2 weeks sitting in new or assignment-approved.

**Comment by vlimant** [comment]
@amaltaro I'll wait for you go to get rid of 

https://github.com/CMSCompOps/WmAgentScripts/blob/727b3fda67f164485a70f68d8a28641cc9f20674/reqMgrClient.py#L781 ++
and
https://github.com/CMSCompOps/WmAgentScripts/blob/727b3fda67f164485a70f68d8a28641cc9f20674/reqMgrClient.py#L951
https://github.com/CMSCompOps/WmAgentScripts/blob/727b3fda67f164485a70f68d8a28641cc9f20674/reqMgrClient.py#L952

**Comment by amaltaro** [comment]
We still can't remove those because, besides a few requests in new state (which will probably never move forward nor get rejected), there are two workflows that were created before HG1710 upgrade:
pdmvserv_task_BTV-RunIISummer17DRStdmix-00010__v1_T_171003_170442_9186
pdmvserv_task_BTV-RunIISummer17DRStdmix-00009__v1_T_171003_170427_1289

**Comment by vlimant** [comment]
is this something we can move on with ?

**Comment by amaltaro** [comment]
We can go ahead with this change, there doesn't seem to be any old requests waiting to be assigned.
You can either update the unit or completely remove it, since it follows the Memory requirements setting.

**Comment by amaltaro** [comment]
Can someone please confirm whether unified and any other Ops scripts are now using MB instead of KB for MaxRSS and MaxVSize? If so, since when? We'd like to remove some backwards code and we're also considering completely removing these 2 metrics, simply use what was asked in the Memory parameter.

**Comment by vlimant** [comment]
hey man, I don't think the move was made yet, sorry about that. remind me next week

**Comment by amaltaro** [comment]
Since it looks like a simple change, I made those myself. Please have a look at #261 and merge it if it's Ok. (there are a few other places with maxrss code, under mc/ and relval/ in general)

**Comment by ticoann** [comment]
@vlimant,
Discussed with Alan - If MaxRSS is set to the same value as Memory always. We can get rid of setting MaxRSS explicitly (only Memory).  WMAgent cant set it as the same value automatically (It currently does if MaxRSS is not defined)

**Comment by vlimant** [comment]
should we get rid of setting MaxRSS all together right away in this PR then ?
if so @amaltaro please update or let me know

**Comment by amaltaro** [comment]
It seems we already update MaxRSS every time we update the memory requirements, so it _should_ be fine. 
Nonetheless, let me make sure this is the case before we completely remove it from Unified.

**Comment by amaltaro** [comment]
We decided to drop those two parameters completely (MaxRSS and MaxVSize). That means they will no longer be supported during assignment (or creation) after the next Tuesday, when cmsweb production deployment will happen.

**Comment by vlimant** [comment]
all dropped with https://github.com/CMSCompOps/WmAgentScripts/commit/5f453a860521c68c85a436141d44ae7959d62128
