### ISSUE TITLE
Summary for Unified

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#250]
It would be nice if we can have a summary section on Unified page, which include basic information to be reported on the CompOps meeting. For example:

>    * Workflows
>       * 28 wfs in staging in 14 campaigns
>       * 836 wfs on-going in 18 campaigns: RunIISummer15wmLHEGS (380), RunIISummer16DR80Premix (149)
> 
>    * Datasets
>       * 2276 datasets announced last week
>          * 337 (331) datasets waiting for tape approval for >7days: https://vocms049.cern.ch/unified/missing_approval_custodial.json
>          * 37 (38 last week) tape copies stuck preventing unlocking: https://vocms049.cern.ch/unified/public/stuck_custodial.json
>       * 7 (1 last a week) dataset appear stuck for placement: https://vocms049.cern.ch/unified/public/stuck_transfers.json 
> 
>    * Disk space
>       * 11 (11 last week) out-of-space sites (unified quota = 80% ddm dataops-quota): https://vocms049.cern.ch/unified/outofspace.html

These numbers are easier to grab by a python script than a human, and would save L3s quite a lot of time to focus on real issues on the report.

**Comment by vlimant** [comment]
https://vocms049.cern.ch/unified/summary_2018_06.json
with https://github.com/CMSCompOps/WmAgentScripts/commit/8c97e0f063e351827f59fa3c3015f05a4916ead2
enjoy !

**Comment by mcremone** [comment]
Can waiting for tape approval for >7days and stuck tape copies be added?

**Comment by mcremone** [comment]
Also, we would need a copy of the file in the public area ("https://vocms049.cern.ch/unified/public"), with a fixed name in .txt format ("summary.txt"), in sync with the original file. I have already modified the running version of htmlor.py and verified that this is the right way to go to automatically update the twiki for the Monday report:

https://twiki.cern.ch/twiki/bin/view/CMS/CompOpsMeetingProductionReprocessing

for the moment I put a placeholder for ape approval for >7days and stuck tape copies (I repeated the output produced number there), waiting for the information to appear in the json.
