### ISSUE TITLE
make the pass thresholds cumulative

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#251]
to be fully consistent between submitting a taskchain and each step separately, and as suggested to me recently the pass threshold could be with respect to the previous task, rather than to the full request.
Example 

pdmvserv_task_HIG-PhaseIITDRFall17wmLHEGS-00053__v1_T_171103_203755_5354 is not completed
{
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17DR-noPU_93X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-RECO": 0.4672489082969432,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17wmLHEGS-93X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM": 0.6244541484716157,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17wmLHEGS-93X_upgrade2023_realistic_v2_ext1-v1/LHE": 6.9553197638412945,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17MiniAOD-PU200_93X_upgrade2023_realistic_v2_ext1-v1/MINIAODSIM": 0.388646288209607,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17DR-PU200_93X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-RECO": 0.5851528384279476,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17MiniAOD-noPU_93X_upgrade2023_realistic_v2_ext1-v1/MINIAODSIM": 0.388646288209607
}
{
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17DR-noPU_93X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-RECO": 0.85,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17wmLHEGS-93X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM": 0.95,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17wmLHEGS-93X_upgrade2023_realistic_v2_ext1-v1/LHE": 0.95,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17MiniAOD-PU200_93X_upgrade2023_realistic_v2_ext1-v1/MINIAODSIM": 0.85,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17DR-PU200_93X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-RECO": 0.85,
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17MiniAOD-noPU_93X_upgrade2023_realistic_v2_ext1-v1/MINIAODSIM": 0.85
} 

 the gen-sim is at 62%
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17wmLHEGS-93X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM": 0.62
and the gen-sim-reco at 58%
"/ZJetsToNuNu_HT-1200To2500_14TeV-madgraph/PhaseIITDRFall17DR-PU200_93X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-RECO": 0.58

if we consider the gen-sim "done" (by virtue of unrecoverable failures) the gen-sim-reco can be considered done too, since 58% > (85% of 62%), while at the moment it is not considered done because not above 85%.

the proposal, rather trivial to implement in checkor is the adjust the effective threshold to the actual completion of the parent dataset.

@thongonary @mcremone @drkovalskyi I leave this open to you guys to decide

**Comment by thongonary** [comment]
I think it's pretty obviously the right thing to do, unless someone has the other reason, I'm 100% supporting this.

**Comment by thongonary** [comment]
I think it's pretty obviously the right thing to do, unless someone has the other reason, I'm 100% supporting this.
One question though, under which mechanism Unified can decide 62% completion of GENSIM is done due to unrecoverable failures? Or are you just referring to the situation when GENSIM is force-completed by Ops and then the subsequent dataset's threshold should be adjusted accordingly by Unified?

**Comment by vlimant** [comment]
62% complete for GEN-SIM is not going to be considered good, if the gen-sim threshold is still 95%.
but if we set the threshold of gen-sim to 50% (because of wmlhe issues), then that workflow above would get announced since the rest of the datasets are above the conditional completion fraction.

**Comment by drkovalskyi** [comment]
While it's logical that completion of following steps should be considered with respect to previous steps, a decision to move on with 58% of GenSim can only be triggered by a human. As is I don't see much value in implementing cumulative thresholds, since if campaign is dominated by GenSim+DigiReco requests cumulative threshold is equivalent to a simple change of the overall threshold from 95% to 90% (95%^2)

**Comment by vlimant** [comment]
there is one adversarial effect at the moment that having cumulative threshold will solve naturally is if the DR campaign is set to 90% and the miniaod is set to 95%, samples won't pass if send in chains, while it would if submitted separately. 
deciding to have gensim pass at 10% could be made automatic if we want to get rid of the large amount of crap with madgraph remaining in old campaigns.
if you don't have strong objection @drkovalskyi , I'd like to go on with the proposal, and let @areinsvo update the pass threshold accordingly if necessary.

**Comment by vlimant** [comment]
The code is ready for this. With an example like

For /DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17wmLHEGS-93X_mc2017_realistic_v3-v2/LHE passing at 0.95 is now passing at 0.95
For /DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17DRPremix-94X_mc2017_realistic_v10-v2/AODSIM passing at 0.95 is now passing at 0.9025
For /DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17wmLHEGS-93X_mc2017_realistic_v3-v2/GEN-SIM passing at 0.95 is now passing at 0.95
For /DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAOD-94X_mc2017_realistic_v10-v2/MINIAODSIM passing at 0.95 is now passing at 0.857375

it is still inactive,

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/1dde57d2445bf0e5ff67bbbfec79c31ca147a95d makes it configurable with cumulative_fraction_pass
