### ISSUE TITLE
Replace max_events_per_lumi by job_time_limit

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#256]
Starting today - with the CMSWEB production upgrade - any new requests (not ACDCs of old requests) will have a new job splitting parameter called `job_time_limit` (if it is using EventAwareLumiBased), which replaces the `max_events_per_lumi`.

Instead of failing jobs based on the amount of events within a single lumi file (20k events was the default), EventAwareLumiBased will start using the estimated job time (events in the lumi file * TimePerEvent). The default value is 172800 secs (2 days).

Please update any scripts interacting with the job splitting.
Further details in https://github.com/dmwm/WMCore/pull/8398 and https://github.com/dmwm/WMCore/pull/8426

**Comment by amaltaro** [comment]
FYI @ticoann

**Comment by prozober** [comment]
@vlimant @areinsvo, do we need to change something in the [actor](https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/actor.py)'s side?

**Comment by vlimant** [comment]
There was no hook to change max_events_per_lumi, so nothing to be adapted.
Only when creating an ACDC will it change something. It does not look like actor.py is modifying this anyways.

**Comment by amaltaro** [comment]
Ok, thanks!
