### ISSUE TITLE
migrate how to hand over output dataset to anaops

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#257]
@yiiyama I think we discuss that we should replace the legacy script assignDatasetToSite.py for a call to a registry of some kind.
Please use this to provide the relevant information to have this happen.

**Comment by vlimant** [comment]
looks like we are close to a new api @yiiyama, right ?

**Comment by vlimant** [comment]
it would right about a good time because https://github.com/CMSCompOps/WmAgentScripts/blob/master/assignDatasetToSite.py (copied from detox) is failing for mysterious reasons

**Comment by vlimant** [comment]
http://t3serv001.mit.edu/~cmsprod/IntelROCCS/Detox/result/T2_CH_CERN/Summary.txt is not there anymore, even though the script is looking for it

**Comment by yiiyama** [comment]
Indeed we have just commissioned a new request API with CRAB folks, so we should roll it out with Unified.
But for the time being we should also fix this failing script, and the reason for failure is that I moved the Summary.txt file away yesterday in an attempt to clean up items from old days. I was not aware that the script is looking for this file. Sorry. I moved it back now.

**Comment by yiiyama** [comment]
OK we have the request API ready for use.
Documentation is here: http://dynamo.mit.edu/registry/request/help
Basic usage is to specify the item and sites as
`https://dynamo.mit.edu/registry/request/copy?item=/A/B/C&site=T2_*,T1_*_Disk&n=2`
in this case, two (n=2) copies of dataset /A/B/C is requested in the pool of T2_* and T1_*_Disk.
The same request can be made by posting a JSON to `https://dynamo.mit.edu/registry/request/copy`:
`{"item": ["/A/B/C"], "site": ["T2_*", "T1_*_Disk"], "n": 2]}`
Multiple items can be placed in a single request. If e.g. `"item": ["/A/B/C", "/D/E/F"]` in the above request, two copies of each of /A/B/C and /D/E/F will be created somewhere in T2 and T1 disk (destinations will be independently chosen for the two datasets).
For each call to the `copy` interface, (if successful) a JSON with the request ID is returned. You can poll the status of the request by this ID:
`https://dynamo.mit.edu/registry/request/pollcopy?request_id=10`
This returns a JSON with the status of copy at `json['data'][0]['status']`.

**Comment by vlimant** [comment]
@yiiyama the hand over is done with no site specification, with ddm deciding where it should be send.
so we need an api where if the site is not specified, dynamo decides where it should go.
does the api work with blocks, list of blocks, mixed list of block and dataset ?

**Comment by yiiyama** [comment]
@vlimant `"site": ["T2_*", "T1_*_Disk"]` above was to be taken literally - that is the site specification saying "somewhere on T2 or a T1 disk". Dynamo will then decide the destination from the list of candidate sites it has.
And yes, it works with any combination of blocks and datasets in one request.

**Comment by vlimant** [comment]
can I put site = "*" and not have to worry about it anymore ?

**Comment by yiiyama** [comment]
yes that works too - I guess we won't include tape nodes and T3 in our target site list.

**Comment by vlimant** [comment]
I am getting user not authorized

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/b278b1010ad022ed4118a24209db3b25f23eda01

switched over. we'll see how this goes.
