### ISSUE TITLE
Migrate locking on dynamo's cycle

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#262]
a poor man's lock file over the web is used. @yiiyama suggested 

"""
he documentation is here:
http://dynamo.mit.edu/registry/applock/help
but the usage is simple:
http://dynamo.mit.edu/registry/applock/lock?app=detox&service=unified
will return a JSON that either says {"result": "OK"} or {"result": "WAIT"}. If the result is OK, the deletion cycle is not running on our side, so you are good to go. If the result is WAIT, then a deletion cycle is running, but your lock has been put in place as next in queue. You can keep polling at the same URL until you get result OK, at which point our applications are blocked. Once you are done, you can call
http://dynamo.mit.edu/registry/applock/unlock?app=detox&service=unified
to release the lock.
"""

**Comment by vlimant** [comment]
@yiiyama does this work with counting the calls ? i.e two calls to http://dynamo.mit.edu/registry/applock/lock?app=detox&service=unified and one call to http://dynamo.mit.edu/registry/applock/unlock?app=detox&service=unified will leave dynamo locked by unified ?
if not it has to be done this way before we move to this.

**Comment by yiiyama** [comment]
@vlimant At the moment no, multiple lock calls will not increase the counter. I will make the change and let you know.

**Comment by vlimant** [comment]
thanks @yiiyama , please update me here, or reference this issue

**Comment by yiiyama** [comment]
@vlimant the applock now has lock count information, so it will be unlocked only by calling "unlock" as many times as "lock" was called. There is no change to the interface. Please let me know if it works for you.
