### ISSUE TITLE
actor is not rejecting ACDC properly

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#265]
I was looking at https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2-0008 and https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/actor.py#L431 it does not look like actor is rejecting the existing ACDC properly.
can you please clarify @areinsvo ?

**Comment by prozober** [comment]
`Looking at prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199 for recovery options
Going to clone  prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199
Let's try kill and clone: 
Going to clone prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199
invalidating the workflow by traffic controller 
setting dataset status INVALID to inexistant dataset /NoBPTX/Run2016H-05Feb2018_ver2-v1/NANOAOD considered succeeding
prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199 and children are rejected
Clone payload
{u'cores': u'', u'splitting': u'2x', u'memory': u''}
Failed to create clone for prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199! Check logs for more information. Action will need to be resubmitted.
Failed to create clone for prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199!
Done
Failed to create clone for prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199!
Failed to create clone for prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199!
finished`

**Comment by prozober** [comment]
Looking at prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199 for recovery options
Going to clone  prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199
Let's try kill and clone: 
Going to clone prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199
invalidating the workflow by traffic controller 
setting dataset status INVALID to inexistant dataset /NoBPTX/Run2016H-05Feb2018_ver2-v1/NANOAOD considered succeeding
prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199 and children are rejected
Clone payload
{u'cores': u'', u'splitting': u'2x', u'memory': u''}
Failed to create clone for prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199! Check logs for more information. Action will need to be resubmitted.
Failed to create clone for prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199!
Done
Failed to create clone for prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199!
Failed to create clone for prebello_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180207_204244_8199!
finished

**Comment by areinsvo** [comment]
I'm confused. Jean-Roch, why did you say the issue is with rejecting the ACDCs?
Looking at the logs, actor first claimed that it couldn't create the clone, but then succeeded three minutes later. The clone appears to be running fine now, with all of the other workflows rejected. 
https://dabercro.web.cern.ch/dabercro/unified/showlog/?search=ReReco-Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2-0008

I tried to check that the splitting was implemented correctly, but request manager claims that events_per_job is set to NULL in the new clone. Jean-Roch, is this expected?
https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_Run2016H-03Feb2017_ver2-v1-NoBPTX-05Feb2018_ver2_944_180228_173718_5022

**Comment by vlimant** [comment]
The code of actor does not seem to be taking care of the rejection of the children, not explicitly; seems to be relying on the web tool’s input.
The acdc got rejected by Paola when manually making a clone.

**Comment by areinsvo** [comment]
Looking at the notes from our recovery tools meeting, I believe this is precisely how we decided to handle things: https://docs.google.com/document/d/1VjcV39Ow9-5ucn50-PD9SciiPKsmi_K8Rj2NLOnBBx0/

> We reject and clone ONLY original requests, not ACDCs. If we reject and clone the original request, all the ACDCs must be rejected. 
> Dan's tool should list all ACDCs for a workflow when rejected.

@dabercro or @prozober feel free to correct me if I'm wrong.

**Comment by vlimant** [comment]
there must have been a confusion then. I don't see a use case to clone a wf and leave the acdc not rejected. please adjust actor @areinsvo

**Comment by areinsvo** [comment]
I agree. As the notes I posted say,  "If we reject and clone the original request, all the ACDCs must be rejected." I think you're taking issue with how we get the list of ACDCs to reject. Right now, actor rejects all ACDCs that are in the list @dabercro includes in the clone action. Do you have a better proposal for how to get the names of the ACDCs to reject?

**Comment by vlimant** [comment]
we can find the familly of acdc to be rejected on unified's side. i.e. there is no need to get the list from the wtc-console. Maybe a minute modification that can simplify things.

**Comment by prozober** [comment]
@areinsvo, Jean-Roch found the issue. Do you think we can make that modification easily?

**Comment by areinsvo** [comment]
Yes, it looks simple enough to do. I'll implement it today and hopefully you can test it tomorrow. Sorry for missing this before; it got lost in the storm of finishing my dissertation.

**Comment by areinsvo** [comment]
Jean-Roch was right; the changes were easy to make. @prozober, please let me know when you have a workflow to clone that we can use to test this feature.
https://github.com/CMSCompOps/WmAgentScripts/commit/53665e238b0dd42b914dac73778761ce4402d9c6#diff-699b8f6dbca6e1b3cf8365e884aaaf0e

**Comment by areinsvo** [comment]
@dabercro, assuming this change is successful, then there is no need for the workflow tool to pass the "ACDCs" list anymore for kill and clone actions.

**Comment by prozober** [comment]
@areinsvo I finally had the chance to kill and clone a request with more than two ACDC rounds
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BTV-RunIISpring18wmLHEGS-00009

as you can see, the third ACDC round was not rejected
https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_ACDC3_task_BTV-RunIISpring18wmLHEGS-00009__v1_T_180426_200124_4344

Could you please take a look?

**Comment by vlimant** [comment]
the commit was on May 4, while the actor action was on May 2. Any more recent one?
