### ISSUE TITLE
Unique Team value

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#267]
Now the requestInfo returns a unique Team value, therefore the **['Teams'][0]** must be changed for **['Team']**
For example:
https://github.com/CMSCompOps/WmAgentScripts/blob/d226c3b13ea35437640bdbe395394622115ebf11/recoverMissingLumis.py#L734
https://github.com/CMSCompOps/WmAgentScripts/blob/bf0596e65a1268ac0798017aebd8c2324c391e99/Unified/recoveror.py#L442

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/a4c105cce01fd76ae9850de68fd680d59984f705
