### ISSUE TITLE
onhold/bypass from the wtc-console

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#268]
@dabercro I think we could add the onhold and bypass option so that the wtc @prozober can set it via the tool.
@areinsvo once this is done, I'll hook something up in actor

**Comment by dabercro** [comment]
To both ACDC and Clone? These are just True/False values, right?

**Comment by dabercro** [comment]
Or do you mean that these are special separate actions?

**Comment by dabercro** [comment]
Under "Special" actions, we already should have "by-pass" (which I can rename to "bypass" for consistent naming). Do you just want me to add "onhold" there?

**Comment by vlimant** [comment]
by-pass of bypass, does not matter to me ;-)
please add on-hold indeed. once there and available, please let us know.
@prozober please make a jira for the next wf that you set bypass or on-hold with the console and I'll take a look at wiring this in actor.

**Comment by prozober** [comment]
We should only use those actions on the original request, right @vlimant? Or will the actor handle a bypassed or on-hold ACDC?

**Comment by vlimant** [comment]
they will apply only to the original request indeed, acdcs are slaved under the hood.

**Comment by dabercro** [comment]
Okay, I added that action. @prozober I think I found the bug that was causing the globalerrors page to not update too.

**Comment by prozober** [comment]
Guys, I've just sent a bypass action. @vlimant 
`{"pdmvserv_task_HIG-RunIIFall17wmLHEGS-00961__v1_T_180220_201255_3132": {"Action": "special", "Reasons": ["Config issues"], "ACDCs": ["vlimant_ACDC0_task_HIG-RunIIFall17wmLHEGS-00961__v1_T_180312_134059_3877"], "user": "prozober", "Parameters": {"action": "by-pass", "other": ""}}}`

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/41d8a1c16f2b796a0b8ff43212f2c4a24e82148f

it goes in my bapss list, until better days with mongodb.

**Comment by vlimant** [comment]
@dabercro I think there is no reason to call is "special", I'd vote to flag it "action" : "bypass" ; is there an issue with that ? let me know once this is changed so that I adapt on the receiving end

**Comment by dabercro** [comment]
I can call "special" "other" instead, if you'd prefer. Are there other parameters that should be set with "by-pass"? If not, I'm not sure it's useful to clutter up the webpage with simple actions like that. To just change the way the action is presented for "other" while keeping the page clean, I would have to sit down and rewrite some stuff.

**Comment by vlimant** [comment]
ok, @prozober and @dabercro have a better feeling for the web interface. special is fine.

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/41d8a1c16f2b796a0b8ff43212f2c4a24e82148f
