### ISSUE TITLE
JIRA integration

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#269]
found this 
https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/

indicating this to discover the schema
https://its.cern.ch/jira/rest/api/2/issue/createmeta?projectKeys=CMSCOMPPR&issuetypeNames=Task&expand=projects.issuetypes.fields

and is a good pointer to creating jira automatically, with priority and all.
The wtc-console/actor could deserve the same integration to update JIRA.

**Comment by vlimant** [comment]
0b97a4882fcad3fe6211beef737d83bc2db927bf

**Comment by vlimant** [comment]
@SvenjaPflitsch if you have time to do some dev on this

**Comment by vlimant** [comment]
@sharad1126 there is info here for writing a bit of code, if you want to simplify your life

**Comment by sharad1126** [comment]
wow.. this sounds good.. I can try this and also see that it doesn't makes JIRA for the first ACDC(could be a little tricky)

**Comment by vlimant** [comment]
we have all markers available for creating the JIRA when we/you want it.
initial work is to be able to make a jira and do a search using the JIRAClient class in https://github.com/CMSCompOps/WmAgentScripts/commit/0b97a4882fcad3fe6211beef737d83bc2db927bf

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/4f8b6345015009260cab788681fa0aa6c220b387 done !
