### ISSUE TITLE
SiteWhiteList for cc7 compatible sites

### ISSUE THREAD

**Issue by areinsvo** [CMSCompOps/WmAgentScripts#270]
I checked, and this doesn't seem to be in Unified yet. Unified needs to be able to read from gwmsmon and prepare site whitelists accordingly for workflows that need to run on cc7 resources.

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/b24999317c03a00c015decc17a0f20e7e0f0ae64 should do it.
NB for relval the "cc7" in the string is still needs to be done
