### ISSUE TITLE
Create JIRA when action is enacted

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#272]
with help from 
https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#creating-an-issue-examples
we should be able to create JIRA with all relevant fields upon actor taking an action.
I don't think the "reason" is passed on to actor @dabercro , we would need this so as to fill the description of the ticket.

**Comment by dabercro** [comment]
The reason is available. For example, you can look here and search for "Reading issues": https://vocms0113.cern.ch:80/getaction?days=100&acted=1

**Comment by vlimant** [comment]
alright, then we should be able to create the JIRA automatically from actor (or vice versa...)
maybe a brainstorming is needed to decide how to take this to the next level @prozober @thongonary @mcremone

**Comment by vlimant** [comment]
relies on #269

**Comment by vlimant** [comment]
@sharad1126 FYI

**Comment by sharad1126** [comment]
Will discuss this with Dan and team during T&I meeting today

**Comment by sharad1126** [comment]
@vlimant should we take the info for the jira from https://vocms0113.cern.ch:80/getaction?days=100&acted=1 or from the actor? @dabercro we never fill the reason thing in the console.

**Comment by vlimant** [comment]
#356 as a seed
