### ISSUE TITLE
ACDC's sites not found

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#276]
The issue is related to the new "T1_UK_RAL_ECHO_Disk" location.
I'm ACDCing https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_ACDC1_task_BTV-RunIISpring18wmLHEGS-00009__v1_T_180410_174118_280, which data is in T1_UK_RAL_ECHO_Disk

> /store/unmerged/RunIISpring18DRPremix/BulkGravTohhTohbbhbb_narrow_M-4000_13TeV-madgraph/GEN-SIM-RAW/100X_upgrade2018_realistic_v10-v1/910000/BE3DC377-FC32-E811-AD97-0242AC1C0501.root @ T1_UK_RAL_ECHO_Disk

When I try

> python assign.py -s acdc -w prozober_ACDC2_task_BTV-RunIISpring18wmLHEGS-00009__v1_T_180420_144613_499

I got

> The taks in resubmission is: /vlimant_ACDC1_task_BTV-RunIISpring18wmLHEGS-00009__v1_T_180410_174118_280/BTV-RunIISpring18DRPremix-00029_1
> using vlimant_ACDC1_task_BTV-RunIISpring18wmLHEGS-00009__v1_T_180410_174118_280
> failed to get the acdc document for vlimant_ACDC1_task_BTV-RunIISpring18wmLHEGS-00009__v1_T_180410_174118_280
> nothing retrieved
> Traceback (most recent call last):
>   File "assign.py", line 488, in <module>
>     main()
>   File "assign.py", line 351, in main
>     sites = list(set([SI.SE_to_CE(site) for site in where_to_run[task]]) & set(SI.all_sites))
> KeyError: u'/vlimant_ACDC1_task_BTV-RunIISpring18wmLHEGS-00009__v1_T_180410_174118_280/BTV-RunIISpring18DRPremix-00029_1'

Could you please take a look at https://github.com/CMSCompOps/WmAgentScripts/blob/master/assign.py#L351 ?

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/74745ffda0e815f2c16d1ba435e63c6622d1b282 
and the acdc is assigned already
