### ISSUE TITLE
Unified error report does not get the exit codes

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#288]
https://cms-unified.web.cern.ch/cms-unified/report/pdmvserv_task_SUS-RunIIFall17GS-00005__v1_T_180618_191828_2442

A screenshot in case it's gone from webspace:
![image](https://user-images.githubusercontent.com/10479549/42825209-d0f70a64-89e1-11e8-9d8f-b578fee233cd.png)

There are failures with exit codes in WmStats, but they do not propagate to the Unified error report.

**Comment by vlimant** [comment]
how many such cases have you noticed. I go with a wmstat data server glitch
