### ISSUE TITLE
Agent manager - updates to reqmgr_aux docs triggered by trello

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#290]
It seems agents moved to the "Drained" column in the trello board trigger an Unified action which updates the agent reqmgr_aux doc to `"UserDrainMode": false`. 

I usually move cards to Drained only when the agent is down and removed from wmstats. It happens that I moved submit3 to the Drained column before shutting it down and I see that the agent has acquired a bunch of work and is running jobs once.

We should have unified acting based on only the "Draining" and "Up & Running" columns.

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/d783cf713ea5fcd86e630d5ce9cd97d999c93962

**Comment by vlimant** [comment]
the drained and offline cards were indeed ignored for sync and lead to waking up agents in that box.

**Comment by amaltaro** [comment]
I don't know where that "offline" list name comes from, but thanks for fixing it.
