### ISSUE TITLE
Agent manager - let draining agents with warnings in drain mode

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#291]
It happened last night that vocms0257 was moved to "Up & Running" by unified, even with a disk warning at 89%. This should be changed such that we only have _healthy_ agents moved to production.

In addition to that, I remember you @vlimant saying that cards manually moved to the Draining column in trello would make the agent be out of the unified agent watch list. The agent was automatically put in drain by WMAgent itself, but the trello move was done by me. Did I miss something?

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/9f725b1f4796a95a74e814ac09be76a93abff851
