### ISSUE TITLE
Relval should not go to assistance-manual

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#292]
For example
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_10_2_0_pre6__fullsim_noPU_HS_fixCPE_highIO-1531273595-QCD_Pt-20toInf_MuEnrichedPt15_13TeV
is in assistance-manual because of biglumi.

Relval should be automatically bypassed in any case and there should be no action required for ops.

**Comment by SvenjaPflitsch** [comment]
I have never seen this status before and usually RelVals just fail. I even asked @prozober  what is usually done if one shows errors that could be fixed with an ACDC like file-read issues and she told me that they are not touched.

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/b8109819d12713e8a283f84a2616417b3c443c9e
