### ISSUE TITLE
Unified shows wrong/incomplete explanation for exit code 99401/99303/99400

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#295]
Unified needs to check the explanation of these exit codes(99400/99401/99303) properly before displaying it on the page. For eg, https://cms-unified.web.cern.ch/cms-unified/report/pdmvserv_task_B2G-RunIIFall17DRPremix-00162__v1_T_180307_173158_8536#B2G-RunIIFall17DRPremix-00162_1:99401 workflow doesn't tells which site has the problem exactly, where as WMStats has the proper error message explanation. Can you please have a look. Thanks.

**Comment by vlimant** [comment]
@ticoann  and @amaltaro can maybe tell why the documents retrieved from wmstats do not contain the site location for these errors. unified is merely a different visualization for that
