### ISSUE TITLE
Need to fetch logs by request

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#296]
We need a mechanism to fetch JobLogs, condorLogs and the Unified JobReport by request.
This is needed when an issue is being debuged.

**Comment by vlimant** [comment]
can you please be more specific about how/what/when ? 
N.B. Unified/showError.py can be run manually with the -w <wfname> to create a report
N.B. this is something in the list of things for the new console

**Comment by prozober** [comment]
This is needed when we need to provide logs to the requestors or site admins, in order to identify an issue with a request or a site.
As this is a critical task, we need to report the logs as soon as possible. We've seen top priority workflows with issues, taking a couple of days to provide the info we need.

Does showError.py fetch the JobLogs too?

@sharad1126, FYI.

**Comment by vlimant** [comment]
showError does get some logs, if you need targeted logs, there is a link in wmstats
