### ISSUE TITLE
remove ReqMgr2Only flag

### ISSUE THREAD

**Issue by ticoann** [CMSCompOps/WmAgentScripts#299]
I am not sure it affect here. related to https://github.com/dmwm/WMCore/pull/8703
Anyway, this will be in next deployment (HG1809). I will check the WmAgentScript whether anything need to be updated

**Comment by vlimant** [comment]
@ticoann this https://github.com/CMSCompOps/WmAgentScripts/commit/04adb1218420cc1091337a99ce98cc6b0782d465 should be enough to make sure the absence of the flag is not interpreted wrongly

**Comment by vlimant** [comment]
what would be left to do, is to clean up completely reqMgrClient from any reqmgr1 interface

**Comment by ticoann** [comment]
Thank you for taking care of this.

**Comment by amaltaro** [comment]
One could also completely remove this check for ReqMgr2Only and avoid one additional query to reqmgr2.

**Comment by vlimant** [comment]
c.f. #313
