### ISSUE TITLE
Rejection not propagated

### ISSUE THREAD

**Issue by SvenjaPflitsch** [CMSCompOps/WmAgentScripts#300]
I have found two instances where the workflow has been killed and resubmitted but Unified still shows it as "away" and the new workflow cannot run due to this. 

This one has been handled by @prozober : 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_PPD-RunIIFall18wmLHEGS-00001 (JIRA: https://its.cern.ch/jira/browse/CMSCOMPPR-3334)

This one has been handled by Scarlet as the request manager: 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_SUS-RunIIFall17wmLHEGS-00131 (JIRA: https://its.cern.ch/jira/browse/CMSCOMPPR-3350)

**Comment by vlimant** [comment]
there is no issue to be solved in the software. checkor has not been able to run on those since they have been rejected

**Comment by vlimant** [comment]
oh, and BTW @SvenjaPflitsch @thongonary @mcremone the "issue" is because @scarletnorberg has hard rejected this by hand
    {
      "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=snorberg/CN=696603/CN=Scarlet Rachel Norberg", 
      "Status": "aborted", 
      "UpdateTime": 1534153924
    }, 

instead of either using Unified (which we should not do at AD role) or McM (which she can as prod manager)

**Comment by thongonary** [comment]
For the PPD one Paola rejected it with reject.py. Is it not supposed to be used?

**Comment by vlimant** [comment]
it always worked. there is no issue to be solved in software
