### ISSUE TITLE
WMStats reports for some ACDCs are empty

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#301]
@amaltaro @ticoann  WMStats reports for some ACDCs are empty. 

Workflows -

https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-01415

https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-01396

https://its.cern.ch/jira/browse/CMSCOMPPR-3297
https://its.cern.ch/jira/browse/CMSCOMPPR-3387

Please have a look.

**Comment by amaltaro** [comment]
Sharad, you probably wanted to open it for https://github.com/dmwm/WMCore instead.

> https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-01415

there is a total of 20 requests handling this prep_id, can you please be more specific with which *request name* didn't upload ACDC documents?

> https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-01396

it's been announced. I'd say you can forget this one.

**Comment by sharad1126** [comment]
Ahh sorry .. i'll open an issue in WMCore ... will close this one..
