### ISSUE TITLE
Workflows stuck in away (Unified) / completed (ReqMgr2)

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#309]
At the moment, there are 1589 workflows stuck in this state
https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?in_production=1&rsort=2&older=2&status=validation 
Some has been in this state for more than 3 weeks, for example: https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2016B-L1MinimumBias1-07Aug17_ver2-0004
Checkor runs normally -- it ran yesterday without any crash. 
We need to investigate and fix this problem.
@SvenjaPflitsch @vlimant @mcremone @dabercro

**Comment by SvenjaPflitsch** [comment]
I tried to run checkor manually on the example given by Thong and got an error. 
I was logged in at vocms0275. It does not look like a general issue as the normal checkor logs do not show these kinds of error messages. @vlimant do I need to load another module or initialize something to run checkor manually now? 

-------------------------------------------------------------------------------------------
python Unified/checkor.py prebello_Run2016B-v2-L1MinimumBias1-07Aug17_ver2_8029_180504_205941_1258
Using the rw account
no options passed, assuming we do everything
Traceback (most recent call last):
  File "Unified/checkor.py", line 1338, in <module>
    checkor(url, spec, options=options)
  File "Unified/checkor.py", line 34, in checkor
    fDB = closeoutInfo()
  File "/data/unified/WmAgentScripts/Unified/utils.py", line 2517, in __init__
    import pymongo,ssl
ImportError: No module named pymongo
------------------------------------------------------------------------------------

**Comment by thongonary** [comment]
@SvenjaPflitsch would these help? https://github.com/CMSCompOps/WmAgentScripts/blob/master/cWrap.sh#L49-L52

**Comment by SvenjaPflitsch** [comment]
Yes that helped. Thank you Thong.

**Comment by SvenjaPflitsch** [comment]
It looks like the explanation for this is rather simple in the end. 
Checkor is only handling 200 workflows per round (value is set in unified) and it is handling the ones with high priority first. And since checkor is most affected from the eos instabilities, and we have lots of high-priority work in the system it is not getting to the ones with 85k priority or less.

**Comment by thongonary** [comment]
Thanks Svenja! So I guess the 200 workflows per round is to reduce the length of Unified cycle. According to a chat with Dima last week, it seems Unified was slow because it has to save workflows logs to EOS. We might want to disable this if it negatively affects our operation -- which is the case. @SvenjaPflitsch can you please try changing the value of those lines to an empty list, ie, "value" : []?
https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L291-L298
Then we should monitor if the cycle goes faster. In case it does, we can increase the checkor limit (to 1000, maybe).

**Comment by vlimant** [comment]
let's disable the report only from checkor. not changing expose_archive_code and expose_condor_code

**Comment by SvenjaPflitsch** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/e5024a06c577084455f45da2fd5bb9cf20979242/Unified/checkor.py#L1147 

I would change this line to "so = showError_options( expose = 0 )"

This looks like it would disable expose_archive_code and expose_condor_code to run during the run of checkor. @vlimant can you confirm or am I on the wrong track?

**Comment by SvenjaPflitsch** [comment]
It looks like checkor is running much faster now (5 completed cycles today already). In order to get the remaining completed workflows out of the system faster, could we temporarily increase the number of workflows it looks at to 300 per cycle (200 now)? 
That way it does not double check the high priority ones quite as often.

**Comment by thongonary** [comment]
Yes please go ahead.

**Comment by SvenjaPflitsch** [comment]
Would it be possible to run checkor on two machines at the same time? Maybe one taking care of the high-priority  workflows e.g. > 90k  and the second one on the low priority ones < 90k so they do not overlapp?

**Comment by SvenjaPflitsch** [comment]
I had another look at checkor and there are options to only check on the completed workflows and to only check on the ongoing ones or the ones in "manual", etc.. . If a second cycle of checkor were to be set up it could be configured to run with the option "strict", which makes it check only the workflows in ReqMgr status "completed". Though I am not sure what will happen if the regular cycle and the secondary one are checking on the same workflow at the same time.

**Comment by vlimant** [comment]
the concurrency is not a good thing indeed. what's the real reason something that has been functioning in the same situation is not functioning anymore ?

**Comment by thongonary** [comment]
Merged the PR to test. For the record: there are 2006 wfs in completed/away in https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?in_production=1&rsort=2&older=2&status=validation at the time of this post.

**Comment by vlimant** [comment]
1700 wfs ATM ?

**Comment by SvenjaPflitsch** [comment]
Yes that's right and everything with priority above 85k is gone.

**Comment by thongonary** [comment]
Yes it seems to progress OK. Perhaps we would want to increase number of concurrency (to 20) to see if the rate could be faster, if you don't see any problem with that.

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/2221dca39337e027064b11ffeeb044b0785cefa5

**Comment by thongonary** [comment]
Just had a chat with Justas and he thinks we should use http instead of https. Skipping authentication could increase the rate significantly.

**Comment by vlimant** [comment]
https won't work, since there is an auth layer to go through from the vm

**Comment by vlimant** [comment]
the analysis of one outlier wf and getRecoveryBlocks perf issue does not give a representative view of what is the bottleneck overall (information that is not here BTW)

**Comment by vlimant** [comment]
I had to push several changes to the original untested threaded code that was merged without testing ; when that happens @thongonary *you* have to be extra vigilant and stay on the watch constantly

**Comment by vlimant** [comment]
360 wfs ATM

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/49d4651217621ce258b0a41ef60af8d43f0a8478

**Comment by vlimant** [comment]
will likely push #326 in to speed up things further

**Comment by vlimant** [comment]
3
