### ISSUE TITLE
Warning system in Unified for eos issue

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#312]
At the moment when eos has issue, Unified just silently stops working, making it very difficult to debug and report the issue. 

We need a warning system when Unified stops working due to EOS issue that can be monitored by the Unified Officer. It should report as many details as possible, such as output from `fuse.cms.log` so that it can be forwarded to the EOS team.

This is urgent since it's also affecting transfer team who depends on Unified to do file deletion/invalidation. 

@vlimant @SvenjaPflitsch @dabercro @mcremone

**Comment by vlimant** [comment]
for silently see https://cms-unified.web.cern.ch/cms-unified/showlog/?search=critical&module=heartbeat&limit=100

**Comment by thongonary** [comment]
There is no indicator of EOS instability in the heartbeat report, and the UO has no procedure to verify it.

**Comment by vlimant** [comment]
just saying that it's not silent

**Comment by SvenjaPflitsch** [comment]
Looking at the timestamps, checkor has been running up to 4 times a day until 2 days ago. 4 times is still not a lot, but it is enough to not trigger the heartbeat message.

**Comment by vlimant** [comment]
the tail -f will not help you much picking up on the fact that checkor is running "slow".
on the other hand, it is pretty trivial to measure the full time spend and divide by the number of workflow handled, and set the alarm for this

**Comment by thongonary** [comment]
The fuse log is for reporting to the EOS team. We can't just say "EOS is not working" without providing further details and expect things to be fixed.

**Comment by vlimant** [comment]
Daniel has access to the node, and as admin rights. he has provided information here and there when necessary.
having this (the tail -f ...) exposed permantly out brings you nothing

**Comment by vlimant** [comment]
so the fuse log, one should ask Daniel, to provide information each time you find out there is an issue with a module and that it seems to be hanging on eos.

the "module took more than n sec/workflow" is a good idead @SvenjaPflitsch

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/a7d915d96fc5815423d5a3cd3cbb3e353b19f325 for 60s/workflow warning
