### ISSUE TITLE
Allow Fall18 campaign to run at CERN

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#315]
Dima doesn't want to put CERN back to production yet, but wants to make exception for Fall18 campaign so that it can run at CERN.
Do you think this is possible? @SvenjaPflitsch @vlimant

**Comment by SvenjaPflitsch** [comment]
The only thing I can think of is Re-Enabling CERN but blacklisting it for all campaigns except Fall18. But this means I need to go through all campaign configurations and edit the site-blacklist.

**Comment by vlimant** [comment]
that's a bit of a weird use case, not really supported.
however, it should be possible to include an override_allowed campaign parameter to let a set of sites be added to the list of allowed sites.

**Comment by thongonary** [comment]
> The only thing I can think of is Re-Enabling CERN but blacklisting it for all campaigns except Fall18. But this means I need to go through all campaign configurations and edit the site-blacklist.

Svenja, can you please proceed with this solution?

**Comment by SvenjaPflitsch** [comment]
The following campaigns now have T2_CERN and HLT blacklisted: 

RunIIWinter15pLHE
RunIIWinter15wmLHE
RunIISummer15wmLHEGS
RunIIWinter15GenOnly
RunIISummer15GS 

2016-----------------

Run2016B
RunIISummer16DR80Premix (Removed T2_CH_CERN from "SecondaryLocation")
RunIISummer16MiniAODv2 
RunIISummer16MiniAODv3 
RunIISummer16NanoAOD
RunIISummer16NanoAODv3

2017-----------------

EOYReReco2017
Commissioning2017

PhaseIISummer17wmLHEGENOnly (only FNAL on SiteWhiteList)
PhaseIISummer17GenOnly
PhaseIISummer17pLHE
PhaseIISummer17D

PhaseIIFall17D    (Already Blacklisted)
PhaseIITDRFall17wmLHEGS
PhaseIITDRFall17DR  (Has SiteWhiteList without CERN)
PhaseIITDRFall17GS 
PhaseIITDRFall17MiniAOD

RunIISummer17pLHE
RunIISummer17GS
RunIISummer17wmLHEGS
RunIISummer17DRStdmix (CERN removed from SiteWhiteList)
RunIISummer17DRPremix
RunIISummer17MiniAOD

RunIIFall17pLHE 
RunIIFall17wmLHEGENOnly
RunIIFall17wmLHEGS
RunIIFall17GS 
RunIIFall17DRPremix
RunIIFall17MiniAOD
RunIIFall17MiniAODv2 
RunIIFall17NanoAOD
RunIIFall17DRStdmix

2018------------------
Commissioning2018  
EarlyReReco2018
NANOAODRun2DataProd 
PhaseIISpr18AODMiniAOD

RunIISpring18wmLHEGS
RunIISpring18GS 
RunIISpring18DR      (CERN removed from SiteWhiteList)   
RunIISpring18DRPremix
RunIILowPUSpring18wmLHEGS
RunIILowPUSpring18GS
RunIILowPUSpring18DR 

RunIILowPUSpring18wmLHEGS
RunIIpp5Spring18wmLHEGS
RunIIpp5Spring18MiniAOD 

RunIISummer18wmLHEGS
RunIISummer18GS
RunIISummer18DR
RunIISummer18MiniAOD

**Comment by thongonary** [comment]
Thanks a lot @SvenjaPflitsch !
