### ISSUE TITLE
Issue with task_TOP-RunIIpp5Spring18wmLHEGS-00027

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#323]
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TOP-RunIIpp5Spring18wmLHEGS-00027

----- Begin Fatal Exception 28-Sep-2018 16:09:16 UTC-----------------------
An exception of category 'Configuration' occurred while
[0] Constructing the EventProcessor
[1] Constructing module: class=MixingModule label='mix'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------

https://its.cern.ch/jira/browse/CMSCOMPPR-3790

Failure happened at Florida where it is not suppose to run.
 "RunIIpp5Spring18DR" :{
"go": true,
"maxcopies": 1,
"lumisize": -1,
"resize" : "auto",
"fractionpass" : 0.95,
"tune" : true,
"secondary_AAA": false,
"secondaries" : {"/MinBias_TuneCUETP8M1_5p02TeV-pythia8/HINppWinter17GS-92X_upgrade2017_realistic_v11-v1/GEN-SIM" :
{"SiteWhitelist" : ["T1_FR_CCIN2P3","T2_CH_CERN","T2_US_MIT","T2_DE_DESY"] }
,
"/MinBias_TuneCUETP8M1_2017_5p02TeV-pythia8/RunIIpp5Spring18GS-94X_mc2017_realistic_v10For2017G_v3-v2/GEN-SIM" :
{"SiteWhitelist" : ["T1_FR_CCIN2P3","T2_CH_CERN","T2_US_MIT","T2_DE_DESY"] }
},
"parameters":
{ "SiteBlacklist": [ "T1_US_FNAL", "T2_US_Purdue", "T2_US_Caltech", "T2_US_Florida", "T2_US_Nebraska", "T2_US_UCSD", "T2_US_Wisconsin" ], "MergedLFNBase": "/store/himc" }
,
"custodial": "T1_FR_CCIN2P3_MSS"
}

@SvenjaPflitsch @vlimant can you please have a look?

**Comment by vlimant** [comment]
nothing to be solved here
