### ISSUE TITLE
Bug when calling rejector from injector

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#324]
https://cms-unified.web.cern.ch/cms-unified//logs/injector/2018-10-06_12:50:45.log

> invalidating the workflow and outputs by unified operator, reason: Transform to StepChain
> Traceback (most recent call last):
>   File "./Unified/rejector.py", line 256, in <module>
>     rejector(url, spec, options)
>   File "./Unified/rejector.py", line 66, in rejector
>     results = invalidate(url, wfi, and_self=True, only_resub=True, with_output= (not options.keep))
> NameError: global name 'invalidate' is not defined

**Comment by thongonary** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/49fe9aa47a80bf0f4545846435437d52c670b8ca should fix this

**Comment by thongonary** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/211f532b8d5fa7b177cc5e838637b199be1c2ea5 more fix

**Comment by thongonary** [comment]
We need to disable this conversion for RelVal. Any idea how to do this? @SvenjaPflitsch @vlimant

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/pull/278 introduced this

**Comment by vlimant** [comment]
you need the sso cookie

**Comment by mcremone** [comment]
we should authenticate with our certificate, like this:

cern-get-sso-cookie --cert ~/.globus/usercert.pem --key ~/.globus/userkey.pem -r -u https://cms-pdmv.cern.ch/mcm/ -o ~/private/mcm-cookie.txt

dropping the --krb option. This way the module runs.
