### ISSUE TITLE
Onhold_timeout should count from the day it's set onhold

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#332]
Currently it's counted from the day that the workflow is completed, which is undesirable. For example, if the workflow is completed for 2 weeks and then Sharad reports it to HN and sets it on-hold, it will be bypassed immediately. This is a typical situation since there are over 1000 workflows in assistance-manual, many of which have stayed for weeks. 

Ideally we want the onhold_timeout to be counted from the day it was set on hold. Would it be possible? @SvenjaPflitsch @vlimant

**Comment by vlimant** [comment]
there shouldnt be two weeks between docking in assistance and being handled
