### ISSUE TITLE
Tape subsciption fails

### ISSUE THREAD

**Issue by SvenjaPflitsch** [CMSCompOps/WmAgentScripts#333]
There are several workflows that are finished, but do not have a tape subscription. The prime-example being the new Premix library for the Autumn18 campaigns: https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_PPD-RunIISummer17PrePremix-00010
Going through the logs of the premix-library workflow line by line and there were two attempts to make a tape subscription: 

Using T1_UK_RAL_MSS as a tape destination for /Neutrino_E-10_gun/RunIISummer17PrePremix-PUAutumn18_102X_upgrade2018_realistic_v15-v1/GEN-SIM-DIGI-RAW
setting pdmvserv_task_PPD-RunIISummer17PrePremix-00010__v1_T_181017_182156_6467 to assistance-custodial

Using T1_US_FNAL_MSS as a tape destination for /Neutrino_E-10_gun/RunIISummer17PrePremix-PUAutumn18_102X_upgrade2018_realistic_v15-v1/GEN-SIM-DIGI-RAW
setting pdmvserv_task_PPD-RunIISummer17PrePremix-00010__v1_T_181017_182156_6467 to assistance-custodial

But I cannot find any PhEDEx requests resulting from this and it never reached "assistance-custodial-recovered" but directly jumped to "closed-out".

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/requestlist?dataset=/Neutrino_E-10_gun/RunIISummer17PrePremix-PUAutumn18_102X_upgrade2018_realistic_v15-v1/GEN-SIM-DIGI-RAW&node=T*_MSS

there's a pending subscription to tape. 

if there is one thing that cannot fail is a sample going to closed-out without a tape subscription if checkor has the guideline of making one
