### ISSUE TITLE
batches.json is empty

### ISSUE THREAD

**Issue by SvenjaPflitsch** [CMSCompOps/WmAgentScripts#334]
This has now happened twice in the last two weeks: 
The file /eos/cms/store/unified/batches.json could not be read because it was completely empty. 
This was why "batches = json.loads(eosRead('%s/batches.json' % base_eos_dir))" failed. 

The solution in this case was to add a pair of brackets "{}" to the file to make it recognizable as a json again. That way new entries could be added to the file. 

@thongonary suggested at the last P&R meeting to add a "catch phrase" that automatically adds a pair of brackets if the file is completely empty. But this has not happened before (at least that I am aware of) and if it keeps happening at this rate, there is likely something else that is failing and should be investigated.

**Comment by vlimant** [comment]
eos is eating the file indeed, you guys should start with that.
the content of the file might be relevant enough that putting {} is not the right thing to do

**Comment by vlimant** [comment]
#336 will remove the need for anything on this matter
