### ISSUE TITLE
Putting addhoc_lock.json on afs

### ISSUE THREAD

**Issue by SvenjaPflitsch** [CMSCompOps/WmAgentScripts#345]
Following up on the P&R meeting, it was suggested to move that file on afs instead of eos because it is small. @drkovalskyi @vlimant what needs to be done for this?

**Comment by drkovalskyi** [comment]
Can someone please clarify who exactly is using it and for what? I can look at the code tomorrow, but some overview would help.

**Comment by haozturk** [comment]
I do not see a problem with this file now, so closing the issue. Feel free to open it again if necessary.
