### ISSUE TITLE
Propagate Splitting Parameter

### ISSUE THREAD

**Issue by dabercro** [CMSCompOps/WmAgentScripts#350]
When the splitting parameter was used by @mcremone over winter break, it does not seem to have changed the splitting of the jobs created. The splitting still appeared in the list of parameters returned by the "getaction" API (for an example, open https://vocms0113.cern.ch:80/getaction?days=20&acted=1 and search for "splitting").

**Comment by vlimant** [comment]
please provide one specific case

**Comment by dabercro** [comment]
By following my link above, I see that the ACDC for workflow "pdmvserv_task_EXO-RunIIFall17GS-01591__v1_T_181120_133558_5038" has splitting entered for task "EXO-RunIIFall17GS-01591_0"

@sharad1126 or @mcremone may be able to say whichever particular workflow they noticed it for.

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/actor.py#L136 there is a protection against bad operators

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/actor.py#L186 actually

**Comment by sharad1126** [comment]
Thanks for the info @vlimant ... This means that the splitting works but not all can do it. Got it.
