### ISSUE TITLE
Campaigns disappearing from mongodb

### ISSUE THREAD

**Issue by SvenjaPflitsch** [CMSCompOps/WmAgentScripts#351]
The two campaigns HINPbPbAutumn18GS and HINPbPbAutumn18DR have been removed from mongodb twice now.
@mweinberg2718 and PdmV noticed the "no go due to" entry in the critical messages for this workflow:

https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIN-HINPbPbAutumn18GS-00033

I put them back on Thursday already, but when assignor tried to run on it on Saturday, they had disappeared again.

**Comment by vlimant** [comment]
where's the configuration in GH ?

**Comment by SvenjaPflitsch** [comment]
The configurations for both campaigns can be found here: https://its.cern.ch/jira/browse/CMSCOMPPR-3989 . I did not add them to campaignsConfiguration.json when I set them up, only used campaignsConfiguration.py .

**Comment by vlimant** [comment]
someone did put it back, correct ?

**Comment by SvenjaPflitsch** [comment]
I did, about 45 min ago when I was asked why this was still showing "no go"

**Comment by SvenjaPflitsch** [comment]
I always added them like this: 
python campaignsConfiguration.py --name "HINPbPbAutumn18GS" --configuration '{"go": true, "fractionpass": 0.95, etc... }'

**Comment by vlimant** [comment]
please copy the full command
from f7251ba44ee45807cf859d492757c2c5bb9aa591 you can also put the config in a json and do
python campaignsConfiguration.py --name HINPbPbAutumn18GS --configuration HINPbPbAutumn18GS.json

**Comment by vlimant** [comment]
I am looking for a type=relval sneaking in somehow

**Comment by vlimant** [comment]
the campaign is still there and nothing was changed ; I can only assume that either it was not added back in mongodb, or that one removed it.
please keep campaigns.json always up to date in GH

vlimant@vocms0275.cern.ch >python campaignsConfiguration.py --dump campaigns.json
212 campaigns damp
vlimant@vocms0275.cern.ch >git diff campaigns.json

**Comment by vlimant** [comment]
@SvenjaPflitsch looking at the history of the json file https://github.com/CMSCompOps/WmAgentScripts/commits/master/campaigns.json all I can say is that HINPbPbAutumn18DR went out of mongodb (for "some reason") on Nov 27, and has not made it back in the sync on Dec 19.

please put here the exact command line you have used to put it back on, and the command you have use the last time before

**Comment by SvenjaPflitsch** [comment]
Hi, 

I had to update this specific campaign just now and did it with the following command. I usually write everything in "json-style" instead of creating an extra campaignXY.json to be read. 

python campaignsConfiguration.py  --name HINPbPbAutumn18DR --configuration '{"parameters":{"MergedLFNBase":"/store/himc","SiteBlacklist":["T1_US_FNAL","T2_US_Purdue","T2_US_Caltech","T2_US_Florida","T2_US_Nebraska","T2_US_UCSD","T2_US_Wisconsin","T2_CH_CERN","T2_CH_CERN_HLT"]},"secondaries":{"/MinBias_Hydjet_Drum5F_2018_5p02TeV/HINPbPbAutumn18GS-103X_upgrade2018_realistic_HI_v11-v1/GEN-SIM":{"SiteWhitelist":["T1_RU_JINR","T1_FR_CCIN2P3"]}},"maxcopies":1,"custodial":"T1_FR_CCIN2P3_MSS","lumisize":-1,"fractionpass":0.95,"go":true,"tune":true}'

**Comment by vlimant** [comment]
the only way I see to loose a campaign in using outdated sofware through https://github.com/CMSCompOps/WmAgentScripts/commit/6ffda33c22fd140944cb9ab1cee3d433858848a0#diff-aee427b78cb693b7d987b925f831d50a
