### ISSUE TITLE
close JIRA on announcement

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#359]
@sharad1126 with the JIRA integration, we could have a convention of closing the JIRA that have a prepid in the "summary", when the corresponding workflow gets announced

**Comment by sharad1126** [comment]
Will start working on this locally. https://jira.readthedocs.io/en/master/examples.html#transitions
1. search interface
2. closing interface

**Comment by sharad1126** [comment]
@vlimant I think we should close the JIRA when the request is in announced/done-unlock, because sometimes it is in closed-out but not announced due to file mismatch.

**Comment by vlimant** [comment]
it goes to closed-out, only once really ready to go there (i.e. filemismatch will prevent the transition).
what is in #356 is to close all related jira (prepid in the summary field) when the unified status goes to "done" from closor.
