### ISSUE TITLE
add node names in the unified error report

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#369]
@SvenjaPflitsch I had a talk with Stephan Lammel and he told me that the site admins also look for nodes which helps them for finding info about the issues we report on GGUS. Do you think we can fetch it from WMStats to the error report too?

@vlimant @thongonary @amaltaro FYI

**Comment by SvenjaPflitsch** [comment]
I think @jenimal  is the expert on finding out the node  a job is running at. At least all tickets I know where problematic nodes were the issue were filed by her.

**Comment by jenimal** [comment]
Site Support has a script for finding this out @Maria  she's not on her apparently.  I'll ask her directly if she can pass the script along.  Generally she gets it from Dashboard Monitoring though not WmStats Error Reports.  That said I know the information is there.  Worker Node: is one of the field that is reported back to WmStats

**Comment by sharad1126** [comment]
Yeah, I think it would be great if we can use it and embed it to the error report in the unified so it is easier while reporting it on the ggus ticket for the site admins. Looking forward to knowing more about it @jenimal. Btw, I think you tagged the wrong Maria in your comment.

**Comment by haozturk** [comment]
Currently, we can see the sites where the errors occur in the Unified error reports. So, I am closing this issue.
