### ISSUE TITLE
Open Issue for Red Agents

### ISSUE THREAD

**Issue by dabercro** [CMSCompOps/WmAgentScripts#370]
This is something that @phylsix could help with. He's going down the list here: https://twiki.cern.ch/twiki/bin/viewauth/CMS/CompOpsPROperationSupport#Steps_to_Automating_CSP_shifting

@vlimant, let him know where the monitoring is, and @scarletnorberg, what rules we want to use (since the tickets will go to you). @amaltaro recommended opening a ticket if a agent is red for two cycles in a row. If you want to handle it, we'll just try to continue going down the list linked above.

**Comment by vlimant** [comment]
#365

**Comment by scarletnorberg** [comment]
Hello, @dabercro we monitor agents here: https://cmsweb.cern.ch/wmstats/index.html using the tab that says agent info. 
For an agent that has an error like this:
Error in worker algorithm (1):
Backtrace:
   <@========== WMException Start ==========@>
Exception Class: JobUpdaterException
Message: CouchInternalServerError - reason: Internal Server Error, data: {'stale': 'update_after', 'reduce': 'false'} result: None
	ModuleName : WMComponent.JobUpdater.JobUpdaterPoller
	MethodName : algorithm
	ClassInstance : None
	FileName : /data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py
	ClassName : None
	LineNumber : 102
	ErrorNr : 0
Than it should just be opened.
For anything that looks like this:
Last worker thread heartbeat than I agree that it should be two cycles in a row.
But @amaltaro can also confirm that this makes the most sense. @thongonary @mcremone

**Comment by vlimant** [comment]
@amaltaro what kind of indicator do we have for "two cycles in a row", as in #365 we could not come up with such a mechanism.
11dd48d3bbcc3fd94366a13c9797aa65a9958504 and 3f0069f460366f2ebfdeea07268ca53a029e1938 will help limiting the amount of jira activity.

as per https://its.cern.ch/jira/browse/CMSCOMPPR-4658 , there is something to be understood about "error" and "down" statuses of the agents, as it leads to multiple jiras ATM

**Comment by vlimant** [comment]
77a6b59eba93b9c6d00c277fa5ddc70af9d50ed4

**Comment by vlimant** [comment]
reopen if the traffic in jira is too high
