### ISSUE TITLE
automating Hyper news for bypassing the requests

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#379]
When we bypass a request or put it on hold, we can automate the HN tickets while putting them on hold or bypassing them with an additional parameter --HNmessage. Mostly these requests are for prep-ops HN so it could save us some time creating the HN ticket.

**Comment by vlimant** [comment]
for people not liking HN in the long run, it might be better sending that notification either (or both) to McM, or JIRA.

@drkovalskyi

**Comment by haozturk** [comment]
I do not see a reason for this functionality now, so closing the issue.
