### ISSUE TITLE
some alternatives to xrootd selection for tasks while sites in drain

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#380]
Selecting xrootd services in every other requests when sites are in drain where the site are from both sides of the Atlantic(US and Europe) can cause more read errors. 
eg.
ACDC created for task /pdmvserv_task_B2G-RunIIFall18wmLHEGS-00047__v1_T_190116_175532_9305/B2G-RunIIFall18wmLHEGS-00047_0/B2G-RunIIAutumn18DRPremix-00125_0/B2G-RunIIAutumn18DRPremix-00125_1. Actions taken
{"cores": "", "xrootd": "enabled", "sites": ["T1_ES_PIC", "T1_FR_CCIN2P3", "T1_IT_CNAF", "T1_RU_JINR", "T2_CH_CERN", "T2_ES_CIEMAT", "T2_FR_GRIF_IRFU", "T2_FR_GRIF_LLR", "T2_IT_Legnaro", "T2_IT_Pisa", "T2_PL_Swierk", "T2_UK_London_IC", "T2_UK_SGrid_Bristol", "T2_UK_SGrid_RALPP", "T2_US_Caltech", "T2_US_Nebraska", "T2_US_Wisconsin"], "memory": "20000" 

@vlimant @amaltaro @thongonary @dabercro can you please have a look and suggest if there could be some optimized solution to these kinds of requests?

**Comment by haozturk** [comment]
I haven't seen any file read errors related to this issue, so closing this ticket.
