### ISSUE TITLE
jira from stalled assignment

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#386]
since the alarms in unified about failing assignment (*) does not seem enough, should there be jira created automatically @drkovalskyi 
(*) https://cms-unified.web.cern.ch/cms-unified/showlog/?search=critical&module=assignor

**Comment by drkovalskyi** [comment]
In ideal world the answer is yes, but given that 186 open issues at the moment I don't think it will work well. If you make it to open and close the same ticket just updating it, then it can be something useful. Anyway, failures of such sort require a proper operational support and we are working toward that. So for now I don't think it will be useful.
