### ISSUE TITLE
Protection against empty lock files

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#393]
For example:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/remainor.py#L21
```
Using the rw account
Tue Mar  5 11:46:02 2019
Traceback (most recent call last):
  File "Unified/remainor.py", line 21, in <module>
    locks = [l.item.split('#')[0] for l in session.query(Lock).filter(Lock.lock == True).all()]
AttributeError: 'NoneType' object has no attribute 'split'
abnormal termination
```
We need a protection against such case.

**Comment by vlimant** [comment]
the "issue" is from RunIIAutumn18FSPremix declaring "" as a secondary 9c2f0637e3eaeaf2ac73d934b0be4b4eee6d720c

**Comment by sharad1126** [comment]
`[sagarwal@vocms0275 WmAgentScripts]$ python campaignsConfiguration.py --name RunIIAutumn18FSPremix
{
  "SecondaryLocation": [
    ""
  ],
  "fractionpass": 0.95,
  "go": true,
  "lumisize": -1,
  "maxcopies": 1,
  "overflow": {
    "PREMIX": {}
  },
  "resize": "auto",
  "secondaries": {
    "": {}
  },
  "secondary_AAA": true,
  "tune": true
}`

**Comment by sharad1126** [comment]
@thongonary should I remove this "SecondaryLocation"?

**Comment by thongonary** [comment]
Yes please try that.

**Comment by sharad1126** [comment]
```
RunIIAutumn18FSPremix
{
  "fractionpass": 0.95,
  "go": true,
  "lumisize": -1,
  "maxcopies": 1,
  "overflow": {
    "PREMIX": {}
  },
  "resize": "auto",
  "secondaries": {
    "": {}
  },
  "secondary_AAA": true,
  "tune": true
}
```

**Comment by thongonary** [comment]
Doesn't seem to work. Remainor still fails with the same message.

**Comment by vlimant** [comment]
sigh.
vlimant@vocms0275.cern.ch >python campaignsConfiguration.py --name RunIIAutumn18FSPremix
{
  "fractionpass": 0.95,
  "go": true,
  "lumisize": -1,
  "maxcopies": 1,
  "overflow": {
    "PREMIX": {}
  },
  "resize": "auto",
  "secondaries": {
    "": {}
  },
  "secondary_AAA": true,
  "tune": true
}

"" is still declared as a secondary. good thing is that https://github.com/CMSCompOps/WmAgentScripts/commit/9c2f0637e3eaeaf2ac73d934b0be4b4eee6d720c is there

**Comment by vlimant** [comment]
that can only mean there is another source

**Comment by sharad1126** [comment]
RunIIAutumn18FSPremix
{
  "fractionpass": 0.95, 
  "go": true, 
  "lumisize": -1, 
  "maxcopies": 1, 
  "overflow": {
    "PREMIX": {}
  }, 
  "resize": "auto", 
  "secondary_AAA": true, 
  "tune": true
}

removed empty secondary as well
