### ISSUE TITLE
Check OS/ScramArch before converting TaskChain to StepChain

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#396]
Besides the different Multicore values that is a showstopper for converting a taskchain into stepchain. We should also make sure that the stepchain job requires the same OS (SLC6, SLC7, etc), otherwise it will certainly bring unwanted surprises during runtime.
Thus, a check on the ScramArch values is necessary.

E.g.
["slc6_amd6_493', 'slc6_amd6_630', slc6_amd6_700'] is Ok
["slc6_amd6_493', 'slc6_amd6_630', slc7_amd6_630'] is NOT Ok

**Comment by srimanob** [comment]
Pilot is injected, and notify P&R:
https://its.cern.ch/jira/browse/CMSCOMPPR-5137

**Comment by amaltaro** [comment]
FYI @mcremone
