### ISSUE TITLE
Properly set Memory for StepChain workflows

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#397]
Different than TaskChain, StepChain workflows execute all steps into the same runtime environment (in the same job), thus the memory has to be properly setup.

The `Memory` parameter has to be set at the top level and it has to be the maximum memory setting found in a TaskChain workflow (in case conversion is in place).
See for an example:
https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/DMWM/StepChain_MC.json#L28

**Comment by vlimant** [comment]
that applies also to `Multicore` right ?

**Comment by amaltaro** [comment]
FYI @mcremone
