### ISSUE TITLE
site column empty in workqueue link

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#400]
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=vlimant_task_HIG-RunIIFall17wmLHEGS-01995__v1_T_181030_224109_3526
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=vlimant_task_HIG-RunIIFall17wmLHEGS-02954__v1_T_181015_122154_4974

These two requests were in the system for a long time. I had a look at these links and they had no site under the site column. @amaltaro as you said, if the column is empty, then it means there is no common site between sitewhitelist and data location and in case there is no input data for MC, it should be full of sites. Can you please correct me if I understood something wrong. 

@vlimant @thongonary FYI

**Comment by sharad1126** [comment]
updates on these two requests,  I cloned and assigned both the workflows manually.

**Comment by vlimant** [comment]
@sharad1126  did you mean to put a GH issue to WMCore instead.
@amaltaro FYI
