### ISSUE TITLE
no overflow for HI request 

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#402]
For future reference https://github.com/CMSCompOps/WmAgentScripts/commit/c1db41b8582227d80fbac5509097b3ba422ce3e7 for which a true solution needs to be found. like setting the right campaign, restricting to the campaign allowed sites ...

**Comment by haozturk** [comment]
Unified overflow is disabled for some time and will be migrated to WMCore in the future. So closing this issue.
