### ISSUE TITLE
move from mongodb to central couchdb

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#403]
@amaltaro and @vkuznet are suggesting to move the content of unified mongodb to reqmgr couchdb.
this would require to change insert, update, find, ... in many places, and can maybe done content by content once the proper manpower is identified

**Comment by vlimant** [comment]
branching from https://github.com/dmwm/WMCore/issues/8324

**Comment by vkuznet** [comment]
Jean-Roch, can you point to a few places where mongodb was used. Did you use common layer to work with DB or use plain mongodb calls. If later, I would suggest first to create a common layer/class which will use MongoDB as backend, then replace in a code direct calls to mongo with this class and later we can change the back-end.

Please also specify where mongodb resides now and how we can access it to see its content and decide about data migration.

**Comment by amaltaro** [comment]
I think it's important to know how MongoDB is used, such that we can make sure CouchDB would deliver the same performance/usability. Just as we do (or that we were suppose to do) for any service that joins the CMSWEB umbrella.

So, the very basic things like:
* number of daily requests
* average document size
* am I missing something?

**Comment by vlimant** [comment]
@vkuznet  the db is on vocms0274, and using pymongo calls. the db is opened on read write and the node has ip restrictions.

anything in utils.py that has mongo_client() is using mongo

@amaltaro  for the metrics, that's probably something that can be done from vocms0274, looking at the mongo logs /var/log/mongodb/mongod.log

**Comment by vkuznet** [comment]
I identified 13 unique databases that used by Unified, here there list:
```
        self.db = self.client.unified.statusHistory
        self.db = self.client.unified.replacedBlocks
        self.db = self.client.unified.transferDataset
        self.db = self.client.unified.cachedTransferStatuses
        self.db = self.client.unified.startStopTime
        self.db = self.client.unified.unifiedConfiguration
        self.db = self.client.unified.batchInfo
        self.db = self.client.unified.campaignsConfiguration
        self.db = self.client.unified.moduleLock
        self.db = self.client.unified.remainingDatasetInfo
        self.db = self.client.unified.reportInfo
        self.db = self.client.unified.closeoutInfo
        self.db = self.client.unified.wtcInfo
```

If we'll agree to move them to CouchDB we need to know the following information
for each database:
- what is a total data volume in particular DB
- what is a turn around for docs in DB
- what is an injection rate
- does DB is temporary (meaning it serves as a cache) or persistent
- does DB should be central or local (to whatever scope)
- does DB has overlap with existing ReqMgr2/WQ/etc. CouchDBs
- which DB is used by which Unified component, e.g. which DB(s) Transferor uses

**Comment by haozturk** [comment]
I cannot see a reason for this migration now, and therefore closing this issue. Feel free to open it again if someone finds it necessary.
