### ISSUE TITLE
Checkor Module failing 

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#405]
According to the logs and my understanding, the showerror script fails to open the error reports from various agents. Once it also logged about not able to copy to eos last week for which a service ticket(https://cern.service-now.com/service-portal/view-incident.do?n=INC1963814) was opened. Can someone please have a look why the module is failing again and again?

**Comment by sharad1126** [comment]
Checkor is trying to access this agent in the last failure log info. 
```
looking for condor log on vocms0253
==================================== Condor log retrieval =============================================
LISTING:  /data/srv/wmagent/current/install/wmagent/JobCreator/JobCache/pdmvserv_task_HIG-RunIIFall17wmLHEGS-01483__v1_T_190118_085746_9058/*/job_730928/
ls: cannot access /data/srv/wmagent/current/install/wmagent/JobCreator/JobCache/pdmvserv_task_HIG-RunIIFall17wmLHEGS-01483__v1_T_190118_085746_9058/*/job_730928/: No such file or directory
no on-going directory
```

This agent doesn't exists on https://cmsweb.cern.ch/wmstats/index.html - agent info.
@amaltaro @vlimant @thongonary FYI

**Comment by sharad1126** [comment]
@thongonary regarding the Eos service ticket, they have updated us. The issue looks like "connections issue to the eos cluster " and suggested us to update the xrootd to 4.8.6-1.

**Comment by sharad1126** [comment]
http://storage-ci.web.cern.ch/storage-ci/eos/citrine-depend/el-7/x86_64/

**Comment by haozturk** [comment]
Checkor is working fine now, so closing this issue.
