### ISSUE TITLE
restrict site list to remote secondary 

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#423]
here 

https://github.com/CMSCompOps/WmAgentScripts/blob/5c23367b5fbab9315cbcc073e030af1e8de623d6/Unified/assignor.py#L259

the allowed sites could be reduced to the list of sites in mapped aaa with the sec_availability

**Comment by haozturk** [comment]
Currently, I do not see a reason for such functionality and therefore closing the issue. And assignment is also planned to be migrated to WMCore in the near future.
