### ISSUE TITLE
Don't move old WMAgent versions to up&running

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#425]
If we have a new major release already in production, e.g.: 1.2.2.patch2, unified should not move old releases (e.g. 1.1.20.patch6) back to up&running (from the draining queue).

We might have incompatibilities (read new features) that could possibly affect central production.

**Comment by sharad1126** [comment]
As per the discussion with @amaltaro , he suggested to 
1. Remove the low load check for agents so that the agents with low load don't go to draining.
2. Stop completely the agents to move from draining to up&running. 

@thongonary @drkovalskyi  FYI

**Comment by sharad1126** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L5702 I think this is putting the agents to drain, but I am not sure what is offline. Will be investigating more about it.

**Comment by amaltaro** [comment]
@thongonary @sharad1126 can you please actually disable this module moving agents in and out of drain?
I see the same agent (vocms0283) - running an old version - going out of drain, then an hour or so later going into drain, and so on. This has been happening since Friday or Saturday, which just makes my life harder to get a new version (without flooding the system with pending jobs) in production.

**Comment by thongonary** [comment]
@amaltaro Don't look like there is a simple switch. https://github.com/CMSCompOps/WmAgentScripts/commit/005a0418ae2a9151be426f9985719771725f5d33 is my attempt to not let Unified interfere with agent deployment

**Comment by amaltaro** [comment]
Thanks, Thong. It might actually do the job!

**Comment by thongonary** [comment]
Cool. I will close it here, feel free to reopen if it doesn't work.

**Comment by vlimant** [comment]
guys, the only way old agents would be put back in action is if there was not new agent ready, and all agents maxed out.
the priority is to have work submitted, not to have agent draining. right?

**Comment by amaltaro** [comment]
And I was wrong, it's not Unified that is moving that agent in and out, but the agent itself (likely disk thresholds), given that it's using `AgentDrainMode` instead of `UserDrainMode`. Apologies for the misleading information.

Still, we can profit of this issue to make some modifications to the code handling agent statuses in Unified. Like what was originally reported in this issue, and possibly a switch to turn it on/off (or we extend the constraints to take into consideration jobs created and jobs in condor).

**Comment by amaltaro** [comment]
I guess we had a regression on this issue. Unified moved vocms0283 back from Draining to Up&Running in trello, even though that agent is running an old release: 1.3.3.patch3

Can someone please investigate and make sure this feature gets removed from Unified? @sharad1126 @haozturk @z4027163

**Comment by sharad1126** [comment]
@z4027163 I think what Alan mentioned above is happening https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L5975-L5991. If we remove this piece of code, then unified will only send emails but not pick anyone from drained ones.

**Comment by amaltaro** [comment]
Sorry for the noise, @todor-ivanov was upgrading the agent and had not yet updated the trello board. So everything looks normal and I'm closing this issue again.
