### ISSUE TITLE
Check for duplicated output before stepchain conversion

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#427]
So that it won't get converted and then be rejected by ReqMgr2. 
Reference: https://its.cern.ch/jira/browse/CMSCOMPPR-6268

@amaltaro is there any other requirements we should pay attention to? It's better to have the same set 
of requirements in ReqMgr2 and Unified so that Unified doesn't give the wrong stuff to ReqMgr2. 

Clarification: "duplicated output" in the title means the same output module and output data tier.

**Comment by thongonary** [comment]
@sharad1126 would you like to try to implement this?

**Comment by amaltaro** [comment]
It's not really duplicated output, but duplicated pair of: output module + datatier.
Checking output module isn't straight forward, so I suggest you simply check whether the same datatier appears twice in the same request.

**Comment by sharad1126** [comment]
@thongonary sure I would like to work on this and would like to know more about it.

**Comment by thongonary** [comment]
I think JR already wrote it 
https://github.com/CMSCompOps/WmAgentScripts/blob/671f183af3c3a1e441534947d7a8da3324199105/utils.py#L6729
Not sure why it was turned off.
