### ISSUE TITLE
can we add T3_US_SDSC to the list of US HPC Unified overflows to?

### ISSUE THREAD

**Issue by hufnagel** [CMSCompOps/WmAgentScripts#434]
It should use the same rules as T3_US_NERSC, T3_US_PSC and T3_US_TACC.

We recently commissioned SDSC Comet access in HEPCloud and want to start sending jobs.

**Comment by thongonary** [comment]
Done https://github.com/CMSCompOps/WmAgentScripts/commit/f467e0be3ec6e8b965405a2afc2c917b215f570e

However I realized that PSC and TACC were taken out of overflow map last year -- not sure what's the reason https://github.com/CMSCompOps/WmAgentScripts/commit/466cd115de708443e128cf8fc2ad74a3439e3966

For now only NERSC, OSG and SDSC are in the overflow map. Do you want me to add PSC and TACC back?

**Comment by thongonary** [comment]
Note that now NERSC and SDSC are receiving both overflowing jobs and jobs not requiring any input data.
PSC and TACC only receive jobs not requiring any input data.

**Comment by hufnagel** [comment]
I thought all these HPC sites were treated the same. There is certainly no reason to treat them different, they all have good external network connectivity. So unless someone else has any objections, I would request that PSC and TACC are added back to the overflow map.

**Comment by hufnagel** [comment]
Also, you said the change was made, but how long does this usually take to propagate to the submission machines (at FNAL). I assume here this is automatic, if we need to do something manually please let us know.

**Comment by thongonary** [comment]
PSC and TACC back to overflow list https://github.com/CMSCompOps/WmAgentScripts/commit/d48f8dd61e7ab3932e33c97224a738300472c5a4

One thing though: I see NERSC, PSC, and TACC are all in SSB http://dashb-ssb.cern.ch/dashboard/request.py/getplotdata?columnid=237&batch=1&lastdata=1
but not T3_US_SDSC. I assume some action needs to be taken to put it there. This is not within my power.
(OSG is also not in the list.)

**Comment by hufnagel** [comment]
Talking to Site Support to get T3_US_SDSC into SSB...

Coming back to my deployment question, when will this be active? Immediately? We haven't seen any jobs white listing T3_US_SDSC in the Fermilab WMAgent schedd yet.

**Comment by thongonary** [comment]
Yes it should be within few hours. Not sure whether SSB presence could affect it.

**Comment by thongonary** [comment]
@hufnagel Do you see jobs flowing to the sites? Can I close this?

**Comment by hufnagel** [comment]
We saw some jobs appearing for T3_US_SDSC, you can close this.
