### ISSUE TITLE
Make available input fraction configurable as campaign parameter

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#435]
Right now it's hard-coded in stagor
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/stagor.py#L31

We should make this configurable as a campaign parameter, so that some campaign can start early (such as BParking) without waiting for the full input dataset).

@sharad1126 can you please try this? Let me know if you need help.

**Comment by vlimant** [comment]
the functionality is there already https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json#L2345

**Comment by thongonary** [comment]
@amaltaro Should we add this `partial_copy` parameter to your new template? It's not directly related to distribution of the input dataset, but would be used for assignment. Depends on your final purpose.

**Comment by amaltaro** [comment]
If I correctly understand the meaning of this `partial_copy`, which is:
* assign a workflow if its input has more than xx% availability (how we define availability here? blocks transferred / blocks to be transferred?)

then yes, we definitely need to have it in the campaign configuration to be used within WMCore.

**Comment by thongonary** [comment]
@amaltaro That sounds right. Full definition here https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L3773-L3834

**Comment by amaltaro** [comment]
I'd call that as "implementation" instead of definition though :-)

**Comment by amaltaro** [comment]
If not available in the campaign, we assume it's `1`, correct?

**Comment by thongonary** [comment]
Haha yes.
