### ISSUE TITLE
Check on relval stat before announcement 

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#436]
So that relval will not announce at 2% without anyone notice.

Perhaps just modify this 
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L304
with the final statistics.

**Comment by thongonary** [comment]
Actually it's already implemented.
https://github.com/CMSCompOps/WmAgentScripts/blob/aab1dabc8a3e5cc10326690be5e2031b3da4e2a8/Unified/closor.py#L300-L304
We just need to advertise it.

**Comment by sharad1126** [comment]
Ohh cool. sure will keep this point in the meeting.
