### ISSUE TITLE
gwmsmon* from doccache giving json error 

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#437]
gwmsmon_prod_site_summary, gwmsmon_prod_maxused, gwmsmon_totals, gwmsmon_pool are giving an error since yesterday:
No JSON object could be decoded

http://cms-gwmsmon.cern.ch/totalview//json/site_summary opening this needs authentication. @thongonary I opened it on the browser and it asked for the sso. through the terminal we are able to curl it normally without authentication. what should we do to fix this?

**Comment by thongonary** [comment]
Can you just print out the output in the code to see what does it get?

**Comment by sharad1126** [comment]
json.loads(os.popen('curl --retry 5 -s http://cms-gwmsmon.cern.ch/poolview/json/summary').read()) returns a json

**Comment by sharad1126** [comment]
the issue was related to the IPs not added to the gwmsmon in the whitelist. the IPs were added and now working fine.
