### ISSUE TITLE
Only check small lumi output for taskchain

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#441]
Since it doesn't affect stepchain.

**Comment by sharad1126** [comment]
@thongonary can you please clarify what are we supposed to check here? I am a little confused with the title of the issue.

**Comment by thongonary** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L955
Add one requirement for taskchain

**Comment by sharad1126** [comment]
ok basically to check ```if ttype is task```. I will add this condition too.

**Comment by thongonary** [comment]
OK perhaps don't do it yet. For now just bypass thing manually and check number of total lumisecs.

**Comment by sharad1126** [comment]
sure, I am doing the same. I have already bypassed one and running acdc on one.

**Comment by haozturk** [comment]
This issue is not very clear to me, so I am closing it.
