### ISSUE TITLE
remove the stepchain conversion email

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#449]
As per the emails, there is a confusion created by these emails to PdMv regarding clone and step chain conversion. We will remove the email sending from unified. @thongonary FYI

**Comment by sharad1126** [comment]
eg. 
Cloned into cmsunified_task_HIN-pPb816Spring16GS-00151__v1_T_190907_060854_6418 by unified operator , reason: Transform to StepChain

**Comment by sharad1126** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/rejector.py#L262 &
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/rejector.py#L265. we can just comment them.

**Comment by thongonary** [comment]
Let's just turn off the clone message. The reject message is still important.

**Comment by sharad1126** [comment]
ok, I will comment out the line. hope this doesn't needs a PR.

**Comment by sharad1126** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/6c5a9d7a5f8c72129641421793b7452992033a96
