### ISSUE TITLE
phedex url issue for checkTransferLag 

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#450]
@nsmith- @dmielaikaite @nataliaratnikova can you please have a look?

```http://cmsweb.cern.ch/phedex/datasvc/json/prod/subscriptions?request=1687295&create_since=1553024209.35001&collapse=n```

The url after appending '&collapse=n' isn't working or taking too much time to load. 

@thongonary  FYI

**Comment by sharad1126** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L3505

**Comment by dmielaikaite** [comment]
this particular request was made for dataset level subscriptions and you want to see block level subscriptions with '&collapse=n'  so that is taking more time. 
https://cmsweb.cern.ch/phedex/datasvc/doc/subscriptions

**Comment by haozturk** [comment]
Phedex is not alive anymore, so closing this issue.
