### ISSUE TITLE
change trello secret to cmsunified

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#451]
at https://github.com/CMSCompOps/WmAgentScripts/blob/master/TrelloClient.py#L6 and in Unified/secret_trello.txt there are my credentials to interact with trello over the restapi.

one should create the credential for cmsunified and make the change

**Comment by sharad1126** [comment]
I have made a cmsunified account for trello board and got the key, token and secret values from the AP. @vlimant  Do we also need to provide it some allowed origins?

**Comment by sharad1126** [comment]
the credentials in all machines have been changed.
