### ISSUE TITLE
adiabatic agent drain

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#452]
this /afs/cern.ch/user/v/vlimant/public/ops/agent_drain.py would adiabatically get some jobs at higher priority to drain an agent faster. (partially related to #425) 

@amaltaro can create a wmcore issue to integrate something along this line in the agent.

it has to be adiabatic ; only handfull of jobs getting promoted at any given time.

**Comment by haozturk** [comment]
I cannot se
