### ISSUE TITLE
throttle campaign in transferor

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#465]
as per question at ops meeting on Nov 18. Easy to compute the number of active workflows per campaign and put a configurable cap in the campaign configuration

**Comment by drkovalskyi** [comment]
What is the reason to do so? Isn't it enough that we have a transfer queue and priorities?

**Comment by drkovalskyi** [comment]
For now I don't see a use case for throttling a campaign. It should be something extremely sick or special. For example if we consider RelVal a campaign it will clearly need some other controls if it can run everywhere with top priority. I would leave it as is till we have such a use case.

**Comment by haozturk** [comment]
Transferor does not run anymore, I cannot see a reason to keep this issue open, so closing it. Feel free to open it again if necessary.
