### ISSUE TITLE
Checkor still sends output dataset to CERN tape

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#467]
**Impact of the bug**
CERN tape 

**Describe the bug**
CERN tape has been set a virtual quota of 0 to prevent any automatic output sent there. However for some reason checkor still sends output datasets to it.

**How to reproduce it**
https://cms-unified.web.cern.ch/cms-unified/showlog/?search=%2FSpin0_ggPhi12j_g1_800_PseudoScalar_13TeV-madgraph%2FRunIISummer16NanoAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2%2FNANOAODSIM&module=checkor&limit=50&size=1000

> Using T0_CH_CERN_MSS as a tape destination for /Spin0_ggPhi12j_g1_800_PseudoScalar_13TeV-madgraph/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM
> Using T0_CH_CERN_MSS as a tape destination for /Spin0_ggPhi12j_g1_800_PseudoScalar_13TeV-madgraph/RunIISummer16NanoAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2/NANOAODSIM
> setting pdmvserv_task_EXO-RunIISummer16MiniAODv3-05429__v1_T_190924_161856_2287 to assistance-custodial
 
or perhaps just run checkor on such workflow.

**Expected behavior**
It should send the output to some other destination, not T0.

**Additional context and error message**

**Comment by sharad1126** [comment]
@thongonary do you think we might need to check unifiedConfigurations.json and remove T0 from there - may be this is one https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L91

**Comment by vlimant** [comment]
looking at https://cmsweb.cern.ch/phedex/prod/Request::View?type=xfer;nodes=T0_CH_CERN_MSS;state=appr and because there is no funny business, it can only mean that on Oct 23, the value of T0_CH_CERN_MSS was not zero.

Looking at all other manual operations there : #469

**Comment by nsmith-** [comment]
Indeed there was a brief period of a few hours that day where the value was nonzero in the tape usage json.
