### ISSUE TITLE
remove datasets from transfers_status as 0 is duplicate transfer is completed

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#478]
**Impact of the bug**
In case the dataset isn't able to transfer, unified creates a duplicate transfer on syncing back to considered but the transfer_status.json shows it 0 as the original transfer request doesn't gets completed. This increases confusion for the data management team.

**Describe the bug**
/WprimeToWZToWlepZlep_narrow_M-3000_13TeV-madgraph/RunIISummer16DR80Premix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/AODSIM in the request 1946246 had another transfer request 1980695 which got completed the workflow completed but the transfer_status.json still shows 0 which should have been removed or changed. 

**How to reproduce it**
resyncing a stuck transfer should reproduce the error as it would create a new transfer request.

**Expected behavior**
the dataset shouldn't have appeared in the transfer_status.json as 0 status. 

**Additional context and error message**
@z4027163 this is an issue but I think we can put it in low priority for now as input data placement will be migrated to wmcore soon. @amaltaro hope you take care about these issues in your microservices. 
@dmielaikaite @nsmith FYI

**Comment by haozturk** [comment]
Unified does not deal with input data placement anymore. So, closing this issue.
