### ISSUE TITLE
Query Kibana/Monit directly instead of gwmsmon

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#493]
as per https://github.com/dmwm/gwmsmon/issues/23 equalizor should be made to query kibana/monit since gwmsmon is only a messenger at this point (messenger that does not respond anymore BTW)

job tuning / resizing will then be properly enabled

**Comment by sharad1126** [comment]
@z4027163 can you see how to also assign this issue to @jenimal , I don't see her name in assignee dropdown list.
