### ISSUE TITLE
monit is unstable : failed to get site configuration

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#501]
#492 lead to failures in getting site configuration https://github.com/CMSCompOps/WmAgentScripts/commit/3334d6925ba24af3315dd152978654091cb9767f

**Comment by sharad1126** [comment]
@vlimant i have already a email thread open for this with the site support team and MonIT team.

**Comment by sharad1126** [comment]
Can you please tell why you commented out the send email? It’s good to know when it failed so we can get this fixed from MONIT team.

**Comment by sharad1126** [comment]
Just realised it's due to https://cern.service-now.com/service-portal/view-outage.do?n=OTG0054760.

**Comment by vlimant** [comment]
bombing one's inbox with thousands of emails is not really the way to go, is it. removing that was mandatory. having unified broken due to this is not even a good thing (the last source of site status information was far more stable overall), hence #502 

https://cms-unified.web.cern.ch/cms-unified/showlog/?search=critical&module=doccache was/is the source of information to keep an eye on

**Comment by vlimant** [comment]
should the site status/monit be put in a critical component @drkovalskyi @z4027163 ?
it would then have to be put under componentInfo

**Comment by sharad1126** [comment]
I agree, but I didn't know that it was bombarding and that's why I removed the comment.

I think even if the doccache exists, still it showed no document available for other metrics so I am not sure even putting this one in doccache is going to help a lot.

**Comment by sharad1126** [comment]
@vlimant I thought that the cache was supposed to use the last available doc for the ssb metrics if the ssb fetch is failed according to the last PR #502  but unfortunately looks like that isn't the case. assignor module fails since morning because the site-prod status isn't available.

**Comment by sharad1126** [comment]
From the assignor logs, `2020-04-27_05:40:26.log` ran without issues as the json was present in kibana but the next log `2020-04-27_06:05:25.log` gave the error for the metric and never used the last doc. this is something we need to check why https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L1884 didn't work as expected.

**Comment by sharad1126** [comment]
The error is as below:

```
cache hit ssb_prod_status
Failed to run function _get_dashbssb with arguments ['sts15min', 'prod_status'] {} for 1/10 times and 5[s] wait (%s). Exception
 Mon Apr 27 06:05:46 2020
 list index out of range
```

**Comment by vlimant** [comment]
the last doc for "ssb_prod_status" is {}
I think you have the wrong analysis, the logic in the code is such that the lastdoc will be taken. Only {} was stored as the last doc at some point, because get_dashbssb returned an empty list

**Comment by sharad1126** [comment]
ohh yeah... we might need to put another check to retain the previous log in case we encounter {} as a fetch result.

**Comment by sharad1126** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/15f55d57b1c7d4d6588755be29e029ca85f8dfc5 this should probably help. will keep an eye.

**Comment by vlimant** [comment]
the cache is purged ~constantly of expired documents (to avoid accumulation), and hence ssh_prod_status gets deleted too soon, no last doc means {} is used instead

980b5d6e1a57f58eceb6b44eac486c9adb9b5ba8  purges with 2 days grace period ; hopefully monit will never be down for that long

**Comment by sharad1126** [comment]
Thanks for changing that @vlimant . Hope this helps us. We are also working with SS team to make sure we get an alternative json for the ssb_prod_status so we don't have to depend on the unreliable monit services.
