### ISSUE TITLE
MongoDB grows in size and is not removing old data

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#521]
**Impact of the bug**
MongoDB db reached 867GB on 03/04/2020. It had 436 unified.* files in the ```/data/mongodb/db``` . This made all modules stop running as there was no space left in the /dev/vdb1.

**Describe the bug**
MongoDB grows in size and didn't removed the old data. The ```/data``` grew to 100% and all modules therefore stopped working. 

**How to reproduce it**
Better not to 

**Expected behavior**
As per the understanding, there should be a proper cleanup that should happen frequently to remove old documents from the collections in unified db in monggodb. 

**Additional context and error message**
```
[root@vocms0274 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.1G     0  7.1G   0% /dev
tmpfs           7.1G     0  7.1G   0% /dev/shm
tmpfs           7.1G  705M  6.5G  10% /run
tmpfs           7.1G     0  7.1G   0% /sys/fs/cgroup
/dev/vda1        80G  9.0G   72G  12% /
/dev/vdb1      1008G  955G  2.0G 100% /data
ceph-fuse       9.8T     0  9.8T   0% /cephfs
AFS             2.0T     0  2.0T   0% /afs
tmpfs           1.5G     0  1.5G   0% /run/user/105057
tmpfs           1.5G     0  1.5G   0% /run/user/78829
tmpfs           1.5G     0  1.5G   0% /run/user/0
cvmfs2          4.0G  1.3G  2.7G  34% /cvmfs/cvmfs-config.cern.ch
cvmfs2          4.0G  1.3G  2.7G  34% /cvmfs/cms.cern.ch
```

@z4027163 @drkovalskyi @vlimant @jenimal @amaltaro fyi

**Comment by sharad1126** [comment]
```
[root@vocms0274 data]# du -hsx /data/*| sort -rh | head -5
883G	/data/mongodb
71G	/data/bk_mongobd
915M	/data/mongodb_logs
507M	/data/unified
310M	/data/mongodb_exporter.log
```

```
[root@vocms0274 mongodb]# du -hsx /data/mongodb/*| sort -rh | head -5
864G	/data/mongodb/db
20G	/data/mongodb/logs
8.0K	/data/mongodb/mongod.conf.bkp
```

```
[root@vocms0274 mongodb]# du -hsx /data/mongodb/db/*| sort -rh | head -10
3.1G	/data/mongodb/db/journal
2.0G	/data/mongodb/db/unified.99
2.0G	/data/mongodb/db/unified.98
2.0G	/data/mongodb/db/unified.97
2.0G	/data/mongodb/db/unified.96
2.0G	/data/mongodb/db/unified.95
2.0G	/data/mongodb/db/unified.94
2.0G	/data/mongodb/db/unified.93
2.0G	/data/mongodb/db/unified.92
2.0G	/data/mongodb/db/unified.91
```

```
rw------- 1 mongodb mongodb 2.0G Apr  3 13:16 unified.415
-rw------- 1 mongodb mongodb 2.0G Apr  3 11:08 unified.416
-rw------- 1 mongodb mongodb 2.0G Apr  3 09:15 unified.417
-rw------- 1 mongodb mongodb 2.0G Apr  2 22:35 unified.418
-rw------- 1 mongodb mongodb 2.0G Apr  3 09:27 unified.419
-rw------- 1 mongodb mongodb 2.0G Apr  3 09:16 unified.420
-rw------- 1 mongodb mongodb 2.0G Apr  3 09:16 unified.421
-rw------- 1 mongodb mongodb 2.0G Apr  3 09:45 unified.422
-rw------- 1 mongodb mongodb 2.0G Apr  3 13:21 unified.423
-rw------- 1 mongodb mongodb 2.0G Apr  3 10:35 unified.424
-rw------- 1 mongodb mongodb 2.0G Apr  3 08:40 unified.425
-rw------- 1 mongodb mongodb 2.0G Apr  3 10:35 unified.426
-rw------- 1 mongodb mongodb 2.0G Apr  3 10:25 unified.427
-rw------- 1 mongodb mongodb 2.0G Apr  3 10:26 unified.428
-rw------- 1 mongodb mongodb 2.0G Apr  3 11:09 unified.429
-rw------- 1 mongodb mongodb 2.0G Apr  3 10:40 unified.430
-rw------- 1 mongodb mongodb 2.0G Apr  3 10:40 unified.431
-rw------- 1 mongodb mongodb 2.0G Apr  3 13:16 unified.432
-rw------- 1 mongodb mongodb 2.0G Apr  3 13:03 unified.433
-rw------- 1 mongodb mongodb 2.0G Apr  3 12:54 unified.434
-rw------- 1 mongodb mongodb 2.0G Apr  3 13:25 unified.5
-rw------- 1 mongodb mongodb 2.0G Apr  3 13:25 unified.6
-rw------- 1 mongodb mongodb 2.0G Apr  3 11:06 unified.7
-rw------- 1 mongodb mongodb 2.0G Apr  3 10:45 unified.8
-rw------- 1 mongodb mongodb 2.0G Apr  3 13:25 unified.82
-rw------- 1 mongodb mongodb 2.0G Apr  3 13:10 unified.9
```

**Comment by sharad1126** [comment]
Steps taken by me:
1. Shift ```/data/mongodb/bk_mongobd``` and ```/data/mongodb/logs``` to ```/eos/cms/store/unified/bk_mongobd``` and clean this from ```/data/mongodb```.
2. Run ```> db.runCommand({compact: 'agentInfo'})``` but it did no help in reducing the data size.

**Comment by sharad1126** [comment]
After @z4027163 removed the data from the ```/data/mongodb/db```, the status is:

```
[root@vocms0274 /]# du -hsx /eos/cms/store/unified/bk_mongobd/*| sort -rh | head -5
867G	/eos/cms/store/unified/bk_mongobd/db
73G	/eos/cms/store/unified/bk_mongobd/mongodb
20G	/eos/cms/store/unified/bk_mongobd/logs
4.1G	/eos/cms/store/unified/bk_mongobd/db_bk
4.0K	/eos/cms/store/unified/bk_mongobd/repairpath
[root@vocms0274 /]# du -hsx /data/mongodb/*| sort -rh | head -5
7.1G	/data/mongodb/db
140K	/data/mongodb/logs
8.0K	/data/mongodb/mongod.conf.bkp
```

**Comment by sharad1126** [comment]
Another thing to understand is, why does the mongo makes so many files for the unified db at the same time!

```
[root@vocms0274 db]# ll -lh | grep 14:00
-rw------- 1 mongodb mongodb 2.0G Apr  3 14:00 unified.5
-rw------- 1 mongodb mongodb 2.0G Apr  3 14:00 unified.6
-rw------- 1 mongodb mongodb  16M Apr  3 14:00 unified.ns
```

**Comment by sharad1126** [comment]
@z4027163 can you please explain a bit more explicitly what you did in the steps. what all exactly you deleted? Did you enable journal while restarting the mongo or not?

```
A brief recap of what was done by Qier:
1. back up DB directory in eos
2. rm some data file, run repair in mongo shell. Result: failed (no reaction from db.repairDatabase() , no file reduction, this function is not supported in version 4.2 or there were some conflict in journal since some of the data file is removed)
3. stop the mongoBD, try "mongod --repair --dbpath XXX". Result: fail, conflict in journal, data file not whole.
4. Make another copy in eos, treat new copy as dbpath. Remove "journal" folder in that copy. Then do: mongod --dbpath <new copy path> --repair
5. replace the /mongodb/db with the result from step 4.
6. chown -R mongodb:mongodb <all the file in db> (or else can't start mongodb)
7. service mongod start
```

**Comment by vlimant** [comment]
@dabercro 

it seems something is coming from the "prep" collection of the wtc-console 

```
wtc-console
	action 1 items 8192 total size
	system.indexes 6 items 8192 total size
	prep 21256 items 857276416 total size
	reason 4 items 8192 total size
	site 74 items 8192 total size
	task_action 3 items 8192 total size
	workflow_to_update 9478 items 2793472 total size
wtc-console-dev
	action 7 items 8192 total size
	system.indexes 7 items 8192 total size
	prep 14799 items 790740992 total size
	reason 1 items 8192 total size
	site 72 items 8192 total size
	task 3453 items 11243520 total size
	task_action 15 items 8192 total size
	workflow_to_update 5228 items 696320 total size
```

the top 10 of collection size is 

```
(u'wtc-console.prep', 857276416)
(u'wtc-console-dev.prep', 790740992)
(u'unified.reportInfo', 582324224)
(u'unified.cacheInfo', 282124288)
(u'unified.remainingDatasetInfo', 243314688)
(u'wtc-console-dev.task', 11243520)
(u'unified.replacedBlocks', 11182080)
(u'unified.startStopTime', 11182080)
(u'local.startup_log', 10485760)
(u'unified.statusHistory', 2793472)
```

reportInfo is purged https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/addHoc.py#L130 regularly
cacheInfo is purged https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/deadlock.py#L16 regularly
remainingDatasetInfo is not purged yet; #522

**Comment by vkuznet** [comment]
Sharad,
so my understanding that after deletion of old docs you went roughly from 900GB to 7GB, right? This is quite a relief. I reviewed #522  and its logic seems correct. This IS THE way I do in DAS/WMArchive and I never run compaction/repair on my DBs. I hope you put everything under control now.

Please keep in mind, the purge can be done in two different ways:
- you can run separate process (e.g. cron/thread) which takes care of that
- or, you add purse in front of your insert operations (this is the way I do) such that I don't need the former. But in order for that to be efficient you need to keep index on a key which you use in your delete_many query.

I hope you understand that any DB operations are efficient only with indexes, without index you'll  experience poor performance. Therefore, my advise please organize your indexes and keep eye on them. In MongoDB they should fit into RAM to be efficient.

**Comment by dabercro** [comment]
We don't have any developers or users for `wtc-console`. The new plan is to instead port the needed functionality into Rucio's OpInt Framework. I'll just turn that console off for now. Hopefully it will stop filling up MongoDB.

**Comment by jenimal** [comment]
Is it ready to go?  we need to keep a close eye on things so that we don’t refill the MongoDB again.

Jen


On Apr 4, 2020, at 5:34 PM, Daniel Abercrombie <notifications@github.com<mailto:notifications@github.com>> wrote:



We don't have any developers or users for wtc-console. The new plan is to instead port the needed functionality into Rucio's OpInt Framework. I'll just turn that console off for now. Hopefully it will stop filling up MongoDB.
