### ISSUE TITLE
After the input dataplacement migration, stagor is not needed

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#536]
**Impact of the new feature**
would avoid running one script on machine and stop making jsons which are not needed

**Is your feature request related to a problem? Please describe.**
#519 

**Describe the solution you'd like**
let's comment out the stagor module in precycle.sh

**Comment by sharad1126** [comment]
All the files created by stagor are now empty excep:
https://cms-unified.web.cern.ch/cms-unified/lost_files_datasets.json
https://cms-unified.web.cern.ch/cms-unified/lost_blocks_datasets.json

Do we know if anyone is checking these two files or not?
@nsmith-  @z4027163  @vlimant @dabercro @amaltaro 

Please confirm so we can stop running stagor module. Thanks.

**Comment by amaltaro** [comment]
I'm all in favor of decommissioning unneeded modules/code. However, if you do so, please make it one pull request per module/feature, with a very clear commit message. Just in case we ever need to get back there for reviving the module, recycling the logic, etc.

**Comment by sharad1126** [comment]
@amaltaro exactly what I have done as you can see above #537

**Comment by amaltaro** [comment]
Sounds good! You might want to create another issue to eventually deprecate/delete that module as well.

**Comment by nsmith-** [comment]
`lost_files_datasets.json` looks empty now for me.
For `lost_blocks_datasets.json` what are these supposed to indicate?
@dr-stringfellow
