### ISSUE TITLE
check dataset size for all output going to tape

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#538]
how come that 1.2PB dataset made it to an tape request while the limit (way too high already) is 850TB ?

https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L217

it's because the check ins only done for the dataset passed to ddm

https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1037

to be fixed

**Comment by vlimant** [comment]
is that not an issue anymore ?

**Comment by sharad1126** [comment]
I don't think there is any issues for the tape as such right now. I only see issues with disks at some sites. @z4027163 can you check and clarify this?

**Comment by vlimant** [comment]
is there no interest to merge this protection for checking all relevant output sizes?

**Comment by haozturk** [comment]
Unified does not deal with output data placement anymore, so closing this issue.
