### ISSUE TITLE
Remove phedex from component check and its related functions that aren't being used now

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#540]
**Impact of the new feature**
Let's remove phedex as a component check from unified scripts. 

**Is your feature request related to a problem? Please describe.**
As we won't be using phedex as such now for input data placement, do you think we should remove it from a set of component checks?

**Describe the solution you'd like**
remove all phedex related functions that are not needed. 

**Additional context**
@z4027163 @vlimant @amaltaro what's your suggestion?

**Comment by z4027163** [comment]
Looks good to me.

**Comment by z4027163** [comment]
It seems among all the 10+ modules using the component check, "checkor" and "htmlor" are still using the phedex service. If we want to remove the phedex out of the check, maybe we need to separately add it to these two modules?
