### ISSUE TITLE
Communicate  ParentageResolved flag with Unified

### ISSUE THREAD

**Issue by todor-ivanov** [CMSCompOps/WmAgentScripts#545]
**Impact of the new feature**
WMAgent & Unified

**Is your feature request related to a problem? Please describe.**
Due to the asynchronous execution of the merge jobs, WMAgent cannot figure out the correct file parentage information. Instead, the WM system relies in another thread that fixes the output dataset parentage information once the workflow gets into `announced` status. If this external thread is not behaving properly, it will add delays to the parentage information and it can be noticed by the end users analyzing the data [1].

**Describe the solution you'd like**
Assuming that Unified already has the whole workflow description before announcing it. We could add an extra check for StepChain workflows like:
* if the `ParentageResolved` is `True` (and it passes all the other unified checks), then the workflow can be announced
* else, log that the parentage information is incomplete and wait until the next cycle or so.

**Describe alternatives you've considered**
Other alternatives  are to  have WMAgent to only publish full information to DBS - this requiters long term development plans and redesign of portions of the WMAgent

**Additional context**
[1]
https://github.com/dmwm/WMCore/issues/9656

**Comment by amaltaro** [comment]
Thanks, Todor. I have made a few modifications to the issue description to make it more precise.

**Comment by todor-ivanov** [comment]
Thank you @amaltaro. Your change makes things much cleaner.
