### ISSUE TITLE
looks like logscycle.sh is not enable in acrontab

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#555]
**Impact of the bug**
condor logs are not being produced in https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/efficiencor.py

**Describe the bug**
acrontab has been commented out 

**How to reproduce it**
check acrontab and logs

**Expected behavior**
if acrontab is not commented, it should produce condor logs. 

**Additional context and error message**
@vlimant @thongonary do you know why it is commented out?

**Comment by sharad1126** [comment]
@amaltaro this is related to what @dpiparo was asking us that day about condor logs on mattermost channel.

**Comment by haozturk** [comment]
This entry has been disabled for 2 years. I haven't seen a lock of it so far. So, closing this issue.
