### ISSUE TITLE
inputscycle.sh is commented out in acrontab

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#556]
**Impact of the bug**
inputs_summary.py is not running 

**Describe the bug**
inputscycle.sh is commented out in the acrontab. 

**How to reproduce it**
check the logs and acrontab. 

**Expected behavior**
not sure

**Additional context and error message**
@vlimant @thongonary any suggestions?
@amaltaro @z4027163 fyi

**Comment by z4027163** [comment]
@sharad1126 It seems that the inputs_summary.py checks the wfs from campaigns 'RunIISummer16DR80' and 'RunIISummer16DR80Premix' about how much they were staged from tape to disk. I don't think we need this anymore. 

@thongonary Do you know the reason why we developed this in the first place?

**Comment by vlimant** [comment]
there was an emergency on staging samples from tape in Dec 2016. That lead to the restriction to the script and later to the restriction to these campaigns only.

**Comment by sharad1126** [comment]
thanks @vlimant for clarifying. @z4027163 I will make a PR to remove this.

**Comment by haozturk** [comment]
We do not run `inputscycle.sh` anymore. It will be removed from repository in the clean-up that we will do soon. Closing this issue.
