### ISSUE TITLE
chosing site for HIN relvals

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#564]
**Impact of the bug**
Relvals stuck in system for more than 10 days.

**Describe the bug**
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/batchor.py#L96
shows that if the relval is HIN, the site chosen is randomly between T1_DE_KIT or T1_FR_CCIN2P3. The problem here is now that if unified makes a campaign with site whitelist as T1_FR_CCIN2P3 and if data is at KIT, the workflows are stuck.

**How to reproduce it**
https://its.cern.ch/jira/browse/CMSCOMPPR-12285
https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?campaign=CMSSW_11_1_0_pre7__HIN_PU2018-1589471410

**Expected behavior**
Should have chosen KIT as the data is at KIT unless it checks the resources required by the relval and matches it with site whitelist which it is not doing here. 

**Additional context and error message**
@z4027163 @vlimant @amaltaro I think we should check the input data and then assign the campaign a site. what's your suggestions here?

**Comment by sharad1126** [comment]
@drkovalskyi can you please put your suggestion here and then we can change things accordingly. I am not sure removing KIT or N2P3 without proper discussion is a good idea as it was implemented since a long time and probably due to some reason.

**Comment by drkovalskyi** [comment]
Can't we read data remotely? If not move everything to a single site, lock data there and use only that site.

**Comment by sharad1126** [comment]
Conclusion: the site to be assigned for HIRelvals is only CERN.
