### ISSUE TITLE
Assignor assigned workflow which needs input to a T3 site only

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#574]
**Impact of the bug**
the workflow won't be able to run 

**Describe the bug**
http://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIIFall17DRPremix-00227
The latest workflow was assigned by unified to T3_US_Colorado without the primary AAA enabled which means that the wf cannot run as the input is not at T3 site. 

**How to reproduce it**
https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_BPH-RunIIFall17DRPremix-00227&module=assignor&limit=50&size=1000

**Expected behavior**
It should have been assigned to CERN

**Additional context and error message**
@z4027163 we should check why this happened. @amaltaro @scarletnorberg thanks for reporting this.

**Comment by z4027163** [comment]
@sharad1126 It's because the ssb_prod_status cache calling failed, which makes [1] return an empty result, and available sites to be only [2]. At the end, which only returns T3 sites at [3]. 
I don't know how we came up with the sites at [2], but either we need to update this list or we need to bypass things in case ssb_prod_status fails?

[1]https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L2066
[2]https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L2082
[3]https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/assignor.py#L113

**Comment by sharad1126** [comment]
@z4027163 i expected something like this actually. but I thought we had conditions there to avoid anything like this to happen. I think we need to fail the site assignment softly if the prod_status fails.

**Comment by sharad1126** [comment]
I have cloned almost 17 workflows due to this issue:
```
task_MUO-RunIISummer19UL16wmLHEGENAPV-00005
task_MUO-RunIISummer19UL16wmLHEGENAPV-00012
task_MUO-RunIISummer19UL16wmLHEGENAPV-00007
task_MUO-RunIISummer19UL16wmLHEGENAPV-00008
task_MUO-RunIISummer19UL16GENAPV-00002
task_MUO-RunIISummer19UL16wmLHEGENAPV-00010
task_MUO-RunIISummer19UL16wmLHEGENAPV-00009
task_MUO-RunIISummer19UL16wmLHEGENAPV-00011
task_MUO-RunIISummer19UL16wmLHEGENAPV-00002
task_MUO-RunIISummer19UL16GENAPV-00003
task_MUO-RunIISummer19UL16wmLHEGENAPV-00004
task_MUO-RunIISummer19UL16wmLHEGENAPV-00006
task_MUO-RunIISummer19UL16wmLHEGENAPV-00003
task_MUO-RunIISummer19UL16wmLHEGENAPV-00013
task_TOP-RunIIFall17DRPremix-00678
task_TOP-RunIIFall17DRPremix-00677 
task_BPH-RunIIFall17DRPremix-00227 
```
@scarletnorberg fyi

**Comment by sharad1126** [comment]
@z4027163 we still need to make sure this fails gracefully as there is no solution to this yet.

**Comment by z4027163** [comment]
@sharad1126 Once Alan fixes WMcore bug so that the WFs will only be assigned to the sites where the PU is located, it can automatically solve this issue.

**Comment by haozturk** [comment]
I do not see this issue in the production anymore and closing this one.
