### ISSUE TITLE
stop lockor module

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#580]
**Impact of the bug**
unnecessary module running as unified is not handling input data placement anymore. 

**Describe the bug**
@amaltaro as we have shifted all the input data placement to WMCore MS, should we also remove lockor module as we assume all the locks are now being made by Dynamo based on the data you have, or do you still want us to run the lockor module. 

**How to reproduce it**
the module has been running and producing logs.

**Expected behavior**
Should stop running lockor module as unified doesn't handles input data placement which is already migrated to WMCore MS. 

**Additional context and error message**
@z4027163 @vlimant @todor-ivanov  what's your suggestion?

**Comment by amaltaro** [comment]
Thanks for creating this issue Sharad. Can you please wait for a while until we can double check this with the DDM team?

**Comment by sharad1126** [comment]
Sure @amaltaro . I will wait for you and @todor-ivanov to give me a green light to stop this.

**Comment by sharad1126** [comment]
Benedikt confirmed that we can stop lockor module as he isn't using the info from unified for locking the data.

**Comment by sharad1126** [comment]
@amaltaro can you please confirm if you guys are locking output datasets too?
I saw in lockor that unified is sending request to lock both I/O . eg.
```
qnguyen_task_HIG-RunIISummer16NanoAODv5-02488__v1_T_190922_223721_5423 is unknown to unified, relocking all I/O
        /MSSMggA-HiggsToMuMu_MA-160_Tanb-25_13TeV_pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM
        /MSSMggA-HiggsToMuMu_MA-160_Tanb-25_13TeV_pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v2/NANOAODSIM
```

**Comment by amaltaro** [comment]
Yes, while workflows are active (until they get archived).

**Comment by sharad1126** [comment]
@amaltaro this means we are good to go ahead and stop the lockor module.

**Comment by amaltaro** [comment]
yes, DDM is anyways no longer consuming that information.
