### ISSUE TITLE
rucio data placement changes in closor

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#583]
**Impact of the bug**
closor is complaining about sending log due to incorrect syntax.

**Describe the bug**
`failed on chayanit_RVCMSSW_11_1_0_pre8BeamHalo_13__nanotest_200609_121530_7186 due to sendLog() takes at least 2 arguments (1 given) and Traceback (most recent call last):
File "Unified/closor.py", line 358, in run
self.close()
File "Unified/closor.py", line 504, in close
sendLog("Data Tier: %s is blacklisted, so skipping dataset placement for: %s" % (tier,out))
TypeError: sendLog() takes at least 2 arguments (1 given)`

**How to reproduce it**
`failed on chayanit_RVCMSSW_11_1_0_pre8TTbar_13__nanotest_200609_121527_5165 due to sendLog() takes at least 2 arguments (1 given) and Traceback (most recent call last):
File "Unified/closor.py", line 358, in run
self.close()
File "Unified/closor.py", line 504, in close
sendLog("Data Tier: %s is blacklisted, so skipping dataset placement for: %s" % (tier,out))
TypeError: sendLog() takes at least 2 arguments (1 given)`

**Expected behavior**
sendLog shouldn't have syntax issues.

**Additional context and error message**
@todor-ivanov @amaltaro looks like closor is working as expected for nanoaod datasets. I'll fix this bug for sendLog.

**Comment by sharad1126** [comment]
@amaltaro @todor-ivanov are you sure you want to send this log to the closor module directly only and not to the workflow logs?

**Comment by sharad1126** [comment]
@ishanrai05 we should make sure in our testing that things like these syntactical errors shouldn't be pushed. can you make a note here please.

**Comment by todor-ivanov** [comment]
Thanks @sharad1126
