### ISSUE TITLE
Alternative way to tag pilot workflows besides "pilot" processing string

### ISSUE THREAD

**Issue by justinasr** [CMSCompOps/WmAgentScripts#585]
**Impact of the new feature**
WMAgent? 

**Is your feature request related to a problem? Please describe.**
Only way to indicate that workflow is a pilot is to add "pilot" processing string. Processing string is always added to output dataset name. In some cases this is intended - to show that this dataset is not suitable for analysts, however, in other cases output is suitable for analysis and even though it is a pilot workflow, it would be better to *not to* include it in output in order to not confuse analysts.

**Describe the solution you'd like**
We would like to ask for a way to indicate that workflow is pilot without adding "pilot" as processing string. We would like to add it as processing string only in some cases, but also have a way to indicate it without reflecting that in output dataset name. It could be some parameter in "Comments" field (to be discussed with ReqMgr2 team).

**Describe alternatives you've considered**
It could also be any other argument, such as SubRequestType, but this would require deeper investigation and changes in McM as SubRequestType is already used in some cases.

**Additional context**
We use ReqMgr2 to submit workflows.

A couple of emails from @srimanob in our email thread:
```
We don't propose to delete what we are using now, we propose to have an alternative
way.

+ Pilot as processing string is useful, i.e. for pilot requests at the beginning of
  campaign. We don't expect analyst to use them as it runs quick, no approval from GEN
  conveners. The goal is to test the overall production.

+ Pilot as a comment is an additional option we would like to have. This is useful for
  validating reMiniAOD or reNanoAOD campaign, where we start from PROD AOD or MiniAOD.
  The output datasets are useful for analyst. So we would like to avoid having "pilot"
  as a processing string. However, we would like to short the communication process to
  assign these workflows manually during pilot period also.
```
```
In short, as of now, the "pilot" in processing string serves 2 purposes:
+ to trigger the workflow as pilot ==> To avoid delay of manual assigning workflow
+ to add to processing string

I would like to have the way to trigger that workflow is pilot without necessary of
adding "pilot" as processing string. We will have it on what we want only. "pilot" as
processing string is useful in some cases, but should be avoided in others.

Useful case:
We open a new GS, DR campaign, the first request we put in should have the word
"pilot" somewhere.
/TTJets_14TeV/Run3Summer22GS-pilot-xxxx-v1/AOD => useful to have "pilot" there, so
analyst will not use it

Case that I would like to avoid to have pilot in the processing string:
ReMiniAOD or ReNanoAOD because input datasets that we uses are big prod ones like
TTJets_Hadronic, or some Higgs process. The output is useful for analyst.
```

**Comment by wajidalikhan** [comment]
Thanks a lot Justinus!

**Comment by z4027163** [comment]
As long as we have the new "Comments" from reqmgr, it won't be hard for the unfied to change it to the normal output dataset name. I am wondering if all the output pilot datasets have the format of "/*/*-pilot_*/*" and you want "pilot_" to be removed from output dataset name? Or the format could be "/*/*-pilot-*/*" or something else. @justinasr

**Comment by justinasr** [comment]
We want another/additional way to indicate that job is a pilot. We don't want to change the current logic, i.e. if processing string has "pilot" in it, then it's a pilot request as it was up until now. In the new way, we don't want you to _remove_ "pilot", we want to omit it from processing string ourselves, but _say that it's a pilot_ in a different way - through comments.

Is unified code available for everyone? I would be interested to see that part that checks for "pilot" in processing string.

**Comment by z4027163** [comment]
The unified read "processingString" [1] to check if there is "pilot" string inside [2], and then assign the WF automatically.
I was thinking that for the new way you put some "comment" in the workflow, and when unified detected it, it removes the "pilot" string from the output. 
If you don't put "pilot" in the "processingString" then it would be easier, we can just straight up pass the WF when unified detects the pilot "comment".  Once you finalize with @amaltaro about what "comment" to add in reqmgr, things can be easily done on unified side.

[1]https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L8061
[2]https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L8082

**Comment by amaltaro** [comment]
Hi everyone, I apologize for not following these discussions carefully.
If my memory doesn't fail me, I think my advice many weeks ago was to actually use the `SubRequestType`:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1065

which AFAIK is only used for RelVals at the moment.
I know there are ongoing discussions for using the `Comments` field for other purposes, so we better use one parameter that is not going to act like a wildcard. Just my 2cents!

**Comment by sharad1126** [comment]
@amaltaro actually we discussed this last Friday and were wondering why we shouldn't use the `comments` field as it already exists.

**Comment by amaltaro** [comment]
And so is `SubRequestType`.

**Comment by scarletnorberg** [comment]
I thought the comment field was going to be used partial for the multiple validation information.
