### ISSUE TITLE
checkor reported unsupported operand issue

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#588]
**Impact of the bug**
checkor module where we want to check for nanoaod tiers failed on a specific workflow. Looks like the total filecount returned by the function was `None`.

**Describe the bug**
```
failed on pdmvserv_task_B2G-RunIISummer16NanoAODv7-02956__v1_T_200609_205933_7388 due to unsupported operand type(s) for +: 'int' and 'NoneType' and Traceback (most recent call last):
File "Unified/checkor.py", line 374, in run
self.check()
File "Unified/checkor.py", line 1041, in check
phedex_presence[output] = sum(map(lambda x: x[1], all_filecount_pb))
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**How to reproduce it**
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1041
wf: http://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_B2G-RunIISummer16NanoAODv7-02956

**Expected behavior**
should not report this error i.e. all_filecount_pb should not be `None`.

**Additional context and error message**
@amaltaro  @todor-ivanov looks like we encountered another new bug for nanoaod tier in checkor.

**Comment by sharad1126** [comment]
actually looks like more than one failed:
```
failed on pdmvserv_task_B2G-RunIISummer16NanoAODv7-02487__v1_T_200428_100049_5406 due to unsupported operand type(s) for +: 'int' and 'NoneType' and Traceback (most recent call last):
File "Unified/checkor.py", line 374, in run
self.check()
File "Unified/checkor.py", line 1041, in check
phedex_presence[output] = sum(map(lambda x: x[1], all_filecount_pb))
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by sharad1126** [comment]
#590 should be able to fix this. we are waiting to close this issue once we are satisfied.

**Comment by todor-ivanov** [comment]
The PR #590  provided by @vlimant  should fix this. Thanks!
