### ISSUE TITLE
Adding tape destinations to NanoAOD wfs?

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#589]
**Impact of the bug**
Checkor module is adding tape destinations to all workflows including NanoAOD workflows. @amaltaro @todor-ivanov @nsmith- is this suppose to happen or not at all?

**Describe the bug**
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1278-L1303 is responsible for adding the tape destinations to all workflows and I am not able to see any exclusions here to NANOAOD workflows. Am I understanding this properly or not?

eg. https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_EXO-RunIIAutumn18NanoAODv7-02797

**How to reproduce it**
https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_EXO-RunIIAutumn18NanoAODv7-02797

https://cms-unified.web.cern.ch/cms-unified/assistance.html#assistance-custodial has 26 wfs and all are nanoaod wfs.

**Expected behavior**
If I have understood correctly, NanoAOD output should not be assigned to tape by checkor module. @amaltaro @nsmith- please correct me here if I am wrong.

**Additional context and error message**
@todor-ivanov @amaltaro @nsmith- @z4027163 @jenimal please have a look and clarify this issue and let's solve it asap.

**Comment by todor-ivanov** [comment]
Hi @sharad1126 thanks for reporting it and @nsmith- Thanks for confirming Sharads's remark is True. At a first glance i thought we could use a similar approach as for the data placement, but here I do not see any data Tier resolution from the dataset name it is rather treating all them equally. I am not sure which would be the best approach here.

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L209
```
 "tiers_with_no_custodial": {
   "value" : ["DQM","DQMIO","RECO","RAWAODSIM"],
   "description": "The data tiers that do not go to tape. Can be overidden by custodial overide at campaign level"
 },
```
need to add NANOAOD and NANOAODSIM.

But then, what takes care of sending them to tape ...

**Comment by nsmith-** [comment]
@vlimant the same mechanism that is now being used to send the NANOAOD* output to disk will be used to send them to tape, namely the rucio subscription mechanism.

**Comment by nsmith-** [comment]
Since these workflows cannot be announced until this is resolved, is there a timeline?
I checked a few examples in https://cms-unified.web.cern.ch/cms-unified/assistance.html#assistance-custodial and indeed every one is a dataset that only exists in rucio. Right now there are 234 of them in total.

**Comment by sharad1126** [comment]
@nsmith- I will add the NANOAOD, NANOAODSIM tiers to the list and for the ones stuck in assistance-custodial, I will try to see how to announce them asap. technically putting the NANOAOD tiers should automatically do it in next checkor run. @vlimant thanks for pointing out the perfect place for it.
