### ISSUE TITLE
equalizor provides max_core as 15 cores for a 8 cores requested task

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#596]
**Impact of the bug**
`max_core` after resizing for the task is becoming 15 cores. 
eg. https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_BTV-RunIISummer19UL17GEN-00001&module=equalizor&limit=50&size=1000

**Describe the bug**
Need to understand why the max_core is calculating like this. https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/equalizor.py#L474
For a 8 core task, the max_core will always be 15 here.

**How to reproduce it**
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/equalizor.py#L474

**Expected behavior**
equalizor should follow the proper numbers of core count. when 8 core is provided, it should not increase the max core count. 

**Additional context and error message**
@vlimant @drkovalskyi @z4027163 please suggest and comment.

**Comment by vlimant** [comment]
min(8,15) = 8 as far as I can tell.
the 15 is there to make sure we never resize to more than 15 cores.
Maybe the actual issue could be explained a little better ?

**Comment by drkovalskyi** [comment]
I don't think it's an issue on its own. The issue was that it was no clear who performed resizing and how the memory requirements were computed. Basically we were asking for more memory than we needed on the Xeon Phi machines and were leaving some CPUs unused.

**Comment by sharad1126** [comment]
@vlimant I am not sure how `min(int(2*mcore)+2, 15)` where mcore is 8 makes it 8.

**Comment by drkovalskyi** [comment]
I didn't check the code. My comment was more general regarding how we got to the point to review the code and what it does.
