### ISSUE TITLE
assignor fails to run when dynamo isn't available

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#607]
**Impact of the bug**
Assignor is not able to assign any wfs when dynamo isn't available. @z4027163 do you think dynamo is an important component needed for wf assignment?

**Describe the bug**
Assignor module should run even if dynamo is not available. The components check for every module needs to be updated and module should fail only if the needed component is not available. 

**How to reproduce it**
check assignor logs. 

**Expected behavior**
assignor should run even if dynamo isn't available. 

**Additional context and error message**
@z4027163 @vlimant fyi

**Comment by haozturk** [comment]
Dynamo lock was removed with #684 , so closing this issue.
