### ISSUE TITLE
T1 sites are chosen to be the output site despite out of space

### ISSUE THREAD

**Issue by z4027163** [CMSCompOps/WmAgentScripts#622]
The unified keeps sending WFs to T1 sites (PIC, KIT) despite they have 0 space available. This causes the long time issue that the data are not evenly distributed among the sites.

**Describe the bug**
In the assignor where it decides the output site [1]. If any T1 sites are in the "sites_allowed",  only T1 sites will be considered even they are out of space. If all the T1 sites are out of space, the function [2] will pick the first site in the array, and it ends up with "PIC" usually.

Is picking T1 sites only a policy? I would suggest at least check the remaining quota as well at [3]. 

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/assignor.py#L298-L304
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L2565
[3] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/assignor.py#L298

@sharad1126  @vlimant  Do you know the reason why it was set in this way?

**Comment by vlimant** [comment]
NB. the early assumption in designing some of the rules, assume a well already behaved system situation (S_t) to set the directions for the next time step (S_(t+1)). Once the system exists that assumption (how can a T1 ever get out of disk space if we have dynamic data placement, and people looking, ...) , then things go bad.

as chatted with @drkovalskyi if NonCustodialSites is left empty, nothing will break.

**Comment by sharad1126** [comment]
thanks for the quick updates @vlimant

**Comment by vlimant** [comment]
@z4027163 some level of random order of site with 0 weight should be added in https://github.com/CMSCompOps/WmAgentScripts/blob/1e871728da45f5a7d0c59a9604fc108efa6dea87/utils.py#L2582 , at the very least

**Comment by nsmith-** [comment]
Indeed the main culprit is the loss of dynamo updates to DataOps space usage. But nevertheless it is good to fail safe.

**Comment by haozturk** [comment]
Output data placement was migrated to WMCore, no need this issue anymore.
