### ISSUE TITLE
remaining space monitoring not up to date

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#623]
since the locks are not actively maintained by unified anymore (which BTW would require a full cleanup of the code), this https://cms-unified.web.cern.ch/cms-unified/outofspace.html , https://cms-unified.web.cern.ch/cms-unified/remaining.html and other lock-related info is not up to date. They can be extremely useful when the system has gone bad (#622 for example).

either update https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/remainor.py#L200 to query the locked dataset from reqmgr (@amaltaro @todor-ivanov ) or all such monitoring pages should be thrown away.

**Comment by haozturk** [comment]
Unified does not need this information as it does not deal with data placement anymore. So, closing this issue.
