### ISSUE TITLE
HEPCloud assignments don't run

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#637]
**Impact of the bug**
In assignor, we check if we can assign wfs to only HEP Cloud and check for NERSC and then assign them only for NERSC. @amaltaro @todor-ivanov but I see these wfs cannot run. Should this be removed from unified code?

**Describe the bug**
On checking https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L2685 and https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L6548, unified uses https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/assignor.py#L417 to assign wfs to team hepcloud but I don't think we are running any such agents these days. There are some wfs stuck in the system since a long time: https://cmsweb.cern.ch/reqmgr2/data/request?mask=RequestStatus&status=assigned&status=acquired&status=running-open&status=running-closed&team=hepcloud

@amaltaro @todor-ivanov should this be removed from unified code or are there any plans to run them in the future? Also, for now these ~40 wfs should be cloned right?

**How to reproduce it**
explained above. 

**Expected behavior**
should run at NERSC through the hep cloud agent. 

**Additional context and error message**
@z4027163 @haozturk please have a look. @scarletnorberg fyi

**Comment by amaltaro** [comment]
I would keep the code around for a little longer. Just make sure to keep it disabled for now.

**Comment by sharad1126** [comment]
@amaltaro so you mean to comment out the code for now and clone all the wfs stuck in hepcloud right?

**Comment by amaltaro** [comment]
Yes, that's what I would do.

**Comment by sharad1126** [comment]
@haozturk please make a file with the list of wfs mentioned above. Let's comment out the code in assignor and then kill and clone those wfs.
