### ISSUE TITLE
Migration of output data placement functionality from Unified to WMCore

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#646]
This issue is a starting point to identify and migrate all the parts related to output data placement in Unified. Here are the items that I've identified in this regard.

1. Unified makes a replica request for RelVals through Phedex based on specific rules. Related code:
    1. https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L499-L532
    2. https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L5173-L5180
2. Unified handles the placement of particular data tiers through DDM. These data tiers are determined according to campaign configuration ([An example](https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json#L1425)) and [Unified Configuration](https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L226-L233) (`tiers_to_DDM` and `tiers_no_DDM`). Related code:
     1. https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L533-L595
     2. https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L544-L592
3. Unified sets the status of datasets to VALID and announces them. It stores the status (successful or not) of the output data placement in the `results` list and uses this list in the announcement. This list is also populated by `makeReplicaRequest` and `pass_to_dynamo`  functions which are planned to be removed. That's why we also need to revisit this part of the code. Related links:
     1. Announcement check using `results` list: https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L620-L631
     2. https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L586
     3. https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L526

Please keep in mind that this issue might not cover all the points which needs to be revisited in the migration. But, rather, it aims to start the discussion. @z4027163 @amaltaro FYI

**Comment by vlimant** [comment]
FYI https://github.com/dmwm/WMCore/issues/8921 https://github.com/dmwm/WMCore/issues/9836

**Comment by amaltaro** [comment]
Thanks Hasan. I noticed this code:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1012

also has plenty of logic around the custodial data placement. I just failed to find where the transfer request gets made.

**Comment by vlimant** [comment]
here https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L335

**Comment by vlimant** [comment]
checkor == https://github.com/dmwm/WMCore/issues/8914

**Comment by amaltaro** [comment]
Perfect, thanks Jean-Roch!

**Comment by haozturk** [comment]
As the migration's completed with #653 , closing this issue.
