### ISSUE TITLE
Phedex2Rucio transition: the fate of the stuckor module

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#662]
**Impact of the new feature**
Depends on the chosen alternative

**Is your feature request related to a problem? Please describe.**
The stuckor module is responsible for checking the progress of dataset transfers and creating a report for this. It performs this by making some Phedex queries [1] and tries to determine if there is a lag in the transfer. It considers the `transfer_timeout` and `transfer_lowrate` thresholds in Unified configuration [2] e.g. if the transfer takes more than 7 days, label it as stuck. In the Rucio transition phase, we should decide the fate of this module.

**Describe the solution you'd like**
I see three options:
1. Stop running this module. 
2. Keep running the module after converting Phedex functions into Rucio equivalents.
3. Discuss the functionality with WMCore team and see if there is a similar functionality there.

As Unified does not have a data placement responsibility anymore, implementation of such functionality seems out of the scope of Unified. In my opinion, if there is a stuck transfer this should be somehow monitored/detected either by Unified or WMCore, so that an action could be taken to solve the issue.  @amaltaro @todor-ivanov do you have a similar mechanism in WMCore which checks the stuck transfers?

PS: I've checked the logs of this module and I see that it has not reported any incident in the last month, although we have witnessed some stuck transfers.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L3392-L3483
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L277-L284

**Describe alternatives you've considered**
Described above.

**Additional context**
@drkovalskyi @z4027163 @amaltaro @todor-ivanov Any comment is very much appreciated.

**Comment by amaltaro** [comment]
I vote for:
> Stop running this module.

and let the data management team take care of the... data management. Of course you need to specify the requirements and work with them such that it gets properly implemented. They might even have such stuckness monitoring already in Rucio...

**Comment by todor-ivanov** [comment]
+1

I would vote for stopping it too. Especially since the information provided by the module is not about to be used anywhere in Unified itslef once we move to Rucio.

**Comment by drkovalskyi** [comment]
I agree with Alan. While it's not always working well this way, ultimately it's not PnR responsibility to take care of the transfers and associated issues. Saying that, we still need to monitor for such issues since we are ultimately responsible for request processing and should be able to see that we have issues with stuck workflows and report these issues to the transfer team. Since we cannot keep the old functionality I would stop the module and get back to this topic later when we see how much we lack in monitoring with the new setup and then decide what to do.

**Comment by haozturk** [comment]
Thanks everyone for your comments. I also agree with the consensus here. We will stop running the module and evaluate how much we lack without it in the upcoming weeks/months in terms of workflow management.
