### ISSUE TITLE
Phedex2Rucio transition: disable dataset presence and block fraction info in the error reports

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#669]
**Impact of the new feature**
For the operator, it will take more time to check the dataset presence with this new feature in necessary conditions.

**Is your feature request related to a problem? Please describe.**
Unified reports the location of each input and outputdataset and their fraction at that location in the error reports. i.e.
https://cms-unified.web.cern.ch/cms-unified/report/haozturk_r-0-Run2018C-v1_SingleMuon_ForPixelALCARECO_UL2018_200817_123854_9761
```
Reads in primary
/SingleMuon/Run2018C-v1/RAW (events/lumi ~3935)

Available 2.00 (>1 more than one copy, <1 not in full on disk)

    T1_RU_JINR_Disk : 46.11 %
    T1_UK_RAL_Disk : 20.93 %
    T1_US_FNAL_Disk : 7.16 %
    T2_BE_IIHE : 33.21 %
    T2_CH_CSCS : 6.85 %
    T2_ES_CIEMAT : 23.09 %
    T2_ES_IFCA : 6.26 %
    T2_FR_GRIF_IRFU : 2.74 %
    T2_IN_TIFR : 2.05 %
    T2_IT_Bari : 12.54 %
    T2_IT_Pisa : 13.05 %
    T2_UK_London_Brunel : 6.24 %
    T2_UK_London_IC : 13.68 %
    T2_US_Vanderbilt : 6.95 %


Produces
/SingleMuon/Run2018C-SiPixelCalSingleMuon-ForPixelALCARECO_UL2018-v1/ALCARECO (events/lumi ~ 3968)

    T1_DE_KIT_Disk : 3.20 %
    T1_ES_PIC_Disk : 100.00 %
    T1_FR_CCIN2P3_Disk : 0.53 %
    T1_IT_CNAF_Disk : 1.44 %
    T1_RU_JINR_Disk : 33.85 %
    T1_UK_RAL_Disk : 10.85 %
    T1_US_FNAL_Disk : 5.53 %
    T2_BE_IIHE : 13.13 %
    T2_CH_CERN : 0.02 %
    T2_CH_CSCS : 0.77 %
    T2_ES_CIEMAT : 2.54 %
    T2_FR_GRIF_LLR : 2.35 %
    T2_HU_Budapest : 100.00 %
    T2_IN_TIFR : 0.04 %
    T2_RU_JINR : 0.92 %
    T2_UK_London_Brunel : 6.14 %
    T2_UK_London_IC : 8.84 %
    T2_UK_SGrid_RALPP : 1.57 %
    T2_US_Caltech : 1.13 %
    T2_US_Florida : 0.62 %
    T2_US_MIT : 0.55 %
    T2_US_Nebraska : 0.27 %
    T2_US_Purdue : 0.24 %
    T2_US_UCSD : 0.23 %
    T2_US_Vanderbilt : 4.16 %
    T2_US_Wisconsin : 0.23 %
```
It uses Phedex dependant `getDatasetBlocksFraction` and `getDatasetPresence` functions [1] to prepare this report. In the phedex to rucio transition, we need to decide the fate of this functionality.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/showError.py#L358-L397

**Describe the solution you'd like**
This information is not critical for the workflow management and the same information can be reached using Phedex web interface and probably using Rucio web interface in the future (not sure). Currently, we can disable this functionality. If we lack without this report, we can re-implement it in the future with the Rucio equivalent.

The new report will look like:
```
Reads in primary
/SingleMuon/Run2018C-v1/RAW (events/lumi ~3935)

Produces
/SingleMuon/Run2018C-SiPixelCalSingleMuon-ForPixelALCARECO_UL2018-v1/ALCARECO (events/lumi ~ 3968)
```

**Describe alternatives you've considered**
We should either remove it or re-implement it with the Rucio alternative. Due to time pressure, it is better to disable it now, and re-implement it in the future if necessary.

@z4027163  FYI

**Comment by vlimant** [comment]
let's have a rucio GH issue linked to this if the feature does not exist yet.
