### ISSUE TITLE
Phedex2Rucio transition: Checking the location of the outputs to create harvesting workflows

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#670]
**Impact of the new feature**
Harvesting workflows might be affected depending on the chosen alternative.

**Is your feature request related to a problem? Please describe.**
Unified closor module checks the location of each output dataset using Phedex dependent `getDatasetPresence` function [1] and if the necessary conditions are met, it creates a harvesting workflow and assigns the workflow to the site where the DQMIO output is 100% available. [2,3] Since this function will not work due to Phedex to Rucio transition anymore, we might need a replacement.

An example for harvesting from the logs:
```
./2020-09-30_03:08:54.log:4183:cmsunified_HARVEST-Run2016B-v2_DoubleEG_21Feb2020_UL2016_HIPM_rsb_200930_032143_8807 was created at announcement of /DoubleEG/Run2016B-21Feb2020_UL2016_HIPM_rsb-v1/DQMIO in pdmvserv_Run2016B-v2_DoubleEG_21Feb2020_UL2016_HIPM_rsb_200922_061914_5265, and assigned

```

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L444
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L470-L472
[3] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L24-L138

**Describe the solution you'd like**
I do not know the purpose and the logic behind this harvesting functionality. If this is necessary, then we need a Rucio compatible replacement for this function. If not, we can remove this feature.

**Describe alternatives you've considered**
Described above

**Additional context**
@z4027163 @drkovalskyi @amaltaro @todor-ivanov Any comment/suggestion is very much appreciated.

**Comment by amaltaro** [comment]
@haozturk Hasan, starting in the next CMSWEB production deployment (next Tuesday), input dataset for harvesting workflows will all be placed under a single location (in full).

So, I'd suggest to let Unified create and assign such workflows to a handful of sites (CERN, FNAL, etc). MSTransferor would then pick one of those sites as a destination for the input DQM/DQMIO dataset.

Once we implement and deploy this:
https://github.com/dmwm/WMCore/issues/9958

we could then just pick one site (like T2_CH_CERN) and always assign such harvesting workflows to the same location.

**Comment by haozturk** [comment]
@amaltaro Then we can create a new parameter in Unified Configuration something like `sites_for_DQM` and assign all harvesting workflows to those sites. Does that make sense?

And, it is not very clear for me which sites to include in this list until the new input data placement logic is implemented in WMCore. Do we have a site requirement for such workflows?

**Comment by nsmith-** [comment]
I would choose the sites to run the harvesting workflow based on where the output usually resides. I imagine good choices would be CERN and FNAL. I believe both the input and output datasets for these workflows should be quite small, so the transfer overhead (vs. assigning harvesting where the inputs already are, as I assume is currently done) isn't such a big deal. Out of curiosity, in the current implementation, what happens if the DQMIO inputs are nowhere 100% present?

**Comment by haozturk** [comment]
I would also choose to run the harvesting workflow where the input is to avoid the transfer overhead even if it is negligible. But, since, currently there is no Rucio compatible function in Unified to check a dataset's location, for now we can assign them to some candidate sites such as CERN and FNAL as you suggested, in order to meet the deadline. Later we can switch to the other alternative, if we agree that it's a better option.

About your question @nsmith- , it does not assign the workflow if the DQMIO input is nowhere 100% present: https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L115-L119

**Comment by amaltaro** [comment]
> I would choose the sites to run the harvesting workflow based on where the output usually resides.

That's the best option. However, it would require either:
a) DQMHarvest workflow creation to be done within WMCore; or
b) Unified performing output dataset data location, and properly assigning DQMHarvest workflows.

We plan to have a better support for DQMHarvest in WMCore, but it might still take many months until we get there.

So, hardwiring a few sites to execute those workflows look a reasonable interim step.
Hasan, if you create a new unified parameter, please make it more meaningful such as `sites_for_DQMHarvest`, or something like that.

**Comment by haozturk** [comment]
Sure Alan, `sites_for_DQMHarvest` sounds like a meaningful name. Then I am moving forward with a PR to hardwire a few sites for this purpose.
