### ISSUE TITLE
Phedex2Rucio transition: checking input locations for the overflow mechanism

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#673]
**Impact of the new feature**
Overflow mechanism

**Is your feature request related to a problem? Please describe.**
As we discussed in the last PnR dev meeting, Unified `equalizor` module manages the overflow mechanism. It checks the location of primary and secondary input datasets [2,3,4,5,6] using the Phedex dependent`getDatasetPresence` function [1] and it overrides the sitewhitelist of the workflows considering the location information. With the Rucio transition, this function will deprecate and it should either be removed or re-implemented with Rucio alternative.

Additionally,  the same module uses `getClassicalPUOverflow` function [7] to to get the `PhedexNodeNames` of each block and again uses this information to determine the sites with "enough" input fraction. This information is fetched by the active agents [8] and most probably this `PhedexNodeNames` field is going to change and we should find a replacement for this.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L4229
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/equalizor.py#L623
[3] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/equalizor.py#L637
[4] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/equalizor.py#L683
[5] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/equalizor.py#L731
[6] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/equalizor.py#L877
[7] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L6997
[8] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L6977
**Describe the solution you'd like**
We should implement the Rucio equivalent of the getDatasetPresence function if we want to support the overflow functionality.

**Describe alternatives you've considered**
Due to time pressure, if we cannot manage to re-implement these functions, we can stop the overflow mechanism until we support it again. 

**Additional context**
@z4027163 @drkovalskyi @amaltaro @todor-ivanov  FYI

**Comment by nsmith-** [comment]
Shouldn't the allowed site list imply the data locations? All valid data locations would already be there I suspect, and any non-production-owned data locations should not be considered as they might disappear at any moment. We went through some work to make sure that only `wmcore_transferor`-owned rules would be used for data location. For AAA-based overflow, the mapping site->neighbors can just use the existing allowed site list and expand to well-connected neighbors of the existing sites.

**Comment by haozturk** [comment]
The allowed sitelist includes the input locations only for workflows reading classical mixing by considering the campaign configuration. e.g. https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json#L41 For others, Unified does not check the input locations while composing the sitewhitelist.

Currently, for AAA-based overflow, it extends the sitelist to the well-connected neighbors of the sites containing the input. We can implement your approach @nsmith- but what would be difference between these two approaches?

**Comment by nsmith-** [comment]
The difference would be that then unified would not need to query the data locations, if I understand correctly.
