### ISSUE TITLE
Phedex2Rucio transition: monitoring of stuck workflows in the GQ module

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#675]
**Impact of the new feature**
Monitoring of workflows which are stuck due to not intersecting input location and sitewhitelist

**Is your feature request related to a problem? Please describe.**
Unified `GQ` module checks necessary files for ACDCs [1] and if the file cannot be read with the current configuration and the sitewhitelist, it creates a warning for us. So that, PnR could re-submit the ACDC with the correct configuration. e.g.

```
using cmsunified_ACDC3_Run2017H-v1_LowEGJet_09Aug2019_UL2017_LowPU_200813_104655_1043
5 files in ACDC doc
ACDC reads /LowEGJet/Run2017H-v1/RAW
File /store/data/Run2017H/LowEGJet/RAW/v1/000/307/076/00000/42E82040-F5D1-E711-85E1-02163E01A509.root is at T1_US_FNAL_Buffer,T0_CH_CERN_Export,T1_US_FNAL_MSS,T1_DE_KIT_Disk,T0_CH_CERN_MSS,T2_IT_Pisa while asked to run at T2_US_UCSD
Should have [u'T2_IT_Pisa'] also in the whitelist, or have xrootd enabled
```

GQ uses the phedex dependent `getDatasetFileLocations` [2] for this purpose.

It also performs a similar check in block level using another Phedex dependent function called `getDatasetBlockAndSite`[3] e.g.

```
Block /SingleMuon/Run2017B-v1/RAW#52268970-6927-11e7-9282-001e67ac06a0 is at T0_CH_CERN_Export,T0_CH_CERN_MSS,T1_FR_CCIN2P3_Buffer,T1_FR_CCIN2P3_MSS,T2_PT_NCG_Lisbon while asked to run at T1_DE_KIT_Disk,T1_ES_PIC_Disk,T1_FR_CCIN2P3_Disk,T1_IT_CNAF_Disk,T1_RU_JINR_Disk,T1_UK_RAL_Disk,T1_US_FNAL_Disk,T2_BE_IIHE,T2_BE_UCL,T2_BR_SPRACE,T2_CH_CERN,T2_CH_CERNBOX,T2_CH_CSCS,T2_CN_Beijing,T2_DE_DESY,T2_DE_RWTH,T2_ES_CIEMAT,T2_FR_CCIN2P3,T2_FR_GRIF_IRFU,T2_FR_GRIF_LLR,T2_FR_IPHC,T2_HU_Budapest,T2_IT_Bari,T2_IT_Legnaro,T2_IT_Pisa,T2_IT_Rome,T2_KR_KISTI,T2_PL_Swierk,T2_RU_JINR,T2_TW_NCHC,T2_UA_KIPT,T2_UK_London_Brunel,T2_UK_London_IC,T2_UK_SGrid_Bristol,T2_UK_SGrid_RALPP,T2_US_Caltech,T2_US_MIT,T2_US_Nebraska,T2_US_Purdue,T2_US_UCSD,T2_US_Vanderbilt,T2_US_Wisconsin,T3_US_FNALLPC,T3_US_Vanderbilt_EC2
```

We should decide on the fate of this functionality with the Phedex2Rucio transition.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/GQ.py#L179
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L3659
[3] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L4195

**Describe the solution you'd like**
From the operational perspective, it is critical to monitor these stuck workflows. Therefore, I believe this functionality should be re-implemented with the Rucio alternative.

**Describe alternatives you've considered**
With a similar approach to the other issues, we can stop monitoring of these issues and rely on the MSTransferor.

**Additional context**
@z4027163 @drkovalskyi @amaltaro @todor-ivanov  FYI

**Comment by amaltaro** [comment]
This functionality has been implemented years ago:
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/stuckElementsInfo

**Comment by nsmith-** [comment]
Is this site part of either the WM or DM operator checklist? If not, we should document it. How do I interpret the missing inputs when they are in unmerged space? What actions should be taken, and by which operator, to correct these cases?

**Comment by haozturk** [comment]
@amaltaro If I am not wrong, GQ module catches some stuck workflows which are not caught by https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/stuckElementsInfo For instance:
```
acdc doc input /acdc/cmsunified_ACDC0_task_EXO-RunIISummer15wmLHEGS-07470__v1_T_200930_123650_4812/:pdmvserv_task_EXO-RunIISummer15wmLHEGS-07470__v1_T_200304_160541_158:EXO-RunIISummer15wmLHEGS-07470_0:EXO-RunIISummer16DR80Premix-15339_0:EXO-RunIISummer16DR80Premix-15339_1/0/2
using pdmvserv_task_EXO-RunIISummer15wmLHEGS-07470__v1_T_200304_160541_158
24 files in ACDC doc
original workflow does not read from any dataset
Should have [u'T2_US_Florida'] also in the whitelist, or have xrootd enabled
```
This is the stuck workflow: https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EXO-RunIISummer15wmLHEGS-07470 and it is not listed in the stuckElementsInfo page.

If this functionality is fully supported by WMCore, I agree that it could be removed from Unified.

**Comment by haozturk** [comment]
@nsmith- It's in the WM operator checklist: https://twiki.cern.ch/twiki/bin/view/CMS/CompOpsPRWorkflowManger#Checking_workflow_info_in_the_gl 
For checking the missing inputs in unmerged space, I follow this wiki page: https://github.com/CMSCompOps/WmAgentScripts/wiki/MC-Data-and-unmerged-file-checks
I think documentation needs to be improved. I will check that.
