### ISSUE TITLE
Stuck workflows in assigned state due to wrong top-level sitewhitelists of the campaigns

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#686]
**Impact of the bug**
Transition from assigned to acquired

**Describe the bug**
For some campaigns which contain minbias PU, there are two sitewhitelists defined: The inner sitewhitelist shows the location of the minbias PU and MSTransferor looks at this parameter while moving a request to `staging`. Unified checks the outer/top-level sitewhitelist to restrict the sitewhitelist. For some campaigns, the outer sitewhitelist does not include the site hosting the PU and workflows belonging to this campaign get stuck in `assigned` state, since MSTransferor realizes that the site hosting the PU location is not in the sitewhitelist.  

**How to reproduce it**
For instance, the following workflow [1], is assigned to Florida, but the PU is at JINR which is also specified by campaign configuration [2], but the JINR is not in the top-level sitewhitelist [3] and therefore workflow gets stuck in assigned.

[1] https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_TSG-Phase2HLTTDRWinter20wmLHEGS-00082__v1_T_201007_215238_2381
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json#L352
[3] https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json#L345

**Expected behavior**
Best way would be to assign the workflows only to the sites hosting the PU. But, as a fast solution, we can remove all the top-level sitewhitelists from the campaigns and giving workflows a wider sitewhitelist including the site hosting the PU.

**Additional context and error message**
@scarletnorberg  @z4027163  @amaltaro  @todor-ivanov  FYI

**Comment by scarletnorberg** [comment]
Updating the topper part of the white list for minbais campaigns with this PR: https://github.com/CMSCompOps/WmAgentScripts/pull/688

**Comment by haozturk** [comment]
Thanks @scarletnorberg . Issue seems to be fixed, so closing.
