### ISSUE TITLE
Legacy code in checkor module

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#691]
**Impact of the bug**
Readability of the code + Proper execution of the module

**Describe the bug**
Although all the output subscription functions were removed from the checkor module, there are still redundant pieces of code which are related to output data placement logic. (e.g. there are still some logic here [1] about custodial copies although there is no action taken). Plus, there is still one redundant function [2] talking to Phedex to get the node names [3], which should also be removed immediately.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1201
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1268
[3] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L1925

**Expected behavior**
Code should be cleaned and all redundant code pieces should be removed.

**Additional context and error message**
@z4027163  FYI

**Comment by z4027163** [comment]
@haozturk  Same as the function checkTransferStatus. We can straight up delete them. Or do we still want to check the transfer status from rucio ourselves or we rely on wmcore?
