### ISSUE TITLE
HEPCloud sites are restricted due to missing core and memory information source

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#709]
**Impact of the bug**
HEPCloud site utilization

**Describe the bug**
Unified assignment logic checks the maximum number of cores and maximum memory status for each site and if one site cannot satisfy at least one of these constraints according to the request core and memory requirements, then it is restricted in the whitelist of that request [1]. Unified fetches the site core and memory information from `gwmsmon` [2,3] and HEPCloud sites are not included in this data source. Therefore, they are automatically restricted for every workflow.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L7427-L7440
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L2318
[3] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L1776

**How to reproduce it**
Looking at the [assignor logs](https://cms-unified.web.cern.ch/cms-unified/logs/assignor/). e.g.
```
cmsunified_task_PPD-RunIILowPUAutumn18GS-00002__v1_T_201107_155203_7294 to be assigned
Include HEPCloud in the sitewhitelist of  cmsunified_task_PPD-RunIILowPUAutumn18GS-00002__v1_T_201107_155203_7294
Initially allow [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BE_UCL', u'T2_BR_UERJ', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_CN_Beijing', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_EE_Estonia', u'T2_ES_CIEMAT', u'T2_ES_IFCA', u'T2_FI_HIP', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_IRFU', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_GR_Ioannina', u'T2_HU_Budapest', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_IT_Pisa', u'T2_IT_Rome', u'T2_KR_KISTI', u'T2_PT_NCG_Lisbon', u'T2_RU_IHEP', u'T2_RU_INR', u'T2_RU_JINR', u'T2_TR_METU', u'T2_TW_NCHC', u'T2_UA_KIPT', u'T2_UK_London_IC', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_UCSD', u'T2_US_Vanderbilt', u'T2_US_Wisconsin', u'T3_US_NERSC', u'T3_US_PSC', u'T3_US_SDSC', u'T3_US_TACC']
[INFO] Sites allowing 14700 MB and 8 core are
[INFO] Sites ready for multicore: [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BE_UCL', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_CN_Beijing', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_EE_Estonia', u'T2_ES_CIEMAT', u'T2_ES_IFCA', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_IRFU', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_HU_Budapest', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_IT_Pisa', u'T2_IT_Rome', u'T2_KR_KISTI', u'T2_PT_NCG_Lisbon', u'T2_RU_IHEP', u'T2_RU_JINR', u'T2_TW_NCHC', u'T2_UA_KIPT', u'T2_UK_London_IC', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_UCSD', u'T2_US_Vanderbilt', u'T2_US_Wisconsin', u'T3_CH_CERN_HelixNebula', u'T3_UK_SGrid_Oxford', u'T3_US_Baylor', u'T3_US_Colorado', u'T3_US_NERSC', u'T3_US_OSG', u'T3_US_SDSC']
Removing sites due to 14700 MB and 8 core(s) requirements: [u'T2_BR_UERJ', u'T2_FI_HIP', u'T2_GR_Ioannina', u'T2_RU_INR', u'T2_TR_METU', u'T3_US_NERSC', u'T3_US_PSC', u'T3_US_SDSC', u'T3_US_TACC']
```
Run the following lines to see what is fetched from `gwmsmon` (in Unified environment)
```
from utils import global_SI
SI = global_SI()
SI.sites_memory
```
Here is an example:
[assignor-sites-memory.txt](https://github.com/CMSCompOps/WmAgentScripts/files/5506521/assignor-sites-memory.txt)

**Expected behavior**
HEPCloud sites should be included in the whitelist of StepChain requests if they satisfy the core and memory requirements. We should either fix `gwmsmon` data source to include HEPCloud info, or get this information from somewhere else.

**Additional context and error message**
@drkovalskyi @z4027163  FYI

**Comment by drkovalskyi** [comment]
gwmsmon is not supported as a service, so we should not rely on it as a source of information for Unified. I also don't think such restrictions are relevant for StepChain requests, i.e. I would leave matching to WMCore and HTCondor. If you want to keep the old design, we need to switch to supported services such as monit or gwms factory. I suspect in both cases the it will require extra work and I'm not see any benefits to justify it.

**Comment by haozturk** [comment]
Thanks @drkovalskyi this was helpful. @amaltaro @todor-ivanov while preparing the sitewhitelist, if we stop checking site core and memory capacity to match request requirements, can WMCore handle this matching? Or do you know if HTCondor has such an utility?

**Comment by drkovalskyi** [comment]
HTCondor is the final matcher and it won't allow jobs to run that won't match. The only issue that I can see is that if we run a TaskChain request on a site that cannot match all tasks, the workflow can get stuck. I think WMCore should check for such issues, not Unified, since WMCore is the one that creates the jobs. Anyway, for StepChain it should be an issue.
