### ISSUE TITLE
Test needed for some T2 sites for goodAAA

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#725]
**Impact of the bug**
T2 site utilization

**Describe the bug**
With #642 we tested available T2 sites for goodAAA and added successful sites to the list. There are some sites which was not available during the test and we could not test them. These sites are:
```
T2_AT_Vienna,T2_BR_UERJ,T2_ES_IFCA,T2_FI_HIP,T2_PK_NCP,T2_PL_Warsaw,T2_PT_NCG_Lisbon,T2_RU_ITEP,T2_UA_KIPT
```

**How to reproduce it**
Check the utilization in these sites

**Expected behavior**
After running a test workflow there, we should decide if these sites are suitable for goodAAA or not.

**Additional context and error message**
@z4027163  FYI

**Comment by haozturk** [comment]
Note that the following sites are in drain or not available as of today, therefore we will not be able to test them in this test, either.
```
T2_PK_NCP,T2_PL_Warsaw,T2_PT_NCG_Lisbon,T2_RU_ITEP
```

**Comment by haozturk** [comment]
Here is the test workflow: https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_TEST-BACKFILL-task_EGM-Run3Summer19wmLHEGS-00003__v1_T_201123_131347_3589

**Comment by haozturk** [comment]
Current status:
```
T2_UA_KIPT: success:110, submitted-running:22, retry:10, pending:4087, first:4099,
T2_AT_Vienna: submitted-running:88, retry:10, pending:485, first:563, queued-retry:1, success:541,
T2_ES_IFCA: submitted-running:202, retry:16, pending:1158, first:1344, queued-retry:1, success:867,
T2_BR_UERJ: success:1, submitted-retry:6, pending:208, first:202,
T2_FI_HIP: submitted-retry:9, pending:314, first:305
```

**Comment by haozturk** [comment]
Current status:
```
T2_UA_KIPT: success:988, submitted-running:36, retry:98, pending:165, first:103, queued-retry:2389,
T2_AT_Vienna: success:3502, submitted-running:126, retry:175, pending:350, first:301, cooloff-job:1,
T2_BR_UERJ: success:1, submitted-retry:72, pending:140, first:68,
T2_ES_IFCA: success:3441, submitted-retry:3, pending:93, first:90,
T2_FI_HIP: submitted-retry:2, pending:2
```

**Comment by haozturk** [comment]
Current status:
```
T2_UA_KIPT: success:1264, transition:149, submitted-retry:109, pending:162, first:96, running:43, failure-exception:1, queued-retry:2164,
T2_AT_Vienna: success:3933, submitted-retry:10, pending:242, first:232, transition:2,
T2_BR_UERJ: success:1, submitted-retry:72, pending:140, first:68, queued-retry:3,
T2_ES_IFCA: success:3441, submitted-retry:3, pending:92, first:89, 
```

**Comment by haozturk** [comment]
According to latest results, I would say `T2_AT_Vienna` and `T2_ES_IFCA` are good to be included in the list. For `T2_UA_KIPT` although the number of successful jobs are high, number of retries makes me suspicious about the site. For `T2_BR_UERJ`, there is not enough jobs to conclude. What do you think @z4027163 ?

**Comment by akurov** [comment]
Hi,

According to this link

https://monit-grafana.cern.ch/d/gZG0DDgWz/user-cfarizapo-testcondorproductionfilter?orgId=11&from=now-7d&to=now&var-type=production&var-site=T2_UA_KIPT

those 2164 queued-retry jobs even not started on T2_UA_KIPT site and there is no such large number of failed jobs.

Thanks,
Alexey

**Comment by haozturk** [comment]
Hi @akurov this is the highest priority workflow running at KIPT. I do not understand why the jobs are waiting in Pending for so long. Do you have a clue?

**Comment by akurov** [comment]
Hi @haozturk,

I see that analysis jobs preempting production jobs

https://monit-grafana.cern.ch/d/o3dI49GMz/cms-job-monitoring-12m?orgId=11&var-group_by=Type&var-Site=T2_UA_KIPT&from=now-2d&to=now

We have no problems with running HC test jobs from highprio.cmsdataops@cms AccountingGroup but for unknown reason production.cmsdataops@cms can be preempted by analysis. I don't know can we change this in some way.

**Comment by haozturk** [comment]
I understand, thanks for the information @akurov I do not know how the analysis and production jobs are scheduled with respect to each other, either. 
@amaltaro @drkovalskyi  do you know this mechanism or someone who knows? We simply cannot understand why the jobs of a 400k production workflow are waiting for so long due to analysis jobs at `T2_UA_KIPT` site. Is this a priority issue or something else?
@4quarks FYI

**Comment by drkovalskyi** [comment]
The priority are adjusted such that all T2 sites on average have 50%/50% production/analysis. Each individual site may deviate from this ratio. Looking at last week fairshare of the site (https://cms-gwmsmon.cern.ch/prodview/T2_UA_KIPT) I don't see anything unusual, i.e. it typically runs fairly balanced mix of production and analysis jobs. I would suggest to wait a bit.

**Comment by akurov** [comment]
Hi all,
I found Debug information "Scheduler is overloaded" on site
https://cms-gwmsmon.cern.ch/prodview/haozturk_TEST-BACKFILL-task_EGM-Run3Summer19wmLHEGS-00003__v1_T_201123_131347_3589
Maybe this can explain why no running jobs.

**Comment by haozturk** [comment]
Hi @akurov I do not know how to read this debug information. Does this mean that the site cannot handle when we overload it with relatively big workflows?

Number of successful jobs is increasing, though:
```
T2_UA_KIPT: success:1444, submitted-running:8, retry:54, pending:146, first:100, queued-retry:1695, failure-exception:1,
T2_AT_Vienna: success:3933, transition:1, queued-retry:115, submitted-retry:3, pending:106, first:103, cooloff-job:4,
T2_BR_UERJ: success:1, submitted-retry:60, pending:128, first:68, transition:1, queued-retry:14,
T2_ES_IFCA: success:3541, transition:2, submitted-running:89, retry:427, pending:662, first:324, queued-retry:13,
T2_FI_HIP: submitted-retry:142, pending:206, first:64, 
```

**Comment by akurov** [comment]
Hi @haozturk, 
I am not sure but looks like  "Scheduler is overloaded" this is more about submitting problem on CERN side (vocms0250.cern.ch) than problem on our site.
When your workflow started it was running fine, using more than half of available cores (despite the fact that we have fewer cores than IFCA have)
https://monit-grafana.cern.ch/d/000000628/cms-job-monitoring-es-agg-data-official?viewPanel=15&orgId=11&refresh=15m&var-group_by=CMS_JobType&var-Tier=All&var-CMS_WMTool=All&var-CMS_SubmissionTool=All&var-CMS_CampaignType=All&var-Site=T2_UA_KIPT&var-Type=All&var-CMS_JobType=All&var-CMSPrimaryDataTier=All&var-binning=1h&from=now-7d&to=now-1h

**Comment by drkovalskyi** [comment]
I see production jobs running, but clearly priority is not respected. Most likely it's caused by fragmentation of the slots available at the site. It will take a while to get 8-core slots for the test workflow.

**Comment by haozturk** [comment]
Current status:
```
T2_UA_KIPT: success:1794, transition:1, submitted-running:9, retry:74, pending:134, first:69, failure-exception:3, queued-retry:676, cooloff-job:1,
T2_AT_Vienna: success:3933,
T2_BR_UERJ: success:1, submitted-retry:58, pending:116, first:57, failure-exception:1, transition:1, cooloff-job:2, queued-retry:10,
T2_ES_IFCA: success:5434, failure-exception:37, transition:4, submitted-running:100, retry:359, pending:635, first:376, cooloff-job:4, queued-retry:23,
T2_FI_HIP: submitted-retry:98, pending:192, first:94, failure-exception:35, cooloff-job:2, queued-retry:3
```
I see that retried jobs are being successful at `T2_UA_KIPT`, so the following sites are going to be added to the goodAAA list:
- T2_UA_KIPT
- T2_AT_Vienna
- T2_ES_IFCA

`T2_FI_HIP` has many failures and no success at all. So according to this test, it is not able to run workflows with PREMIX libraries

`T2_BR_UERJ` has many pending and retried jobs. So, there is not enough information to conclude for this site. This site has no space in its disk for over 3 weeks [1]. Maybe this is the reason for this problem.

@akurov  let's monitor the failure rate for `T2_UA_KIPT`. Please let us know if you see something wrong for production jobs.

[1] https://cmsweb.cern.ch/ms-transferor/data/status?detail=true

@dpiparo FYI

**Comment by haozturk** [comment]
I will close this issue with the following result:
- `T2_UA_KIPT` , `T2_AT_Vienna`, `T2_ES_IFCA` are added to goodAAA due to their success.
- `T2_FI_HIP` is unsuccessful according to this test and it will not be in the list until a further test proves the opposite.
- `T2_BR_UERJ` - Not enough data to conclude
- `T2_PK_NCP` , `T2_PL_Warsaw` , `T2_PT_NCG_Lisbon` , `T2_RU_ITEP` were not available during this test and therefore they should be tested in the future.
