### ISSUE TITLE
Get a baseline code for the new filtering and automation panel

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#765]
**Impact of the new feature**
Management of resubmissions

**Is your feature request related to a problem? Please describe.**
Motivation can be found at #731 

**Describe the solution you'd like**
#731 describes our end goal. As a first step of this goal, we need a `Workflow` class which gives us all the information that we need for the filtering and automation panel. 

Our guides would be:
1. https://github.com/CMSCompOps/WorkflowWebTools/blob/master/workflowwebtools/workflowinfo.py
2. https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L6470

**Describe alternatives you've considered**
Instead of creating a new baseline code, we can use the already implemented ones whose links are given above. But, I'd prefer writing a new one by consulting them.

**Additional context**
@hbakhshi FYI

**Comment by hbakhshi** [comment]
Here is the database schema of the workflow model that was implemented in OSDroid. This can also be used as a guideline.
[osdroid-db.pdf](https://github.com/CMSCompOps/WmAgentScripts/files/5859727/osdroid-db.pdf)
