### ISSUE TITLE
Blacklisting T2_CH_CERN_HLT from several campaigns due to missing PU samples at CERN

### ISSUE THREAD

**Issue by scarletnorberg** [CMSCompOps/WmAgentScripts#769]
Already done for RunIIFall17DigiPremix, RunIIAutumn18DigiPremix, RunIISummer16DigiPremix campaigns.
Need to keep track of for the future campaigns opened make sure PU is at CERN or blacklist CERNHLT.
Future: this is going to be managed in wmCore here is a link to the doc https://docs.google.com/document/d/1L_p7Dm3K7bvgW8lugq6-RV2qex5uptbKxl2DW5hFeNo/edit that talks about this addition.
When this happens we should be able to remove the blacklist assuming that the method which should be done is to check the site of the neutrino sample as they move to wmCore and blacklist CERNHLT if the neutrino sample is not found there.

Pileup is going to be difficult because there is probably going to be loops inside loops.

**Comment by haozturk** [comment]
After many investigations and trials, it turned out that site blacklisting does not work in WMCore for Taskchains - it only work for StepChain and ReRecos. So the solution is to blacklist `T2_CH_CERN` as well for those campaigns.

**Comment by amaltaro** [comment]
Just a correction, it does work for TaskChain as well. However, taskchains have multiple tasks (different than all the other workflow specs), and the SiteBlacklist is only enforced against the top level task (Task1).

**Comment by haozturk** [comment]
Thanks for the correction Alan, indeed I was aware of this. But since there is no taskchain workflow with only one Task, practically speaking the workflow fails anyway due to the failures in Task[>1]
