### ISSUE TITLE
Unified is producing excessive amount of files in EOS -- Disk quota exceeds

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#772]
**Impact of the bug**
All unified modules

**Describe the bug**
As we experienced couple of months ago, Unified modules are not able to run again since the its EOS quota was exceeded in terms of inodes: 

```
[haozturk@vocms0273 checkor]$ eos quota ls -p /eos/cms/store/unified -u cmsvoc
# pre-configuring default route to /eos/user/h/haozturk/
# -use $EOSHOME variable to override

┏━> Quota Node: /eos/cms/store/unified/
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│user      │used bytes│logi bytes│used files│aval bytes│aval logib│aval files│ filled[%]│vol-status│ino-status│
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
 cmsvoc       13.72 TB    6.86 TB    15.08 M   30.00 TB   15.00 TB    15.00 M    45.73 %         ok   exceeded 
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

The EOS quota was exceeded since lots of garbage files are being written to that space. Some example garbage files:

```
/eos/cms/store/unified/.sys.a#.v#1448666-testfile.32687e8a-3f99-11eb-89e4-a4bf0112e408
/eos/cms/store/unified/.sys.a#.v#1574804-testfile.f86bd124-191d-11eb-9095-a4bf0112e408
/eos/cms/store/unified/.sys.a#.v#164961-testfile.71f63bec-2e54-11eb-b4aa-a4bf0112e408
/eos/cms/store/unified/.sys.a#.v#165725-testfile.72f8aaa2-2e54-11eb-9317-a4bf0112e408
/eos/cms/store/unified/.sys.a#.v#166362-testfile.6af18ea0-2e54-11eb-9c96-a4bf0112e408
/eos/cms/store/unified/.sys.a#.v#166362-testfile.7ce7ee7e-2e54-11eb-bc48-a4bf0112e408
/eos/cms/store/unified/.sys.a#.v#1696077-testfile.d6327cb6-3fd3-11eb-9fa5-a4bf0112e408
/eos/cms/store/unified/.sys.a#.v#170116-testfile.83492ada-2e54-11eb-a6f5-a4bf0112e408
/eos/cms/store/unified/.sys.a#.v#1709216-testfile.62dddf18-3fd7-11eb-8b2c-a4bf0112e408
/eos/cms/store/unified/.sys.a#.v#1765095-testfile.3e1e0c2a-3fe6-11eb-8fd2-a4bf0112e408
```

**How to reproduce it**
Run: 
```
eos quota ls -p /eos/cms/store/unified -u cmsvoc
```
An example e-mail alert:
```
The cron command
     /usr/bin/eosfusebind;source /data/unified/WmAgentScripts/whatjob.sh > /eos/cms/store/unified/www/info.txt 2> /dev/null
produced the following output:
/bin/sh: line 1: /eos/cms/store/unified/www/info.txt: Disk quota exceeded
```

**Expected behavior**
I am currently running the following command in order to compile the list of all files in EOS unified space:
```
find /eos/cms/store/unified -type f -name "*" -print > /afs/cern.ch/user/h/haozturk/unified-all-files.txt 2>&1 &
```

Once this job ends, I'll investigate those files and remove all the redundant ones.

But, we should figure out how these garbage files are produced and prevent it!

**Additional context and error message**
@z4027163  FYI

**Comment by haozturk** [comment]
I am running this command for +12 hours and so far I've compiled 417k files which contain `sys` in its name:
`nohup find /eos/cms/store/unified -type f -name "sys" -print > /afs/cern.ch/user/h/haozturk/unifiedsys.txt 2>&1 &`
Some example files which were produced 30mins ago while this comment is being written:
```
[haozturk@vocms0268 ~]$ find /eos/cms/store/unified -type f  -mmin 30
/eos/cms/store/unified/.sys.a#.v#383065-testfile.1bfe5544-63a6-11eb-be26-a4bf0112e408
/eos/cms/store/unified/www/.sys.a#.v#closeout.html.0ec425d4-63a6-11eb-84ca-a4bf0112e408
/eos/cms/store/unified/www/.sys.a#.v#closeout.html.20b9b754-63a6-11eb-9728-a4bf0112e408
```
I haven't figured out how these files are being generated yet, I am still working on it.

**Comment by haozturk** [comment]
During the weekend, I have managed to decrease the number of files from 15.31M to 14.19M by cleaning `.sys` files. I believe there is more to clean:
```
[haozturk@vocms0268 ~]$ eos quota ls -p /eos/cms/store/unified -u cmsvoc
# pre-configuring default route to /eos/user/h/haozturk/
# -use $EOSHOME variable to override

┏━> Quota Node: /eos/cms/store/unified/
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│user      │used bytes│logi bytes│used files│aval bytes│aval logib│aval files│ filled[%]│vol-status│ino-status│
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
 cmsvoc       13.52 TB    6.76 TB    14.19 M   30.00 TB   15.00 TB    15.00 M    45.06 %         ok    warning 
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```
Please see the following ticket for the discussion with EOS team: https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2687211

**Comment by amaltaro** [comment]
> But, we should figure out how these garbage files are produced and prevent it!

I would go even further. How come Unified produces 15 million files on EOS!?! Is it a fact that Unified has been accumulating data on EOS for over the last 5 years without a single cleanup? Or is it because Unified is definitely writing too many things in there that are actually no longer needed (e.g., maybe job logs)?
Just my 2c.

**Comment by haozturk** [comment]
Thanks Alan, I fully agree. Unified's usage of EOS should be analyzed carefully and improved. Unified uses EOS mainly to store job logs of workflows in assistance manual, error reports of them and the logs of unified modules. Note that these are being cleaned regularly. The current issue stems from the massive production of these weird `.sys.a#` and `.sys.v#`  files (millions of them) whose source I still could not find. An example:

`/eos/cms/store/unified/www//joblogs/cmsunified_ACDC0_task_EXO-RunIISummer15wmLHEGS-07503__v1_T_200930_124200_6090/8028/EXO-RunIISummer16DR80Premix-15370_1/bccca11c-e702-49eb-a080-5de3a94f44bd-1-3-logArchive/job/WMTaskSpace/cmsRun1/.sys.v#.cmsRun1-stdout.log/1603792301.899f764e`

Btw, instead of storing the job logs, using them from `eoscmsweb` [1] is still in my radar. We can switch to that in the near future.

[1] https://eoscmsweb.cern.ch/eos/cms/store/logs/prod/recent/PRODUCTION/amaltaro_TEST-BACKFILL-task_EGM-Run3Summer19wmLHEGS-00003__v1_T_200924_164243_9049/EGM-Run3Summer19wmLHEGS-00003_0

**Comment by jenimal** [comment]
@amaltaro @haozturk   seeing this exact same issue again.
Should I start the cleanup like @haozturk  mentions above or are you doing something else right now>

Jen

**Comment by haozturk** [comment]
@jenimal  I am already doing some clean-ups, but it's not enough. I sent another message to EOS team and waiting a response from them: https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2687211

**Comment by haozturk** [comment]
This issue is fixed by contacting CERN EOS team. These `.sys` files are no longer produced and the inode situation is pretty stable as of now (about 6M)
