### ISSUE TITLE
Set SiteBlacklist parameter of the request by looking at campaign configuration for an effective banning

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#776]
**Impact of the bug**
Workflow assignment - Siteblacklisting

**Describe the bug**
So far, if we want to blacklist a site for a particular campaign - we were using the `SiteBlacklist` parameter of the campaigns and we were expecting workflows from this campaign not to run at those sites. Unfortunately, it turned out that this is not true. @amaltaro and @todor-ivanov  suggested to set `SiteBlacklist` parameter in the request schema in the workflow assignment for an effective blacklist from the point of WMAgents.
 
**How to reproduce it**
The campaigns of this workflow [1] blacklists `T2_CH_CERN_HLT`, but anyways workflow runs at HLT - so this does not work.

[1] https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_HIG-RunIISummer15wmLHEGS-04910__v1_T_210203_122619_295

**Expected behavior**
If a site is blacklisted within a campaign, then no workflow from that campaign should run at that site. The agreement to do so is to set the `SiteBlacklist` parameter in workflow schema by looking at campaign configuration. Unified has some logic regarding this, but apparently, it does not work.

**Additional context and error message**
@z4027163  @todor-ivanov  @amaltaro

**Comment by haozturk** [comment]
Unified restricts the `SiteWhitelist` parameter instead of setting the `SiteBlacklist` parameter. [1] This is the place where all the confusion comes from.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/46598ad74a0f7dbe99c3820a530bba92847c5525/utils.py#L7425

**Comment by amaltaro** [comment]
Hasan, just to be clear. If we want to avoid having jobs running at a given site (CPU resource), then the only way to let the workflow management to know it is by setting `SiteBlacklist=[blah]` **during** the workflow assignment (thus, this would be an additional parameter POSTed to request manager when setting a workflow to `assigned` status).

Having this information in the (Unified) campaign document is just a way to tell Unified that it has to black list sites for a given campaign. I'm just saying that this is not the only way to deal with it.

Given that ban on HLT is solely an effect of not having the input data/pileup at CERN, I think we could use of some new feature/automation in WMCore to make everyone's life easier (remember my pileup management discussion?)

**Comment by haozturk** [comment]
Alan, thanks a lot. #777 implements your suggestion. Regarding the pileup management discussion, maybe we should start discussing it again soon and start taking actions on it.

**Comment by amaltaro** [comment]
I'm afraid I can't commit myself to this task this quarter. But I would be happy to have some discussions with you and perhaps guide you with the first steps (which will depend heavily from Unified configurations and functionality) ;)

**Comment by haozturk** [comment]
Sounds good! I will come up with a chat request in the upcoming days, then.
