### ISSUE TITLE
Filtering and automation panel: Implement getErrors function

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#783]
**Impact of the new feature**
Management of resubmissions

**Is your feature request related to a problem? Please describe.**
Motivation: #731 

**Describe the solution you'd like**
This function [1] should return the errors of the workflow in the given format. Both Unified and WorkflowWebTools have similar support. We can get some help from there.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/21cb7dc8efbd992d5282b24e8598a8f842b3f70c/assistance/Workflow.py#L48

**Describe alternatives you've considered**
-

**Additional context**
@hbakhshi  FYI

**Comment by hbakhshi** [comment]
this feature implemented in a new package [here](https://gitlab.cern.ch/CMSToolsIntegration/workflow/)
