### ISSUE TITLE
Running stepchains w/ 4 cores instead of 8

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#831]
**Impact of the new feature**
CPU efficiency

**Is your feature request related to a problem? Please describe.**
#827 

**Describe the solution you'd like**
I ran some tests. I ran the same workflow as taskchain, stepchain w/ 4 cores and stepchain w/ 8 cores. Here is the results: 

1. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer20UL16wmLHEGEN-01328

| Configuration      | CPU efficiency on T1&T2 |
| ----------- | ----------- |
| [Taskchain](https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_HIG-RunIISummer20UL16wmLHEGEN-Backfill-01328__v1_T_210517_120648_2765)      | 86.5%       |
| [Stepchain w/ 4 cores](https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_HIG-RunIISummer20UL16wmLHEGEN-Backfill-01328__v1_T_210517_120935_8390)   | 80.9%        |
| [Stepchain w/ 8 cores](https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_HIG-RunIISummer20UL16wmLHEGEN-Backfill-01328__v1_T_210517_120805_8254)   | 63.7%        |

2. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TOP-RunIISummer20UL16wmLHEGEN-00152

| Configuration      | CPU efficiency on T1&T2 |
| ----------- | ----------- |
| [Taskchain](https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_TOP-RunIISummer20UL16wmLHEGEN-Backfill-00152__v1_T_210518_120934_8054)      | 89.3%       |
| [Stepchain w/ 4 cores](https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_TOP-RunIISummer20UL16wmLHEGEN-Backfill-00152__v1_T_210518_121233_1189)   | 80.5%        |
| [Stepchain w/ 8 cores](https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_TOP-RunIISummer20UL16wmLHEGEN-Backfill-00152__v1_T_210518_121123_156)   | 70.1%        |

I check the efficiency over here: https://cmsdatapop.web.cern.ch/cmsdatapop/cpu_eff/production/CPU_Efficiency_Table.html

For a given workflow, efficiency is calculated as follows: 
```
CPUTimePerCore = 0
WallTime = 0
For each successful and completed job:
    CPUTimePerCore += (CPU time of the job) / (Number of cores of the job)
    WallTime += Wall time of the job

CPU eff = CPUTimePerCore / WallTime
```

According to this test, running stepchains w/ 4 cores looks promising in terms of CPU efficiency.

**Describe alternatives you've considered**
None

**Additional context**
@drkovalskyi  @z4027163  @jenimal  FYI

**Comment by drkovalskyi** [comment]
What is the expected efficiency for each workflow as it is estimated by the StepChain conversion script? Are we underestimating the conversion inefficiency?

**Comment by haozturk** [comment]
It's 82.5% and 90.4% respectively for 8 cores stepchain conversions. This underestimation in conversion inefficiency is not surprising to me, since the conversion script assumes that taskchain is 100% efficient and it gives a value relative to that. This is one of the weak points of the conversion, IMO. Using multi-core validation in conversion logic should improve this problem.

**Comment by drkovalskyi** [comment]
It's not an issue. The conversion script doesn't need to need to be able to estimate absolute efficiency (only relative). So the relative efficiency of the first workflow is 73.6%  and the second one is 78.5%. These numbers are significantly lower than 82.5% and 90.4%. That's an issue worth understanding.

**Comment by haozturk** [comment]
Right, it might be due to bad time/event estimates, i.e. perhaps the real time/event value is much greater than the estimated value, especially for GEN. I'll try to dig up kibana a little bit to get the real time/event value.

**Comment by drkovalskyi** [comment]
That's a good idea. It will help us to understand if the issue is in the algorithm or in the input.

**Comment by haozturk** [comment]
While that's under progress, what do you think about lowering nCores to 4, Dima? Do you think these tests are enough? Looks like efficiency improves significantly.

**Comment by drkovalskyi** [comment]
4-core results look pretty good. I think it's a reasonable option to use them, but keep in mind that you may start causing failures for long jobs that won't get enough resources to produce enough events per lumi. Personally, instead of manually tuning parameters, I would focus on making sure that the conversion script is working properly taking into account the multi-core GEN validation with additional checks for efficiencies. Most likely it will make the same choice, but it won't require your attention.

**Comment by haozturk** [comment]
I agree. Multi-core GEN validation improvement will likely to take some time, though (1-2 weeks at least). I'm currently revising the equation, then I'll run some tests etc. While that's also in progress, I'd prefer to switch to 4-cores setting (at least for some campaigns) today. This way, we'll have another contribution to increase the cpu efficiency trend and we'll also have some data to judge 4-cores setting with real production workflows. Does that sound reasonable?

**Comment by drkovalskyi** [comment]
Sounds reasonable. Just don't forget that most likely you won't see any effect on a global scale over 1-2 weeks.
