### ISSUE TITLE
Make case insensitive check for pilots

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#843]
**Impact of the bug**
pilot workflows

**Describe the bug**
Pilot workflows are not assigned if SubRequestType is not exactly `pilot`. https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_PPD-HINPbPbWinter16wmLHEGSHIMix-00002__v1_T_210526_132545_7657 For this request, it's `Pilot`

**How to reproduce it**
Check the request above

**Expected behavior**
We should make a case insensitive check

**Additional context and error message**
None

**Comment by scarletnorberg** [comment]
AHHH I thought we had fixed that when talking to Justinas before.
