### ISSUE TITLE
New datatier to handle in output data placement: GEN-SIM-DIGI-RAW-HLTDEBUG-RECO

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#857]
**Impact of the new feature**
Output placement of GEN-SIM-DIGI-RAW-HLTDEBUG-RECO datasets

**Is your feature request related to a problem? Please describe.**
This is a new datatier for which we should configure disk and tape rules

**Describe the solution you'd like**
PdmV informed us that they should go to DISK. I'm waiting their response about tape.

**Describe alternatives you've considered**
None

**Additional context**
@amaltaro  @todor-ivanov  @z4027163  @jenimal  FYI

**Comment by jordan-martins** [comment]
Hi @haozturk, I am going to bring Phase2 people so they can deliver to u a more precise scenario!

**Comment by srimanob** [comment]
Hi @haozturk 
Is GEN-SIM-DIGI-RAW-HLTDEBUG-RECO new? 

I see it since 2014, https://github.com/dmwm/DBS/blob/00f44b9b32cefd79888eb1ded0ab8e359ab47965/Schema/DDL/initialize-template.sql
It is comparable to FEVTDEBUGHLT, and it should go to tape also. I am trying to confirm in MatterMost on June 16, but no answer yet.
https://mattermost.web.cern.ch/cms-o-and-c/pl/4uxy9deyh3frjxaqqug78nds9e

**Comment by haozturk** [comment]
Hi Phat, it's at least new to Unified configurations [1,2,3] These configurations are in place for years and I do not see it there. 
[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L233
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L229 
[3] https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L213

**Comment by srimanob** [comment]
Hi, OK, it is missing somehow on the way. 
Actually, the question is maybe what does not exist? Datatier itself or Rule of datatier?

Would you mind to have it with the same rule as FEVT (tiers_to_DDM), it is the same. Thanks.

**Comment by haozturk** [comment]
Thanks Phat, should I also understand that it should go to tape?

**Comment by srimanob** [comment]
I would say, yes, it should go to tape. We can clean it up also during tape cleanup campaign.

Note that, we don't produce this GEN-SIM-DIGI-RAW-HLTDEBUG-RECO, and FEVT much in production. For relvals, we produce it as eventcontent, but in the shadow of GEN-SIM-RECO datatier.
