### ISSUE TITLE
Compare taskchain and stepchain in terms of turnaround time

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#872]
**Impact of the new feature**
Whole production

**Is your feature request related to a problem? Please describe.**
Taskchain requests seem to be slow in terms of turnaround time (TAT) compared to stepchain. The issue becomes more critical for high priority requests.

**Describe the solution you'd like**
We should analyze these two types requests in terms of TAT and understand how they perform. If we conclude that taskchains are considerably slow, one suggestion of mine could be 

- Convert high priority requests to stepchain at the cost of cpu efficiency.

Here I put some results for our first test. We ran the same workflow both as taskchain and stepchain and monitored output growth: https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL18GEN-00062 

| Request Type      | Output produced | Running for (days)| Priority | 
| ----------- | ----------- | ----------- | ----------- |
| [Taskchain](https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_BPH-RunIISummer20UL18GEN-00062__v1_T_210505_112300_2288)      | 16%       | 12.5       | 120k       |
| [Stepchain](https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_BPH-RunIISummer20UL18GEN-00062__v1_T_210630_165139_3304)   | 82%        | 7        | 120k        |

This clearly shows that stepchain is much quicker. Further tests can be performed to be sure about this conclusion.

**Describe alternatives you've considered**
Work with requestors such that we submit more stepchain friendly workflows (mostly related to GEN)

**Additional context**
@drkovalskyi  @z4027163  @amaltaro  @todor-ivanov FYI

**Comment by drkovalskyi** [comment]
Fully support the proposal to change the threshold for high priority requests. The turnaround time is more important for high priority requests.

**Comment by haozturk** [comment]
Note the CPU efficiency of the requests:
| Request Type      | Output produced | Running for (days)| Priority | CPU efficiency | 
| ----------- | ----------- | ----------- | ----------- | ----------- |
| [Taskchain](https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_BPH-RunIISummer20UL18GEN-00062__v1_T_210505_112300_2288)      | 16%       | 12.5       | 120k       | 59.2% | 
| [Stepchain](https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_BPH-RunIISummer20UL18GEN-00062__v1_T_210630_165139_3304)   | 82%        | 7        | 120k        | 33.6% | 


Source for cpu efficiencies: https://cmsdatapop.web.cern.ch/cmsdatapop/cpu_eff/production/CPU_Efficiency_Table.html

**Comment by haozturk** [comment]
Distribution of currently running workflows in terms of their stepchain efficiency
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32415369/125446255-f7e6c27c-aca3-4954-97a5-8c56f4061d5d.png">
